iPlug2: IVectorBase Class Reference
IVectorBase Class Reference
IGraphics::IControls::BaseControls
A base interface to be combined with IControl for vectorial controls "IVControls", in order for them to share a common style If you need more flexibility, you're on your own!
#include <IControl.h>
Public Member Functions
IVectorBase (const IVStyle &style, bool labelInWidget=false, bool valueInWidget=false)
void AttachIControl (IControl *pControl, const char *label)
void SetColor (EVColor colorIdx, const IColor &color)
void SetColors (const IVColorSpec &spec)
const IColor & GetColor (EVColor color) const
void SetLabelStr (const char *label)
void SetValueStr (const char *value)
void SetWidgetFrac (float frac)
void SetAngle (float angle)
void SetShowLabel (bool show)
void SetShowValue (bool show)
void SetRoundness (float roundness)
void SetDrawFrame (bool draw)
void SetDrawShadows (bool draw)
void SetEmboss (bool draw)
void SetShadowOffset (float offset)
void SetFrameThickness (float thickness)
void SetSplashRadius (float radius)
void SetSplashPoint (float x, float y)
void SetShape (EVShape shape)
virtual void SetStyle (const IVStyle &style)
IVStyle GetStyle () const
IRECT GetAdjustedHandleBounds (IRECT handleBounds) const
float GetRoundedCornerRadius (const IRECT &bounds) const
void DrawSplash (IGraphics &g, const IRECT &clipRegion=IRECT())
virtual void DrawBackGround (IGraphics &g, const IRECT &rect)
virtual void DrawWidget (IGraphics &g)
virtual void DrawLabel (IGraphics &g)
virtual void DrawValue (IGraphics &g, bool mouseOver)
void DrawHandle (IGraphics &g, EVShape shape, const IRECT &bounds, bool pressed, bool mouseOver, bool disabled)
void DrawPressableEllipse (IGraphics &g, const IRECT &bounds, bool pressed, bool mouseOver, bool disabled)
IRECT DrawPressableRectangle (IGraphics &g, const IRECT &bounds, bool pressed, bool mouseOver, bool disabled, bool rtl=true, bool rtr=true, bool rbl=true, bool rbr=true)
/todo
IRECT DrawPressableTriangle (IGraphics &g, const IRECT &bounds, bool pressed, bool mouseOver, float angle, bool disabled)
Draw a triangle-shaped vector button.
IRECT MakeRects (const IRECT &parent, bool hasHandle=false)
Protected Attributes
IControl * mControl = nullptr
IVStyle mStyle
bool mLabelInWidget = false
bool mValueInWidget = false
float mSplashRadius = 0.f
IVec2 mSplashPoint = {0.f, 0.f}
float mMaxSplashRadius = 50.f
float mTrackSize = 2.f
float mValueDisplayFrac = 0.66f
IRECT mWidgetBounds
IRECT mLabelBounds
IRECT mValueBounds
WDL_String mLabelStr
WDL_String mValueStr
EVShape mShape = EVShape::Rectangle
Detailed Description
A base interface to be combined with IControl for vectorial controls "IVControls", in order for them to share a common style If you need more flexibility, you're on your own!
Definition at line 610 of file IControl.h.
Member Function Documentation
IRECT IVectorBase::DrawPressableRectangle (IGraphics & g, const IRECT & bounds, bool pressed, bool mouseOver, bool disabled, bool rtl = true, bool rtr = true, bool rbl = true, bool rbr = true) inline
/todo
Parameters
IGraphics&g /todo
bounds /todo
pressed /todo
mouseOver /todo
Returns
/todo
Definition at line 818 of file IControl.h.
References IGraphics::DrawRoundRect(), IGraphics::FillRoundRect(), IRECT::GetPadded(), IRECT::GetTranslated(), IRECT::ReduceFromBottom(), and IRECT::ReduceFromRight().
Referenced by IVTabSwitchControl::Draw(), and IVPanelControl::Draw().
IRECT IVectorBase::DrawPressableTriangle (IGraphics & g, const IRECT & bounds, bool pressed, bool mouseOver, float angle, bool disabled) inline
Draw a triangle-shaped vector button.
Parameters
g The IGraphics context used for drawing
bounds Where to draw the button
pressed Whether to draw the button pressed or unpressed
mouseOver Whether mouse is currently hovering on control
Definition at line 901 of file IControl.h.
References IGraphics::DrawTriangle(), IGraphics::FillTriangle(), IRECT::GetFromBottom(), IRECT::GetFromTop(), IRECT::GetMidVPadded(), IRECT::GetReducedFromBottom(), IRECT::GetReducedFromTop(), IRECT::GetScaledAboutCentre(), IRECT::GetTranslated(), IRECT::H(), IRECT::MW(), and IRECT::W().
Referenced by IVRangeSliderControl::Draw().
The documentation for this class was generated from the following file:
IControl.h