iPlug2: IPlugProcessor Class Reference
IPlugProcessor Class Reference abstract
The base class for IPlug Audio Processing.
#include <IPlugProcessor.h>
Public Member Functions
IPlugProcessor (const Config &config, EAPI plugAPI)
IPlugProcessor constructor.
IPlugProcessor (const IPlugProcessor &)=delete
IPlugProcessor & operator= (const IPlugProcessor &)=delete
virtual void ProcessBlock (sample **inputs, sample **outputs, int nFrames)
Override in your plug-in class to process audio In ProcessBlock you are always guaranteed to get valid pointers to all the channels the plugin requested (the maximum possible input channel count and the maximum possible output channel count including multiple buses).
virtual void ProcessMidiMsg (const IMidiMsg &msg)
Override this method to handle incoming MIDI messages.
virtual void ProcessSysEx (ISysEx &msg)
Override this method to handle incoming MIDI System Exclusive (SysEx) messages.
virtual void OnReset ()
Override this method in your plug-in class to do something prior to playback etc.
virtual void OnActivate (bool active)
Override OnActivate() which should be called by the API class when a plug-in is "switched on" by the host on a track when the channel count is known.
virtual bool SendMidiMsg (const IMidiMsg &msg)=0
Send a single MIDI message // TODO: info about what thread should this be called on or not called on!
virtual bool SendMidiMsgs (WDL_TypedBuf< IMidiMsg > &msgs)
Send a collection of MIDI messages // TODO: info about what thread should this be called on or not called on!
virtual bool SendSysEx (const ISysEx &msg)
Send a single MIDI System Exclusive (SysEx) message // TODO: info about what thread should this be called on or not called on!
double GetSampleRate () const
int GetBlockSize () const
int GetLatency () const
int GetTailSize ()
bool GetBypassed () const
bool GetRenderingOffline () const
double GetSamplePos () const
double GetTempo () const
double GetSamplesPerBeat () const
void GetTimeSig (int &numerator, int &denominator) const
int NIOConfigs () const
const IOConfig * GetIOConfig (int idx) const
int MaxNBuses (ERoute direction) const
Used to determine the maximum number of input or output buses based on what was specified in the channel I/O config string.
int MaxNChannelsForBus (ERoute direction, int busIdx) const
For a given input or output bus what is the maximum possible number of channels.
bool HasWildcardBus (ERoute direction) const
Check if we have any wildcard characters in the channel I/O configs.
int MaxNChannels (ERoute direction) const
bool IsChannelConnected (ERoute direction, int chIdx) const
int NChannelsConnected (ERoute direction) const
int NInChansConnected () const
Convenience method to find out how many input channels are connected.
int NOutChansConnected () const
Convenience method to find out how many output channels are connected.
bool LegalIO (int NInputChans, int NOutputChans) const
Check if a certain configuration of input channels and output channels is allowed based on the channel I/O configs.
bool HasSidechainInput () const
int NSidechainChannels () const
void LimitToStereoIO ()
This is called by IPlugVST in order to limit a plug-in to stereo I/O for certain picky hosts.
bool IsInstrument () const
bool IsMidiEffect () const
int GetAUPluginType () const
/todo
bool DoesMIDIIn () const
bool DoesMIDIOut () const
bool DoesMPE () const
void SetChannelLabel (ERoute direction, int idx, const char *formatStr, bool zeroBased=false)
This allows you to label input/output channels in supporting VST2 hosts.
virtual void SetLatency (int latency)
Call this if the latency of your plug-in changes after initialization (perhaps from OnReset()) This may not be supported by the host.
void SetTailSize (int tailSize)
Call this method if you need to update the tail size at runtime, for example if the decay time of your reverb effect changes Some apis have special interpretations of certain numbers.
Static Public Member Functions
static int ParseChannelIOStr (const char *IOStr, WDL_PtrList< IOConfig > &channelIOList, int &totalNInChans, int &totalNOutChans, int &totalNInBuses, int &totalNOutBuses)
A static method to parse the config.h channel I/O string.
Protected Member Functions
void SetChannelConnections (ERoute direction, int idx, int n, bool connected)
void AttachBuffers (ERoute direction, int idx, int n, PLUG_SAMPLE_DST **ppData, int nFrames)
void AttachBuffers (ERoute direction, int idx, int n, PLUG_SAMPLE_SRC **ppData, int nFrames)
void PassThroughBuffers (PLUG_SAMPLE_SRC type, int nFrames)
void PassThroughBuffers (PLUG_SAMPLE_DST type, int nFrames)
void ProcessBuffers (PLUG_SAMPLE_SRC type, int nFrames)
void ProcessBuffers (PLUG_SAMPLE_DST type, int nFrames)
void ProcessBuffersAccumulating (int nFrames)
void ZeroScratchBuffers ()
void SetSampleRate (double sampleRate)
void SetBlockSize (int blockSize)
void SetBypassed (bool bypassed)
void SetTimeInfo (const ITimeInfo &timeInfo)
void SetRenderingOffline (bool renderingOffline)
const WDL_String & GetChannelLabel (ERoute direction, int idx)
Protected Attributes
std::unique_ptr< NChanDelayLine< sample > > mLatencyDelay = nullptr
A multichannel delay line used to delay the bypassed signal when a plug-in with latency is bypassed.
ITimeInfo mTimeInfo
Contains detailed information about the transport state.
Detailed Description
The base class for IPlug Audio Processing.
It knows nothing about presets or parameters or user interface.
Definition at line 39 of file IPlugProcessor.h.
Constructor & Destructor Documentation
IPlugProcessor::IPlugProcessor (const Config & config, EAPI plugAPI)
IPlugProcessor constructor.
Parameters
config /todo
plugAPI /todo
Definition at line 24 of file IPlugProcessor.cpp.
References ParseChannelIOStr().
Member Function Documentation
bool IPlugProcessor::DoesMIDIIn () const inline
Returns
true if the plug-in was configured to receive midi at compile time
Definition at line 220 of file IPlugProcessor.h.
Referenced by GetAUPluginType(), IPlugVST2::HostSpecificInit(), and IPlugAU::SendSysEx().
bool IPlugProcessor::DoesMIDIOut () const inline
Returns
true if the plug-in was configured to receive midi at compile time
Definition at line 223 of file IPlugProcessor.h.
Referenced by IPlugVST2::HostSpecificInit().
bool IPlugProcessor::DoesMPE () const inline
Returns
true if the plug-in was configured to support midi polyphonic expression at compile time
Definition at line 226 of file IPlugProcessor.h.
References SetChannelLabel(), and SetLatency().
int IPlugProcessor::GetAUPluginType () const inline
/todo
Returns
int /todo
Definition at line 198 of file IPlugProcessor.h.
References DoesMIDIIn().
int IPlugProcessor::GetBlockSize () const inline
Returns
Current block size in samples
Definition at line 103 of file IPlugProcessor.h.
bool IPlugProcessor::GetBypassed () const inline
Returns
true if the plugin is currently bypassed
Definition at line 112 of file IPlugProcessor.h.
const IOConfig* IPlugProcessor::GetIOConfig (int idx) const inline
Returns
const Pointer to an IOConfig at idx. Can return nullptr if idx is invalid
Definition at line 136 of file IPlugProcessor.h.
References MaxNBuses(), and MaxNChannelsForBus().
Referenced by LegalIO(), and MaxNChannelsForBus().
int IPlugProcessor::GetLatency () const inline
Returns
Plugin latency (in samples)
Definition at line 106 of file IPlugProcessor.h.
bool IPlugProcessor::GetRenderingOffline () const inline
Returns
true if the plugin is currently rendering off-line
Definition at line 115 of file IPlugProcessor.h.
double IPlugProcessor::GetSamplePos () const inline
Returns
The number of samples elapsed since start of project timeline.
Definition at line 119 of file IPlugProcessor.h.
References mTimeInfo.
double IPlugProcessor::GetSampleRate () const inline
Returns
Sample rate (in Hz)
Definition at line 100 of file IPlugProcessor.h.
Referenced by GetSamplesPerBeat().
double IPlugProcessor::GetSamplesPerBeat () const
Returns
The number of samples in a beat
Definition at line 105 of file IPlugProcessor.cpp.
References GetSampleRate(), and GetTempo().
Referenced by GetTempo().
int IPlugProcessor::GetTailSize () inline
Returns
The tail size in samples (useful for reverberation plug-ins, that may need to decay after the transport stops or an audio item ends)
Definition at line 109 of file IPlugProcessor.h.
Referenced by IPlugVST2::HostSpecificInit().
double IPlugProcessor::GetTempo () const inline
Returns
The tempo in beats per minute
Definition at line 122 of file IPlugProcessor.h.
References GetSamplesPerBeat(), and mTimeInfo.
Referenced by GetSamplesPerBeat().
void IPlugProcessor::GetTimeSig (int & numerator, int & denominator) const inline
Parameters
numerator The upper part of the current time signature e.g "6" in the time signature 6/8
denominator The lower part of the current time signature e.g "8" in the time signature 6/8
Definition at line 129 of file IPlugProcessor.h.
References mTimeInfo.
bool IPlugProcessor::HasSidechainInput () const inline
Returns
true if this plug-in has a side-chain input, which may not necessarily be active in the current I/O config
Definition at line 182 of file IPlugProcessor.h.
References MaxNBuses().
bool IPlugProcessor::HasWildcardBus (ERoute direction) const inline
Check if we have any wildcard characters in the channel I/O configs.
Parameters
direction Return input or output bus count
Returns
true if the bus has a wildcard, meaning it should work on any number of channels
Definition at line 152 of file IPlugProcessor.h.
Referenced by MaxNChannelsForBus().
bool IPlugProcessor::IsChannelConnected (ERoute direction, int chIdx) const inline
Parameters
direction Whether you want to test inputs or outputs
chIdx channel index
Returns
true if the host has connected this channel
Definition at line 161 of file IPlugProcessor.h.
References NChannelsConnected().
Referenced by NChannelsConnected().
bool IPlugProcessor::IsInstrument () const inline
Returns
true if the plug-in was configured as an instrument at compile time
Definition at line 191 of file IPlugProcessor.h.
Referenced by IPlugVST2::HostSpecificInit().
bool IPlugProcessor::IsMidiEffect () const inline
Returns
true if the plug-in was configured as an MFX at compile time
Definition at line 194 of file IPlugProcessor.h.
bool IPlugProcessor::LegalIO (int NInputChans, int NOutputChans) const
Check if a certain configuration of input channels and output channels is allowed based on the channel I/O configs.
Parameters
NInputChans Number of inputs to test, if set to -1 = check NOutputChans only
NOutputChans Number of outputs to test, if set to -1 = check NInputChans only
Returns
true if the configurations is valid
Definition at line 163 of file IPlugProcessor.cpp.
References GetIOConfig(), IOConfig::GetTotalNChannels(), and NIOConfigs().
Referenced by NOutChansConnected().
void IPlugProcessor::LimitToStereoIO ()
This is called by IPlugVST in order to limit a plug-in to stereo I/O for certain picky hosts.
Todo:
may no longer be relevant
Definition at line 177 of file IPlugProcessor.cpp.
References MaxNChannels().
Referenced by IPlugVST2::HostSpecificInit(), and NSidechainChannels().
int IPlugProcessor::MaxNBuses (ERoute direction) const
Used to determine the maximum number of input or output buses based on what was specified in the channel I/O config string.
Parameters
direction Return input or output bus count
Returns
The maximum bus count across all channel I/O configs
Definition at line 117 of file IPlugProcessor.cpp.
References NIOConfigs().
Referenced by GetIOConfig(), HasSidechainInput(), and MaxNChannelsForBus().
int IPlugProcessor::MaxNChannels (ERoute direction) const inline
Parameters
direction Whether you want to test inputs or outputs
Returns
Total number of input or output channel buffers (not necessarily connected)
Definition at line 156 of file IPlugProcessor.h.
Referenced by IPlugVST2::HostSpecificInit(), LimitToStereoIO(), ParseChannelIOStr(), IPlugAPPHost::ProbeAudioIO(), and SetChannelLabel().
int IPlugProcessor::MaxNChannelsForBus (ERoute direction, int busIdx) const
For a given input or output bus what is the maximum possible number of channels.
Parameters
direction Return input or output bus count
busIdx The index of the bus to look up
Returns
return The maximum number of channels on that bus
Definition at line 129 of file IPlugProcessor.cpp.
References GetIOConfig(), HasWildcardBus(), MaxNBuses(), IOConfig::NChansOnBusSAFE(), and NIOConfigs().
Referenced by GetIOConfig().
int IPlugProcessor::NChannelsConnected (ERoute direction) const
Parameters
direction Whether you want to test inputs or outputs
Returns
The number of channels connected for input/output. WARNING: this assumes consecutive channel connections
Definition at line 150 of file IPlugProcessor.cpp.
References IsChannelConnected().
Referenced by IsChannelConnected(), NInChansConnected(), and NOutChansConnected().
int IPlugProcessor::NInChansConnected () const inline
Convenience method to find out how many input channels are connected.
Returns
The number of channels connected for input. WARNING: this assumes consecutive channel connections
Definition at line 169 of file IPlugProcessor.h.
References NChannelsConnected().
int IPlugProcessor::NIOConfigs () const inline
Returns
The number of channel I/O configs derived from the channel io string
Definition at line 133 of file IPlugProcessor.h.
Referenced by LegalIO(), MaxNBuses(), and MaxNChannelsForBus().
int IPlugProcessor::NOutChansConnected () const inline
Convenience method to find out how many output channels are connected.
Returns
The number of channels connected for output. WARNING: this assumes consecutive channel connections
Definition at line 173 of file IPlugProcessor.h.
References LegalIO(), and NChannelsConnected().
int IPlugProcessor::NSidechainChannels () const inline
Returns
The number of channels and the side-chain input
Todo:
this will change
Definition at line 185 of file IPlugProcessor.h.
References LimitToStereoIO().
virtual void IPlugProcessor::OnActivate (bool active) inline virtual
Override OnActivate() which should be called by the API class when a plug-in is "switched on" by the host on a track when the channel count is known.
This may not work reliably because different hosts have different interpretations of "activate". Unlike OnReset() which called when the transport is reset or the sample rate changes OnActivate() is a good place to handle change of I/O connections.
Parameters
active true if the host has activated the plug-in
Definition at line 80 of file IPlugProcessor.h.
References SendMidiMsg(), and SendMidiMsgs().
Referenced by IPlugVST2::HostSpecificInit(), and IPlugAU::SendSysEx().
virtual void IPlugProcessor::OnReset () inline virtual
Override this method in your plug-in class to do something prior to playback etc.
(e.g.clear buffers, update internal DSP with the latest sample rate)
Definition at line 74 of file IPlugProcessor.h.
Referenced by IPlugVST2::HostSpecificInit(), and IPlugAU::SendSysEx().
int IPlugProcessor::ParseChannelIOStr (const char * IOStr, WDL_PtrList< IOConfig > & channelIOList, int & totalNInChans, int & totalNOutChans, int & totalNInBuses, int & totalNOutBuses) static
A static method to parse the config.h channel I/O string.
Parameters
IOStr Space separated cstring list of I/O configurations for this plug-in in the format ninchans-noutchans. A hypen character (-) deliminates input-output. Supports multiple buses, which are indicated using a period (.) character. For instance plug-in that supports mono input and mono output with a mono side-chain input could have a channel io string of "1.1-1". A drum synthesiser with four stereo output busses could be configured with a io string of "0-2.2.2.2";
channelIOList A list of pointers to ChannelIO structs, where we will store here
totalNInChans The total number of input channels across all buses will be stored here
totalNOutChans The total number of output channels across all buses will be stored here
totalNInBuses The total number of input buses across all channel I/O configs will be stored here
totalNOutBuses The total number of output buses across all channel I/O configs will be stored here
Returns
The number of space separated channel I/O configs that have been detected in IOStr
Definition at line 201 of file IPlugProcessor.cpp.
References CastCopy(), MaxNChannels(), mLatencyDelay, IOConfig::NChansOnBusSAFE(), and ProcessBlock().
Referenced by IPlugProcessor(), and SetTailSize().
void IPlugProcessor::ProcessBlock (sample ** inputs, sample ** outputs, int nFrames) virtual
Override in your plug-in class to process audio In ProcessBlock you are always guaranteed to get valid pointers to all the channels the plugin requested (the maximum possible input channel count and the maximum possible output channel count including multiple buses).
If the host hasn't connected all the pins, the unconnected channels will be full of zeros. THIS METHOD IS CALLED BY THE HIGH PRIORITY AUDIO THREAD - You should be careful not to do any unbounded, blocking operations such as file I/O which could cause audio dropouts
Parameters
inputs Two-dimensional array containing the non-interleaved input buffers of audio samples for all channels
outputs Two-dimensional array for audio output (non-interleaved).
nFrames The block size for this block: number of samples per channel.
Definition at line 70 of file IPlugProcessor.cpp.
Referenced by ParseChannelIOStr().
void IPlugProcessor::ProcessMidiMsg (const IMidiMsg & msg) virtual
Override this method to handle incoming MIDI messages.
The method is called prior to ProcessBlock(). You can use IMidiQueue in combination with this method in order to queue the message and process at the appropriate time in ProcessBlock() THIS METHOD IS CALLED BY THE HIGH PRIORITY AUDIO THREAD - You should be careful not to do any unbounded, blocking operations such as file I/O which could cause audio dropouts
Parameters
msg The incoming midi message (includes a timestamp to indicate the offset in the forthcoming block of audio to be processed in ProcessBlock())
Definition at line 89 of file IPlugProcessor.cpp.
References SendMidiMsg().
Referenced by IPlugVST2::HostSpecificInit(), and IPlugAU::SendSysEx().
virtual void IPlugProcessor::ProcessSysEx (ISysEx & msg) inline virtual
Override this method to handle incoming MIDI System Exclusive (SysEx) messages.
The method is called prior to ProcessBlock(). THIS METHOD IS CALLED BY THE HIGH PRIORITY AUDIO THREAD - You should be careful not to do any unbounded, blocking operations such as file I/O which could cause audio dropouts
Definition at line 71 of file IPlugProcessor.h.
Referenced by IPlugVST2::HostSpecificInit(), and IPlugAU::SendSysEx().
virtual bool IPlugProcessor::SendMidiMsg (const IMidiMsg & msg) pure virtual
Send a single MIDI message // TODO: info about what thread should this be called on or not called on!
Parameters
msg The IMidiMsg to send
Returns
true if successful
Implemented in IPlugVST3ProcessorBase, IPlugAAX, IPlugAU, IPlugAUv3, IPlugAPP, IPlugVST2, and IPlugWAM.
Referenced by OnActivate(), ProcessMidiMsg(), and SendMidiMsgs().
bool IPlugProcessor::SendMidiMsgs (WDL_TypedBuf< IMidiMsg > & msgs) virtual
Send a collection of MIDI messages // TODO: info about what thread should this be called on or not called on!
Parameters
msgs The IMidiMsg to send
Returns
true if successful
Reimplemented in IPlugAU.
Definition at line 94 of file IPlugProcessor.cpp.
References SendMidiMsg().
Referenced by OnActivate().
virtual bool IPlugProcessor::SendSysEx (const ISysEx & msg) inline virtual
Send a single MIDI System Exclusive (SysEx) message // TODO: info about what thread should this be called on or not called on!
Parameters
msg The ISysEx to send
Returns
true if successful
Reimplemented in IPlugAU, IPlugAUv3, IPlugAPP, IPlugVST2, and IPlugWAM.
Definition at line 97 of file IPlugProcessor.h.
void IPlugProcessor::SetChannelLabel (ERoute direction, int idx, const char * formatStr, bool zeroBased = false)
This allows you to label input/output channels in supporting VST2 hosts.
For example a 4 channel plug-in that deals with FuMa BFormat first order ambisonic material, might label these channels "W", "X", "Y", "Z", rather than the default "input 1", "input 2", "input 3", "input 4"
Parameters
idx The index of the channel that you wish to label
formatStr printf style format string to compose label for the channel - where i will be the channel index
zeroBased If true the index in the format string will be zero based
Definition at line 186 of file IPlugProcessor.cpp.
References MaxNChannels().
Referenced by DoesMPE().
void IPlugProcessor::SetLatency (int latency) virtual
Call this if the latency of your plug-in changes after initialization (perhaps from OnReset()) This may not be supported by the host.
The method is virtual because it's overridden in API classes.
Parameters
latency Latency in samples
Reimplemented in IPlugAAX, IPlugAU, IPlugVST3, IPlugVST2, and IPlugWAM.
Definition at line 192 of file IPlugProcessor.cpp.
References mLatencyDelay.
Referenced by DoesMPE(), IPlugVST2::SetLatency(), IPlugVST3::SetLatency(), IPlugAU::SetLatency(), and IPlugAAX::SetLatency().
void IPlugProcessor::SetTailSize (int tailSize) inline
Call this method if you need to update the tail size at runtime, for example if the decay time of your reverb effect changes Some apis have special interpretations of certain numbers.
For VST3 set to 0xffffffff for infinite tail, or 0 for none (default) For VST2 setting to 1 means no tail
Parameters
tailSize the new tailsize in samples
Definition at line 245 of file IPlugProcessor.h.
References mTimeInfo, and ParseChannelIOStr().
Member Data Documentation
std::unique_ptr<NChanDelayLine<sample> > IPlugProcessor::mLatencyDelay = nullptr protected
A multichannel delay line used to delay the bypassed signal when a plug-in with latency is bypassed.
Definition at line 310 of file IPlugProcessor.h.
Referenced by ParseChannelIOStr(), and SetLatency().
The documentation for this class was generated from the following files:
IPlugProcessor.h
IPlugProcessor.cpp