iPlug2: IBTextControl Class Reference
IBTextControl Class Reference
IGraphics::IControls
A control to display text using a monospace bitmap font.
#include <IControls.h>
Public Member Functions
IBTextControl (const IRECT &bounds, const IBitmap &bitmap, const IText &text=DEFAULT_TEXT, const char *str="", int charWidth=6, int charHeight=12, int charOffset=0, bool multiLine=false, bool vCenter=true, EBlend blend=EBlend::Default)
void Draw (IGraphics &g) override
Draw the control to the graphics context.
void OnRescale () override
Implement to do something when graphics is scaled globally (e.g.
Public Member Functions inherited from ITextControl
ITextControl (const IRECT &bounds, const char *str="", const IText &text=DEFAULT_TEXT, const IColor &BGColor=DEFAULT_BGCOLOR, bool setBoundsBasedOnStr=false)
void Draw (IGraphics &g) override
Draw the control to the graphics context.
void OnInit () override
Called just prior to when the control is attached, after its delegate and graphics member variable set.
virtual void SetStr (const char *str)
virtual void SetStrFmt (int maxlen, const char *fmt,...)
virtual void ClearStr ()
const char * GetStr () const
void SetBoundsBasedOnStr ()
Public Member Functions inherited from IControl
IControl (const IRECT &bounds, int paramIdx=kNoParameter, IActionFunction actionFunc=nullptr)
Constructor.
IControl (const IRECT &bounds, const std::initializer_list< int > &params, IActionFunction actionFunc=nullptr)
Constructor (range of parameters)
IControl (const IRECT &bounds, IActionFunction actionFunc)
Constructor (no paramIdx)
IControl (const IControl &)=delete
void operator= (const IControl &)=delete
virtual ~IControl ()
Destructor.
virtual void OnMouseDown (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse down event on this control.
virtual void OnMouseUp (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse up event on this control.
virtual void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod)
Implement this method to respond to a mouse drag event on this control.
virtual void OnMouseDblClick (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse double click event on this control.
virtual void OnMouseWheel (float x, float y, const IMouseMod &mod, float d)
Implement this method to respond to a mouse wheel event on this control.
virtual bool OnKeyDown (float x, float y, const IKeyPress &key)
Implement this method to respond to a key down event on this control.
virtual bool OnKeyUp (float x, float y, const IKeyPress &key)
Implement this method to respond to a key up event on this control.
virtual void OnMouseOver (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouseover event on this control.
virtual void OnMouseOut ()
Implement this method to respond to a mouseout event on this control.
virtual void OnTouchCancelled (float x, float y, const IMouseMod &mod)
Implement this method to respond to a touch cancel event on this control.
virtual void OnDrop (const char *str)
Implement to do something when something was drag 'n dropped onto this control.
virtual void OnResize ()
Called when IControl is constructed or resized using SetRect().
virtual void OnAttached ()
Called after the control has been attached, and its delegate and graphics member variable set.
virtual void OnMsgFromDelegate (int msgTag, int dataSize, const void *pData)
Implement to receive messages sent to the control, see IEditorDelegate:SendControlMsgFromDelegate()
virtual void OnMidi (const IMidiMsg &msg)
Implement to receive MIDI messages sent to the control if mWantsMidi == true, see IEditorDelegate:SendMidiMsgFromDelegate()
virtual bool OnGesture (const IGestureInfo &info)
virtual void CreateContextMenu (IPopupMenu &contextMenu)
Called by default when the user right clicks a control.
virtual void OnPopupMenuSelection (IPopupMenu *pSelectedMenu, int valIdx)
Implement this method to handle popup menu selection after IGraphics::CreatePopupMenu/IControl::PromptUserInput.
virtual void OnTextEntryCompletion (const char *str, int valIdx)
Implement this method to handle text input after IGraphics::CreateTextEntry/IControl::PromptUserInput.
virtual void OnContextSelection (int itemSelected)
Implement this to respond to a menu selection from CreateContextMenu();.
virtual void DrawPTHighlight (IGraphics &g)
Implement this to customise how a colored highlight is drawn on the control in ProTools (AAX format only), when a control is linked to a parameter that is automated.
void PromptUserInput (int valIdx=0)
Call this method in response to a mouse event to create an edit box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter)
void PromptUserInput (const IRECT &bounds, int valIdx=0)
Create a text entry box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter), specifying the bounds.
void SetActionFunction (IActionFunction actionFunc)
Set an Action Function for this control.
void SetAnimationEndActionFunction (IActionFunction actionFunc)
Set an Action Function to be called at the end of an animation.
void SetTooltip (const char *str)
Set a tooltip for the control.
const char * GetTooltip () const
int GetParamIdx (int valIdx=0) const
Get the index of a parameter that the control is linked to Normaly controls are either linked to a single parameter or no parameter but some may be linked to multiple parameters.
void SetParamIdx (int paramIdx, int valIdx=0)
Set the index of a parameter that the control is linked to.
int LinkedToParam (int paramIdx) const
Check if the control is linked to a particular parameter.
int NVals () const
virtual int GetValIdxForPos (float x, float y) const
Check to see which of the control's values relates to this x and y coordinate.
const IParam * GetParam (int valIdx=0) const
Get a const pointer to the IParam object (owned by the editor delegate class), associated with this control.
virtual void SetValueFromDelegate (double value, int valIdx=0)
Set the control's value from the delegate This method is called from the class implementing the IEditorDelegate interface in order to update a control's value members and set it to be marked dirty for redraw.
virtual void SetValueFromUserInput (double value, int valIdx=0)
Set the control's value after user input.
virtual void SetValueToDefault (int valIdx=kNoValIdx)
Set one or all of the control's values to the default value of the associated parameter.
virtual void SetValue (double value, int valIdx=0)
Set one of the control's values.
double GetValue (int valIdx=0) const
Get the control's value.
void SetGroup (const char *groupName)
Assign the control to a control group.
const char * GetGroup () const
Get the group that the control belongs to, if any.
const IText & GetText () const
Get the Text object for the control.
void SetText (const IText &txt)
Set the Text object typically used to determine font/layout/size etc of the main text in a control.
void SetBlend (const IBlend &blend)
Set the Blend for this control.
IBlend GetBlend () const
Get the Blend for this control.
int GetTextEntryLength () const
Get the max number of characters that are allowed in text entry.
void SetTextEntryLength (int len)
Set the max number of characters that are allowed in text entry.
const IRECT & GetRECT () const
Get the rectangular draw area for this control, within the graphics context.
void SetRECT (const IRECT &bounds)
Set the rectangular draw area for this control, within the graphics context.
const IRECT & GetTargetRECT () const
Get the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetRECT (const IRECT &bounds)
Set the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetAndDrawRECTs (const IRECT &bounds)
Set BOTH the draw rect and the target area, within the graphics context for this control.
virtual void SetPosition (float x, float y)
Set the position of the control, preserving the width and height.
virtual void SetSize (float w, float h)
Set the size of the control, preserving the current position.
void SetPTParameterHighlight (bool isHighlighted, int color)
Used internally by the AAX wrapper view interface to set the control parmeter highlight.
bool GetMouseDblAsSingleClick () const
Get double click as single click By default, mouse double click has its own handler.
virtual void Hide (bool hide)
Shows or hides the IControl.
bool IsHidden () const
virtual void SetDisabled (bool disable)
Sets disabled mode for the control, the default implementation modifies the mBlend member.
bool IsDisabled () const
void SetMouseOverWhenDisabled (bool allow)
Specify whether the control should respond to mouse overs when disabled.
void SetMouseEventsWhenDisabled (bool allow)
Specify whether the control should respond to other mouse events when disabled.
bool GetMouseOverWhenDisabled () const
bool GetMouseEventsWhenDisabled () const
bool GetIgnoreMouse () const
virtual bool IsHit (float x, float y) const
Hit test the control.
virtual void SetDirty (bool triggerAction=true, int valIdx=kNoValIdx)
Mark the control as dirty, i.e.
virtual void SetClean ()
void Animate ()
virtual bool IsDirty ()
Called at each display refresh by the IGraphics draw loop, after IControl::Animate(), to determine if the control is marked as dirty.
void DisablePrompt (bool disable)
Disable/enable right-clicking the control to prompt for user input /todo check this.
virtual void OnGUIIdle ()
This is an idle call from the GUI thread, only active if USE_IDLE_CALLS is defined.
void SetTag (int tag)
Set the control's tag.
int GetTag () const
Get the control's tag.
void SetWantsMidi (bool enable=true)
Specify whether this control wants to know about MIDI messages sent to the UI.
bool GetWantsMidi () const
void SetWantsMultiTouch (bool enable=true)
Specify whether this control supports multiple touches.
bool GetWantsMultiTouch () const
IControl * AttachGestureRecognizer (EGestureType type, IGestureFunc func)
Add a IGestureFunc that should be triggered in response to a certain type of gesture.
bool GetWantsGestures () const
EGestureType GetLastGesture () const
IGEditorDelegate * GetDelegate ()
Gets a pointer to the class implementing the IEditorDelegate interface that handles parameter changes from this IGraphics instance.
void SetDelegate (IGEditorDelegate &dlg)
Used internally to set the mDelegate (and mGraphics) variables.
IGraphics * GetUI ()
const IGraphics * GetUI () const
bool GetMouseIsOver () const
virtual void SnapToMouse (float x, float y, EDirection direction, const IRECT &bounds, int valIdx=-1, double minClip=0., double maxClip=1.)
Set control value based on x, y position within a rectangle.
virtual void OnEndAnimation ()
void StartAnimation (int duration)
void SetAnimation (IAnimationFunction func)
Set the animation function.
void SetAnimation (IAnimationFunction func, int duration)
Set the animation function and starts it.
IAnimationFunction GetAnimationFunction ()
/todo
IAnimationFunction GetActionFunction ()
/todo
double GetAnimationProgress () const
/todo
Milliseconds GetAnimationDuration () const
/todo
Public Member Functions inherited from IBitmapBase
IBitmapBase (const IBitmap &bitmap)
void AttachIControl (IControl *pControl)
void DrawBitmap (IGraphics &g)
Protected Attributes
int mCharWidth
int mCharHeight
int mCharOffset
bool mMultiLine
bool mVCentre
Protected Attributes inherited from ITextControl
WDL_String mStr
IColor mBGColor
bool mSetBoundsBasedOnStr = false
Protected Attributes inherited from IControl
int mTag = kNoTag
IRECT mRECT
IRECT mTargetRECT
WDL_String mGroup
Controls can be grouped for hiding and showing panels.
IText mText
IBlend mBlend
int mTextEntryLength = DEFAULT_TEXT_ENTRY_LEN
bool mDirty = true
bool mHide = false
bool mDisabled = false
bool mDisablePrompt = true
bool mDblAsSingleClick = false
bool mMouseOverWhenDisabled = false
bool mMouseEventsWhenDisabled = false
bool mIgnoreMouse = false
bool mWantsMidi = false
bool mWantsMultiTouch = false
bool mMouseIsOver = false
if mGraphics::mHandleMouseOver = true, this will be true when the mouse is over control.
WDL_String mTooltip
IColor mPTHighlightColor = COLOR_RED
bool mPTisHighlighted = false
Protected Attributes inherited from IBitmapBase
IBitmap mBitmap
IControl * mControl = nullptr
Additional Inherited Members
Protected Member Functions inherited from IControl
template<typename T , typename... Args>
void ForValIdx (int valIdx, T func, Args...args)
A helper template function to call a method for an individual value, or for all values.
void SetNVals (int nVals)
Detailed Description
A control to display text using a monospace bitmap font.
Definition at line 599 of file IControls.h.
Member Function Documentation
void IBTextControl::Draw (IGraphics & g) override virtual
Draw the control to the graphics context.
Parameters
g The graphics context to which this control belongs.
Implements IControl.
Definition at line 1496 of file IControls.cpp.
References IGraphics::DrawBitmapedText().
void IBTextControl::OnRescale () inline override virtual
Implement to do something when graphics is scaled globally (e.g.
moves to different DPI screen)
Reimplemented from IControl.
Definition at line 607 of file IControls.h.
References IGraphics::GetScaledBitmap(), and IControl::GetUI().
The documentation for this class was generated from the following files:
IControls.h
IControls.cpp