iPlug2: IGraphics Class Reference
IGraphics Class Reference abstract
The lowest level base class of an IGraphics context.
#include <IGraphics.h>
Public Member Functions
virtual void BeginFrame ()
Called at the beginning of drawing.
virtual void OnViewInitialized (void *pContext)
Called after platform view initialization, so that drawing classes can e.g.
virtual void OnViewDestroyed ()
Called after a platform view is destroyed, so that drawing classes can e.g.
virtual void EndFrame ()
Called by some drawing API classes to finally blit the draw bitmap onto the screen or perform other cleanup after drawing.
virtual void DrawSVG (const ISVG &svg, const IRECT &bounds, const IBlend *pBlend=0)=0
Draw an SVG image to the graphics context.
virtual void DrawRotatedSVG (const ISVG &svg, float destCentreX, float destCentreY, float width, float height, double angle, const IBlend *pBlend=0)=0
Draw an SVG image to the graphics context with rotation.
virtual void DrawBitmap (const IBitmap &bitmap, const IRECT &bounds, int srcX, int srcY, const IBlend *pBlend=0)=0
Draw a bitmap (raster) image to the graphics context.
virtual void DrawFittedBitmap (const IBitmap &bitmap, const IRECT &bounds, const IBlend *pBlend=0)=0
Draw a bitmap (raster) image to the graphics context, scaling the image to fit the bounds.
virtual void DrawRotatedBitmap (const IBitmap &bitmap, float destCentreX, float destCentreY, double angle, int yOffsetZeroDeg=0, const IBlend *pBlend=0)=0
Draw a bitmap (raster) image to the graphics context with rotation.
virtual void DrawPoint (const IColor &color, float x, float y, const IBlend *pBlend=0)=0
Fill a rectangle corresponding to a pixel on a 1:1 screen with a color.
virtual void DrawLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend=0, float thickness=1.f)=0
Draw a line to the graphics context.
virtual void DrawDottedLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend=0, float thickness=1.f, float dashLen=2.f)=0
Draw a dotted line to the graphics context.
virtual void DrawTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend=0, float thickness=1.f)=0
Draw a triangle to the graphics context.
virtual void DrawRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend=0, float thickness=1.f)=0
Draw a rectangle to the graphics context.
virtual void DrawRoundRect (const IColor &color, const IRECT &bounds, float cornerRadius=5.f, const IBlend *pBlend=0, float thickness=1.f)=0
Draw a rounded rectangle to the graphics context.
virtual void DrawRoundRect (const IColor &color, const IRECT &bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend *pBlend=0, float thickness=1.f)=0
Draw a rounded rectangle to the graphics context with individual corner roundness.
virtual void DrawArc (const IColor &color, float cx, float cy, float r, float a1, float a2, const IBlend *pBlend=0, float thickness=1.f)=0
Draw an arc to the graphics context.
virtual void DrawCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend=0, float thickness=1.f)=0
Draw a circle to the graphics context.
virtual void DrawEllipse (const IColor &color, const IRECT &bounds, const IBlend *pBlend=0, float thickness=1.f)=0
Draw an ellipse within a rectangular region of the graphics context.
virtual void DrawEllipse (const IColor &color, float x, float y, float r1, float r2, float angle=0.0, const IBlend *pBlend=0, float thickness=1.f)=0
Draw an ellipse around a central point given two radii and an angle of orientation.
virtual void DrawConvexPolygon (const IColor &color, float *x, float *y, int nPoints, const IBlend *pBlend=0, float thickness=1.f)=0
Draw a convex polygon to the graphics to the graphics context.
virtual void DrawDottedRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend=0, float thickness=1.f, float dashLen=2.f)=0
Draw a dotted rectangle to the graphics context.
virtual void FillTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend=0)=0
Fill a triangle in the graphics context with a color.
virtual void FillRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend=0)=0
Fill a rectangular region of the graphics context with a color.
virtual void FillRoundRect (const IColor &color, const IRECT &bounds, float cornerRadius=5.f, const IBlend *pBlend=0)=0
Fill a rounded rectangle in the graphics context with a color.
virtual void FillRoundRect (const IColor &color, const IRECT &bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend *pBlend=0)=0
Fill a rounded rectangle in the graphics context with a color.
virtual void FillCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend=0)=0
Fill a circle in the graphics context with a color.
virtual void FillEllipse (const IColor &color, const IRECT &bounds, const IBlend *pBlend=0)=0
Fill an ellipse within a rectangular region of the graphics context.
virtual void FillEllipse (const IColor &color, float x, float y, float r1, float r2, float angle=0.0, const IBlend *pBlend=0)=0
Fill an ellipse in the graphics context.
virtual void FillArc (const IColor &color, float cx, float cy, float r, float a1, float a2, const IBlend *pBlend=0)=0
Fill an arc segment in the graphics context with a color.
virtual void FillConvexPolygon (const IColor &color, float *x, float *y, int nPoints, const IBlend *pBlend=0)=0
Fill a convex polygon in the graphics context with a color.
void DrawText (const IText &text, const char *str, const IRECT &bounds, const IBlend *pBlend=0)
Draw some text to the graphics context in a specific rectangle.
void DrawText (const IText &text, const char *str, float x, float y, const IBlend *pBlend=0)
Draw some text to the graphics context at a point.
virtual void MeasureText (const IText &text, const char *str, IRECT &bounds) const
Measure the rectangular region that some text will occupy.
virtual IColor GetPoint (int x, int y)=0
Get the color of a point in the graphics context.
virtual void * GetDrawContext ()=0
Gets a void pointer to IGraphics Draw Class context data (e.g raw framebuffer).
virtual const char * GetDrawingAPIStr ()=0
virtual IBitmap ScaleBitmap (const IBitmap &inBitmap, const char *cacheName, int targetScale)
Returns a new IBitmap, an integer scaled version of the input, and adds it to the cache.
virtual void RetainBitmap (const IBitmap &bitmap, const char *cacheName)
Adds an IBitmap to the cache/static storage.
virtual void ReleaseBitmap (const IBitmap &bitmap)
Releases an IBitmap from the cache/static storage.
IBitmap GetScaledBitmap (IBitmap &inBitmap)
Get a version of the input bitmap from the cache that corresponds to the current screen scale For example, when IControl::OnRescale() is called bitmap-based IControls can load in.
virtual bool BitmapExtSupported (const char *ext)=0
Checks a file extension and reports whether this drawing API supports loading that extension.
void DrawBitmap (const IBitmap &bitmap, const IRECT &bounds, int frame=1, const IBlend *pBlend=0)
Draws a bitmap into the graphics context.
void DrawBitmapedText (const IBitmap &bitmap, IRECT &bounds, IText &text, IBlend *pBlend, const char *str, bool vCenter=true, bool multiline=false, int charWidth=6, int charHeight=12, int charOffset=0)
Draws mono spaced bitmap text.
void DrawVerticalLine (const IColor &color, const IRECT &bounds, float x, const IBlend *pBlend=0, float thickness=1.f)
Draw a vertical line, within a rectangular region of the graphics context.
void DrawHorizontalLine (const IColor &color, const IRECT &bounds, float y, const IBlend *pBlend=0, float thickness=1.f)
Draw a horizontal line, within a rectangular region of the graphics context.
void DrawVerticalLine (const IColor &color, float xi, float yLo, float yHi, const IBlend *pBlend=0, float thickness=1.f)
void DrawHorizontalLine (const IColor &color, float yi, float xLo, float xHi, const IBlend *pBlend=0, float thickness=1.f)
void DrawRadialLine (const IColor &color, float cx, float cy, float angle, float rMin, float rMax, const IBlend *pBlend=0, float thickness=1.f)
Draw a radial line to the graphics context, useful for pointers on dials.
virtual void DrawGrid (const IColor &color, const IRECT &bounds, float gridSizeH, float gridSizeV, const IBlend *pBlend=0, float thickness=1.f)
Draw a grid to the graphics context.
virtual void DrawData (const IColor &color, const IRECT &bounds, float *normYPoints, int nPoints, float *normXPoints=nullptr, const IBlend *pBlend=0, float thickness=1.f)
/todo
virtual bool LoadFont (const char *fontID, const char *fileNameOrResID)
Load a font to be used by the graphics context.
bool LoadFont (const char *fontID, const char *fontName, ETextStyle style)
void StartLayer (IControl *owner, const IRECT &r)
/todo
void ResumeLayer (ILayerPtr &layer)
/todo
ILayerPtr EndLayer ()
/todo
bool CheckLayer (const ILayerPtr &layer)
/todo
void DrawLayer (const ILayerPtr &layer, const IBlend *pBlend=nullptr)
/todo
void DrawFittedLayer (const ILayerPtr &layer, const IRECT &bounds, const IBlend *pBlend)
/todo
void DrawRotatedLayer (const ILayerPtr &layer, double angle)
/todo
void ApplyLayerDropShadow (ILayerPtr &layer, const IShadow &shadow)
Applies a dropshadow directly onto a layer.
virtual void UpdateLayer ()
/todo
virtual void GetLayerBitmapData (const ILayerPtr &layer, RawBitmapData &data)=0
/todo
virtual void ApplyShadowMask (ILayerPtr &layer, RawBitmapData &mask, const IShadow &shadow)=0
/todo
void PushLayer (ILayer *layer)
/todo
ILayer * PopLayer ()
/todo
virtual bool HasPathSupport () const
virtual void PathClear ()
/todo
virtual void PathClose ()
/todo
void PathLine (float x1, float y1, float x2, float y2)
/todo
void PathRadialLine (float cx, float cy, float angle, float rMin, float rMax)
/todo
virtual void PathTriangle (float x1, float y1, float x2, float y2, float x3, float y3)
/todo
virtual void PathRect (const IRECT &bounds)
/todo
virtual void PathRoundRect (const IRECT &bounds, float ctl, float ctr, float cbl, float cbr)
/todo
virtual void PathRoundRect (const IRECT &bounds, float cr=5.f)
/todo
virtual void PathArc (float cx, float cy, float r, float a1, float a2, EWinding winding=EWinding::CW)
/todo
virtual void PathCircle (float cx, float cy, float r)
/todo
virtual void PathEllipse (float x, float y, float r1, float r2, float angle=0.0)
/todo
virtual void PathEllipse (const IRECT &bounds)
/todo
virtual void PathConvexPolygon (float *x, float *y, int nPoints)
/todo
virtual void PathMoveTo (float x, float y)
/todo
virtual void PathLineTo (float x, float y)
/todo
virtual void PathSetWinding (bool clockwise)
/todo
virtual void PathCubicBezierTo (float c1x, float c1y, float c2x, float c2y, float x2, float y2)
/todo
virtual void PathQuadraticBezierTo (float cx, float cy, float x2, float y2)
/todo
virtual void PathStroke (const IPattern &pattern, float thickness, const IStrokeOptions &options=IStrokeOptions(), const IBlend *pBlend=0)
/todo
virtual void PathFill (const IPattern &pattern, const IFillOptions &options=IFillOptions(), const IBlend *pBlend=0)
/todo
virtual void PathTransformSave ()
/todo
virtual void PathTransformRestore ()
/todo
virtual void PathTransformReset (bool clearStates=false)
/todo
virtual void PathTransformTranslate (float x, float y)
/todo
virtual void PathTransformScale (float scaleX, float scaleY)
/todo
virtual void PathTransformScale (float scale)
/todo
virtual void PathTransformRotate (float angle)
/todo
virtual void PathTransformSkew (float xAngle, float yAngle)
/todo
virtual void PathTransformMatrix (const IMatrix &matrix)
/todo
virtual void PathClipRegion (const IRECT r=IRECT())
/todo
virtual void HideMouseCursor (bool hide=true, bool lock=true)=0
Call to hide the mouse cursor.
virtual void MoveMouseCursor (float x, float y)=0
Force move the mouse cursor to a specific position in the graphics context.
virtual ECursor SetMouseCursor (ECursor cursorType=ECursor::ARROW)
Sets the mouse cursor to one of ECursor (implementations should return the result of the base implementation)
virtual void ForceEndUserEdit ()=0
Call to force end text entry (will cancel any half input text.
virtual void * OpenWindow (void *pParentWnd)=0
Open a new platform view for this graphics context.
virtual void CloseWindow ()=0
Close the platform view for this graphics context.
virtual void * GetWindow ()=0
Get a pointer to the platform view e.g.
virtual bool WindowIsOpen ()
virtual bool GetTextFromClipboard (WDL_String &str)=0
Get text from the clipboard.
virtual bool SetTextInClipboard (const char *str)=0
Set text in the clipboard.
virtual void UpdateTooltips ()=0
Call this if you modify control tool tips at runtime.
virtual EMsgBoxResult ShowMessageBox (const char *str, const char *caption, EMsgBoxType type, IMsgBoxCompletionHanderFunc completionHandler=nullptr)=0
Pop up a modal platform message box dialog.
virtual void PromptForFile (WDL_String &fileName, WDL_String &path, EFileAction action=EFileAction::Open, const char *extensions=0)=0
Create a platform file prompt dialog to choose a file/directory path for opening/saving a file/directory.
virtual void PromptForDirectory (WDL_String &dir)=0
Create a platform file prompt dialog to choose a directory path for opening/saving a directory.
virtual bool PromptForColor (IColor &color, const char *str="", IColorPickerHandlerFunc func=nullptr)=0
Create a platform color chooser dialog.
virtual bool OpenURL (const char *url, const char *msgWindowTitle=0, const char *confirmMsg=0, const char *errMsgOnFailure=0)=0
Open a URL in the platforms default browser.
virtual const char * GetPlatformAPIStr ()
virtual bool RevealPathInExplorerOrFinder (WDL_String &path, bool select=false)
virtual void SetWinModuleHandle (void *pHinstance)
Used on Windows to set the HINSTANCE module handle, which allows graphics APIs to load resources from the binary.
virtual void * GetWinModuleHandle ()
virtual void SetPlatformContext (void *pContext)
Set the platform draw context Used in order to set the platform level draw context - CGContextRef context on macOS and the GDI HDC draw context handle on Windows.
void * GetPlatformContext ()
Get the platform level draw context - an HDC or CGContextRef.
virtual void ClientToScreen (float &x, float &y)
Convert an x, y position in the view to screen coordinates.
virtual PlatformFontPtr LoadPlatformFont (const char *fontID, const char *fileNameOrResID)=0
Load a font from disk or resource in a platform format.
virtual PlatformFontPtr LoadPlatformFont (const char *fontID, const char *fontName, ETextStyle style)=0
Load a system font in a platform format.
virtual void CachePlatformFont (const char *fontID, const PlatformFontPtr &font)=0
Called to indicate that the platform should cache data about the platform font if needed.
virtual const char * GetBundleID ()
Get the bundle ID on macOS and iOS, returns emtpy string on other OSs.
IGraphics (IGEditorDelegate &dlg, int w, int h, int fps=0, float scale=1.)
IGraphics (const IGraphics &)=delete
IGraphics & operator= (const IGraphics &)=delete
void SetScreenScale (int scale)
Called by the platform IGraphics class when moving to a new screen to set DPI.
void SetTranslation (float x, float y)
Called by some platform IGraphics classes in order to translate the graphics context, in response to e.g.
bool IsDirty (IRECTList &rects)
Called repeatedly at frame rate by the platform class to check what the graphics context says is dirty.
void Draw (IRECTList &rects)
Called by the platform class indicating a number of rectangles in the UI that need to redraw.
void PromptUserInput (IControl &control, const IRECT &bounds, int valIdx=0)
Prompt for user input either using a text entry or pop up menu.
void CreatePopupMenu (IControl &control, IPopupMenu &menu, const IRECT &bounds, int valIdx=0)
Shows a pop up/contextual menu in relation to a rectangular region of the graphics context.
void CreatePopupMenu (IControl &control, IPopupMenu &menu, float x, float y, int valIdx=0)
Shows a pop up/contextual menu at point in the graphics context.
void CreateTextEntry (IControl &control, const IText &text, const IRECT &bounds, const char *str="", int valIdx=0)
Create a text entry box.
void SetControlValueAfterTextEdit (const char *str)
Called by the platform class after returning from a text entry in order to update a control with a new value.
void SetControlValueAfterPopupMenu (IPopupMenu *pMenu)
Called by PopupMenuControl in order to update a control with a new value after returning from the non-blocking menu.
void SetScaleConstraints (float lo, float hi)
/todo
void SetSizeConstraints (int widthLo, int widthHi, int heightLo, int heightHi)
/todo
void Resize (int w, int h, float scale)
void SetStrictDrawing (bool strict)
Enables strict drawing mode.
void SetLayoutOnResize (bool layoutOnResize)
int Width () const
Gets the width of the graphics context.
int Height () const
Gets the height of the graphics context.
int WindowWidth () const
Gets the width of the graphics context including scaling (not display scaling!)
int WindowHeight () const
Gets the height of the graphics context including scaling (not display scaling!)
int FPS () const
Gets the drawing frame rate.
float GetDrawScale () const
Gets the graphics context scaling factor.
int GetScreenScale () const
Gets the display scaling factor.
float GetTotalScale () const
Gets the combined screen and display scaling factor.
IRECT GetPixelSnapped (IRECT &r) const
Gets the nearest backing pixel aligned rect to the input IRECT.
IGEditorDelegate * GetDelegate ()
Gets a pointer to the delegate class that handles communication to and from this graphics context.
IPopupMenu & GetPromptMenu ()
bool IsInPlatformTextEntry ()
IControl * GetControlInTextEntry ()
bool TooltipsEnabled () const
EUIResizerMode GetResizerMode () const
bool GetResizingInProcess () const
bool EnableMultiTouch (bool enable)
Enable/disable multi touch, if platform supports it.
bool MultiTouchEnabled () const
virtual bool PlatformSupportsMultiTouch () const
void EnableTooltips (bool enable)
void AssignParamNameToolTips ()
Call this method in order to create tool tips for every IControl that show the associated parameter's name.
void ShowControlBounds (bool enable)
void ShowAreaDrawn (bool enable)
bool ShowAreaDrawnEnabled () const
bool ShowControlBoundsEnabled () const
void EnableLiveEdit (bool enable, const char *file=0, int gridsize=10)
Live edit mode allows you to relocate controls at runtime in debug builds and save the locations to a predefined file (e.g.
bool LiveEditEnabled () const
IRECT GetBounds () const
Returns an IRECT that represents the entire UI bounds This is useful for programatically arranging UI elements by slicing up the IRECT using the various IRECT methods.
void SetDisplayTickFunc (IDisplayTickFunc func)
Sets a function that is called at the frame rate, prior to checking for dirty controls.
void SetKeyHandlerFunc (IKeyHandlerFunc func)
/todo
void SetQwertyMidiKeyHandlerFunc (std::function< void(const IMidiMsg &msg)> func=nullptr)
A helper to set the IGraphics KeyHandlerFunc in order to make an instrument playable via QWERTY keys.
void AttachImGui (std::function< void(IGraphics *)> drawFunc, std::function< void()> setupFunc=nullptr)
/todo
bool RespondsToGesture (float x, float y)
Called by platform class to see if the point at x, y is linked to a gesture recognizer.
void OnGestureRecognized (const IGestureInfo &info)
Called by platform class when a gesture is recognized.
virtual int GetPlatformWindowScale () const
Returns a scaling factor for resizing parent windows via the host/plugin API.
void ForAllControlsFunc (std::function< void(IControl &control)> func)
/todo
template<typename T , typename... Args>
void ForAllControls (T method, Args...args)
/todo
void ForStandardControlsFunc (std::function< void(IControl &control)> func)
For all standard controls in the main control stack perform a function.
template<typename T , typename... Args>
void ForMatchingControls (T method, int paramIdx, Args...args)
/todo
void ForControlWithParam (int paramIdx, std::function< void(IControl &control)> func)
/todo
void ForControlInGroup (const char *group, std::function< void(IControl &control)> func)
void AttachBackground (const char *fileName)
Attach an IBitmapControl as the lowest IControl in the control stack to be the background for the graphics context.
void AttachPanelBackground (const IPattern &color)
Attach an IPanelControl as the lowest IControl in the control stack to fill the background with a solid color.
void AttachCornerResizer (EUIResizerMode sizeMode=EUIResizerMode::Scale, bool layoutOnResize=false)
Attach the default control to scale or increase the UI size by dragging the plug-in bottom right-hand corner.
void AttachCornerResizer (ICornerResizerControl *pControl, EUIResizerMode sizeMode=EUIResizerMode::Scale, bool layoutOnResize=false)
Attach your own control to scale or increase the UI size by dragging the plug-in bottom right-hand corner.
void AttachPopupMenuControl (const IText &text=DEFAULT_TEXT, const IRECT &bounds=IRECT())
Attach a control for pop-up menus, to override platform style menus.
void AttachBubbleControl (const IText &text=DEFAULT_TEXT)
Attach the default control to show text as a control changes.
void AttachBubbleControl (IBubbleControl *pControl)
Attach a custom control to show text as a control changes.
void ShowBubbleControl (IControl *pCaller, float x, float y, const char *str, EDirection dir=EDirection::Horizontal, IRECT minimumContentBounds=IRECT())
void ShowFPSDisplay (bool enable)
Shows a control to display the frame rate of drawing.
bool ShowingFPSDisplay ()
void AttachTextEntryControl ()
Attach a control for text entry, to override platform text entry.
IControl * AttachControl (IControl *pControl, int ctrlTag=kNoTag, const char *group="")
Attach an IControl to the graphics context and add it to the top of the control stack.
IControl * GetControl (int idx)
IControl * GetControlWithTag (int ctrlTag)
bool ControlIsCaptured () const
Check to see if any control is captured.
bool ControlIsCaptured (IControl *pControl) const
Check to see if the control is already captured.
void GetTouches (IControl *pControl, std::vector< ITouchID > &touchesOnThisControl) const
Populate a vector with the touchIDs active on pControl.
IControl * GetBackgroundControl ()
IPopupMenuControl * GetPopupMenuControl ()
ITextEntryControl * GetTextEntryControl ()
void StyleAllVectorControls (const IVStyle &style)
Helper method to style all of the controls which inherit IVectorBase.
void UpdatePeers (IControl *pCaller, int callerValIdx)
This method is called after interacting with a control, so that any other controls linked to the same parameter index, will also be set dirty, and have their values updated.
int NControls () const
void RemoveControl (IControl *pControl)
Remove control from the control list.
void RemoveControlWithTag (int ctrlTag)
Remove controls from the control list with a particular tag.
void RemoveControls (int fromIdx)
Remove controls from the control list above a particular index, (frees memory).
void RemoveAllControls ()
Removes all regular IControls from the control list, as well as special controls (frees memory).
void HideControl (int paramIdx, bool hide)
Hide controls linked to a specific parameter.
void DisableControl (int paramIdx, bool diable)
Disable or enable controls linked to a specific parameter.
void SetAllControlsDirty ()
Calls SetDirty() on every control.
void SetAllControlsClean ()
Calls SetClean() on every control.
void OnMouseDown (const std::vector< IMouseInfo > &points)
void OnMouseUp (const std::vector< IMouseInfo > &points)
void OnMouseDrag (const std::vector< IMouseInfo > &points)
void OnTouchCancelled (const std::vector< IMouseInfo > &points)
bool OnMouseDblClick (float x, float y, const IMouseMod &mod)
void OnMouseWheel (float x, float y, const IMouseMod &mod, float delta)
bool OnKeyDown (float x, float y, const IKeyPress &key)
bool OnKeyUp (float x, float y, const IKeyPress &key)
bool OnMouseOver (float x, float y, const IMouseMod &mod)
void OnMouseOut ()
void OnSetCursor ()
void OnDrop (const char *str, float x, float y)
void OnGUIIdle ()
void OnDragResize (float x, float y)
Called by ICornerResizerControl as the corner is dragged to resize.
void EnableMouseOver (bool enable)
void ReleaseMouseCapture ()
Used to tell the graphics context to stop tracking mouse interaction with a control.
bool CanEnableMouseOver () const
int GetMouseOver () const
void GetMouseDownPoint (float &x, float &y) const
Get the x, y position in the graphics context of the last mouse down message.
void SetTabletInput (bool tablet)
Set by the platform class if the mouse input is coming from a tablet/stylus.
int GetParamIdxForPTAutomation (float x, float y)
[AAX only] This can be called by the ProTools API class (e.g.
int GetLastClickedParamForPTAutomation ()
[AAX only]
void SetPTParameterHighlight (int paramIdx, bool isHighlighted, int color)
[AAX only]
void PopupHostContextMenuForParam (int controlIdx, int paramIdx, float x, float y)
[VST3 primarily] In VST3 plug-ins this enable support for the IContextMenu interface, which allows the host to add contextual options to e.g.
void PopupHostContextMenuForParam (IControl *pControl, int paramIdx, float x, float y)
/todo
const char * GetSharedResourcesSubPath () const
Gets the name of the shared resources subpath.
void SetSharedResourcesSubPath (const char *sharedResourcesSubPath)
Sets the name of the shared resources subpath.
virtual IBitmap LoadBitmap (const char *fileNameOrResID, int nStates=1, bool framesAreHorizontal=false, int targetScale=0)
Load a bitmap image from disk or from windows resource.
virtual ISVG LoadSVG (const char *fileNameOrResID, const char *units="px", float dpi=72.f)
Load an SVG from disk or from windows resource.
virtual void AttachGestureRecognizer (EGestureType type)
Registers a gesture recognizer with the graphics context.
void AttachGestureRecognizerToRegion (const IRECT &bounds, EGestureType type, IGestureFunc func)
Attach a gesture recognizer to a rectangular region of the GUI, i.e.
void ClearGestureRegions ()
Remove all gesture recognizers linked to regions.
Protected Member Functions
virtual void ActivateGLContext ()
virtual void DeactivateGLContext ()
virtual void CreatePlatformTextEntry (int paramIdx, const IText &text, const IRECT &bounds, int length, const char *str)=0
/todo
virtual IPopupMenu * CreatePlatformPopupMenu (IPopupMenu &menu, const IRECT &bounds, bool &isAsync)=0
Calls the platform backend to create the platform popup menu.
virtual APIBitmap * LoadAPIBitmap (const char *fileNameOrResID, int scale, EResourceLocation location, const char *ext)=0
/todo
virtual APIBitmap * CreateAPIBitmap (int width, int height, int scale, double drawScale)=0
Creates a new API bitmap, either in memory or as a GPU texture.
virtual bool LoadAPIFont (const char *fontID, const PlatformFontPtr &font)=0
/todo
virtual bool AssetsLoaded ()
Specialized in IGraphicsCanvas drawing backend.
virtual int AlphaChannel () const =0
virtual bool FlippedBitmap () const =0
void SearchNextScale (int &sourceScale, int targetScale)
Utility used by SearchImageResource/SearchBitmapInCache.
EResourceLocation SearchImageResource (const char *fileName, const char *type, WDL_String &result, int targetScale, int &sourceScale)
Search for a bitmap image resource matching the target scale.
APIBitmap * SearchBitmapInCache (const char *fileName, int targetScale, int &sourceScale)
Search the static storage cache for a bitmap image resource matching the target scale.
virtual void DoMeasureText (const IText &text, const char *str, IRECT &bounds) const =0
/todo
virtual void DoDrawText (const IText &text, const char *str, const IRECT &bounds, const IBlend *pBlend=nullptr)=0
/todo
void DoMeasureTextRotation (const IText &text, const IRECT &bounds, IRECT &rect) const
/todo
void CalculateTextRotation (const IText &text, const IRECT &bounds, IRECT &rect, double &tx, double &ty) const
/todo text
virtual float GetBackingPixelScale () const =0
Protected Attributes
IGEditorDelegate * mDelegate
void * mPlatformContext = nullptr
bool mCursorHidden = false
bool mCursorLock = false
bool mTabletInput = false
float mCursorX = -1.f
float mCursorY = -1.f
float mXTranslation = 0.f
float mYTranslation = 0.f
std::stack< ILayer * > mLayers
Friends
class IGraphicsLiveEdit
class ICornerResizerControl
class ITextEntryControl
Detailed Description
The lowest level base class of an IGraphics context.
Definition at line 80 of file IGraphics.h.
Member Function Documentation
virtual int IGraphics::AlphaChannel () const protected pure virtual
Returns
int The index of the alpha component in a drawing backend's pixel (RGBA or ARGB)
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsSkia, IGraphicsLice, IGraphicsCairo, and IGraphicsCanvas.
Referenced by AssetsLoaded().
void IGraphics::ApplyLayerDropShadow (ILayerPtr & layer, const IShadow & shadow)
Applies a dropshadow directly onto a layer.
Parameters
layer - the layer to add the shadow to
shadow - the shadow to add
Definition at line 1871 of file IGraphics.cpp.
Referenced by GFXLabelControl::Draw(), TestShadowGradientControl::Draw(), TestDropShadowControl::Draw(), IPopupMenuControl::DrawPanelShadow(), and EndFrame().
virtual void IGraphics::ApplyShadowMask (ILayerPtr & layer, RawBitmapData & mask, const IShadow & shadow) pure virtual
/todo
Parameters
layer /todo
mask /todo
shadow /todo
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsSkia, IGraphicsLice, IGraphicsCairo, and IGraphicsCanvas.
Referenced by UpdateLayer().
void IGraphics::AttachBackground (const char * fileName)
Attach an IBitmapControl as the lowest IControl in the control stack to be the background for the graphics context.
Parameters
fileName CString fileName resource id for the bitmap image
Todo:
check this
Definition at line 203 of file IGraphics.cpp.
References IControl::GetDelegate(), and IControl::SetDelegate().
Referenced by GetPlatformWindowScale().
IControl * IGraphics::AttachControl (IControl * pControl, int ctrlTag = kNoTag, const char * group = "")
Attach an IControl to the graphics context and add it to the top of the control stack.
The control is owned by the graphics context and will be deleted when the context is deleted.
Parameters
pControl A pointer to an IControl to attach.
ctrlTag An integer tag that you can use to identify the control
group A CString that you can use to address controlled by group
Returns
The index of the control (and the number of controls in the stack)
Definition at line 218 of file IGraphics.cpp.
References IControl::GetDelegate(), IControl::OnAttached(), IControl::SetDelegate(), IControl::SetGroup(), and IControl::SetTag().
Referenced by IVPresetManagerControl::OnAttached(), IVNumberBoxControl::OnAttached(), IGraphicsLiveEdit::OnMouseDown(), IGraphicsLiveEdit::OnPopupMenuSelection(), and ShowingFPSDisplay().
void IGraphics::AttachCornerResizer (EUIResizerMode sizeMode = EUIResizerMode::Scale, bool layoutOnResize = false)
Attach the default control to scale or increase the UI size by dragging the plug-in bottom right-hand corner.
Parameters
sizeMode Choose whether to scale or size the UI
Definition at line 228 of file IGraphics.cpp.
Referenced by GetPlatformWindowScale().
void IGraphics::AttachCornerResizer (ICornerResizerControl * pControl, EUIResizerMode sizeMode = EUIResizerMode::Scale, bool layoutOnResize = false)
Attach your own control to scale or increase the UI size by dragging the plug-in bottom right-hand corner.
Parameters
pControl control a control that inherits from ICornerResizerControl
sizeMode Choose whether to scale or size the UI
Definition at line 233 of file IGraphics.cpp.
References IControl::GetDelegate().
void IGraphics::AttachGestureRecognizer (EGestureType type) virtual
Registers a gesture recognizer with the graphics context.
Parameters
type The type of gesture recognizer
Definition at line 2137 of file IGraphics.cpp.
Referenced by IControl::AttachGestureRecognizer(), and SetSharedResourcesSubPath().
void IGraphics::AttachGestureRecognizerToRegion (const IRECT & bounds, EGestureType type, IGestureFunc func)
Attach a gesture recognizer to a rectangular region of the GUI, i.e.
not linked to an IControl
Parameters
bounds The area that should recognize the gesture
type The type of gesture to recognize
func The function to call when the gesture is recognized
Definition at line 2145 of file IGraphics.cpp.
References IControl::AttachGestureRecognizer().
Referenced by SetSharedResourcesSubPath().
void IGraphics::AttachPanelBackground (const IPattern & color)
Attach an IPanelControl as the lowest IControl in the control stack to fill the background with a solid color.
Parameters
color The color to fill the panel with
Definition at line 211 of file IGraphics.cpp.
References IControl::GetDelegate(), and IControl::SetDelegate().
Referenced by GetPlatformWindowScale().
void IGraphics::AttachPopupMenuControl (const IText & text = DEFAULT_TEXT, const IRECT & bounds = IRECT())
Attach a control for pop-up menus, to override platform style menus.
Parameters
text The text style to use for the menu
bounds The area that the menu should occupy /todo check
Definition at line 260 of file IGraphics.cpp.
References IControl::GetDelegate().
Referenced by GetPlatformWindowScale(), and TestDirBrowseControl::OnMouseDown().
void IGraphics::BeginFrame () virtual
Called at the beginning of drawing.
Call base implementation if overridden.
Reimplemented in IGraphicsNanoVG, and IGraphicsSkia.
Definition at line 740 of file IGraphics.cpp.
References IControl::Draw(), Draw(), IControl::DrawPTHighlight(), IRECT::GetPadded(), IRECT::GetPixelAligned(), IControl::GetRECT(), IRECT::H(), IRECT::Intersect(), IControl::IsHidden(), IColor::Randomise(), and IRECT::W().
Referenced by IGraphicsSkia::BeginFrame(), and IGraphicsNanoVG::BeginFrame().
virtual void IGraphics::CachePlatformFont (const char * fontID, const PlatformFontPtr & font) pure virtual
Called to indicate that the platform should cache data about the platform font if needed.
Parameters
fontID A string that is used to reference the font
font A const PlatformFontPtr reference to the relevant font
Referenced by ClientToScreen().
void IGraphics::CalculateTextRotation (const IText & text, const IRECT & bounds, IRECT & rect, double & tx, double & ty) const protected
/todo text
Parameters
text /todo
bounds /todo
rect /todo
tx /todo
ty /todo
Definition at line 1994 of file IGraphics.cpp.
References IRECT::MH(), IRECT::MW(), IMatrix::Rotate(), IMatrix::TransformPoint(), and IRECT::Union().
Referenced by AssetsLoaded(), and IGraphicsPathBase::DrawRotatedSVG().
bool IGraphics::CanEnableMouseOver () const inline
Returns
true if the context can handle mouse overs
Definition at line 1404 of file IGraphics.h.
bool IGraphics::CheckLayer (const ILayerPtr & layer)
/todo
Parameters
layer /todo
Returns
/todo
Definition at line 1828 of file IGraphics.cpp.
References APIBitmap::GetDrawScale(), and APIBitmap::GetScale().
Referenced by GFXLabelControl::Draw(), TestLayerControl::Draw(), TestMTControl::Draw(), TestSVGControl::Draw(), TestDropShadowControl::Draw(), TestKeyboardControl::Draw(), IVPlotControl::Draw(), ISVGControl::Draw(), IPopupMenuControl::DrawPanelShadow(), and EndFrame().
virtual void IGraphics::ClientToScreen (float & x, float & y) inline virtual
Convert an x, y position in the view to screen coordinates.
Parameters
x the x position to convert
y the y position to convert
Definition at line 844 of file IGraphics.h.
References CachePlatformFont(), and LoadPlatformFont().
bool IGraphics::ControlIsCaptured (IControl * pControl) const inline
Check to see if the control is already captured.
Returns
true is the control is already captured
Definition at line 1257 of file IGraphics.h.
virtual APIBitmap* IGraphics::CreateAPIBitmap (int width, int height, int scale, double drawScale) protected pure virtual
Creates a new API bitmap, either in memory or as a GPU texture.
Parameters
width The desired width
height The desired height
scale The scale in relation to 1:1 pixels
drawScale /todo
Returns
APIBitmap* The new API Bitmap
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsSkia, IGraphicsLice, IGraphicsCairo, and IGraphicsCanvas.
Referenced by SetSharedResourcesSubPath().
virtual IPopupMenu* IGraphics::CreatePlatformPopupMenu (IPopupMenu & menu, const IRECT & bounds, bool & isAsync) protected pure virtual
Calls the platform backend to create the platform popup menu.
Parameters
menu The source IPopupMenu
bounds /todo
isAsync This gets set true on platforms where popupmenu creation is asyncronous
Returns
A ptr to the chosen IPopupMenu or nullptr in the case of async or dismissed menu
Referenced by GetBundleID().
virtual void IGraphics::CreatePlatformTextEntry (int paramIdx, const IText & text, const IRECT & bounds, int length, const char * str) protected pure virtual
/todo
Parameters
control /todo
text /todo
bounds /todo
str /todo
Referenced by GetBundleID().
void IGraphics::CreatePopupMenu (IControl & control, IPopupMenu & menu, const IRECT & bounds, int valIdx = 0)
Shows a pop up/contextual menu in relation to a rectangular region of the graphics context.
Parameters
control A reference to the IControl creating this pop-up menu. If it exists IControl::OnPopupMenuSelection() will be called on successful selection
menu Reference to an IPopupMenu class populated with the items for the platform menu
bounds The platform menu will popup at the bottom left hand corner of this rectangular region
valIdx The value index for the control value that the menu relates to
Definition at line 1756 of file IGraphics.cpp.
References IControl::OnRescale().
Referenced by CreatePopupMenu(), IGraphicsLiveEdit::OnMouseDown(), TestDirBrowseControl::OnMouseDown(), and SetTranslation().
void IGraphics::CreatePopupMenu (IControl & control, IPopupMenu & menu, float x, float y, int valIdx = 0) inline
Shows a pop up/contextual menu at point in the graphics context.
Parameters
control A reference to the IControl creating this pop-up menu. If it exists IControl::OnPopupMenuSelection() will be called on successful selection
x The X coordinate in the graphics context at which to pop up the menu
y The Y coordinate in the graphics context at which to pop up the menu
valIdx The value index for the control value that the menu relates to
Definition at line 931 of file IGraphics.h.
References CreatePopupMenu(), CreateTextEntry(), SetControlValueAfterPopupMenu(), and SetControlValueAfterTextEdit().
void IGraphics::CreateTextEntry (IControl & control, const IText & text, const IRECT & bounds, const char * str = "", int valIdx = 0)
Create a text entry box.
Parameters
control The control that the text entry belongs to. If this control is linked to a parameter, the text entry will be configured with initial text matching the parameter value
text An IText struct to set the formatting of the text entry box
bounds The rectangular region in the graphics context that the text entry will occupy.
str A CString to specify the default text to display when the text entry box is opened (unless the control specified by the first argument is linked to a parameter)
valIdx The value index for the control value that the text entry relates to
Definition at line 1721 of file IGraphics.cpp.
References IControl::GetParamIdx(), and IControl::GetTextEntryLength().
Referenced by CreatePopupMenu(), TestTextControl::OnMouseDblClick(), IVNumberBoxControl::OnMouseDblClick(), and PlaceHolder::OnMouseDblClick().
void IGraphics::DisableControl (int paramIdx, bool diable)
Disable or enable controls linked to a specific parameter.
Parameters
paramIdx The parameter index
disable /true to disable
Definition at line 360 of file IGraphics.cpp.
References IControl::SetDisabled().
Referenced by NControls().
virtual void IGraphics::DoDrawText (const IText & text, const char * str, const IRECT & bounds, const IBlend * pBlend = nullptr) protected pure virtual
/todo
Parameters
text /todo
str /todo
bounds /todo
pBlend /todo
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsSkia, IGraphicsLice, IGraphicsCairo, and IGraphicsCanvas.
Referenced by AssetsLoaded().
virtual void IGraphics::DoMeasureText (const IText & text, const char * str, IRECT & bounds) const protected pure virtual
/todo
Parameters
text /todo
str /todo
bounds /todo
pBlend /todo
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsSkia, IGraphicsLice, IGraphicsCairo, and IGraphicsCanvas.
Referenced by AssetsLoaded().
void IGraphics::DoMeasureTextRotation (const IText & text, const IRECT & bounds, IRECT & rect) const protected
/todo
Parameters
text /todo
bounds /todo
rect /todo
Definition at line 1986 of file IGraphics.cpp.
References IRECT::Translate().
Referenced by AssetsLoaded().
void IGraphics::Draw (IRECTList & rects)
Called by the platform class indicating a number of rectangles in the UI that need to redraw.
Parameters
rects A set of rectangular regions to draw
Definition at line 796 of file IGraphics.cpp.
References IRECTList::Bounds(), IFPSDisplayControl::Draw(), IRECTList::Get(), IRECTList::Optimize(), IRECT::PixelAlign(), IRECTList::PixelAlign(), and IRECTList::Size().
Referenced by BeginFrame(), GetPlatformWindowScale(), and SetTranslation().
virtual void IGraphics::DrawArc (const IColor & color, float cx, float cy, float r, float a1, float a2, const IBlend * pBlend = 0, float thickness = 1.f) pure virtual
Draw an arc to the graphics context.
Parameters
color The color to draw the shape with
cx The X coordinate in the graphics context of the centre of the circle on which the arc lies
cy The Y coordinate in the graphics context of the centre of the circle on which the arc lies
r The radius of the circle on which the arc lies
a1 the start angle of the arc at in degrees clockwise where 0 is up
a2 the end angle of the arc at in degrees clockwise where 0 is up
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestArcControl::Draw(), EndFrame(), and IVKnobControl::GetKnobDragBounds().
virtual void IGraphics::DrawBitmap (const IBitmap & bitmap, const IRECT & bounds, int srcX, int srcY, const IBlend * pBlend = 0) pure virtual
Draw a bitmap (raster) image to the graphics context.
Parameters
bitmap The bitmap image to draw to the graphics context
bounds The rectangular region to draw the image in
srcX The X coordinate in the source image to draw from
Todo:
Parameters
srcY The Y coordinate in the source image to draw from
Todo:
Parameters
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsCairo, IGraphicsLice, IGraphicsSkia, and IGraphicsCanvas.
Referenced by IBSliderControl::Draw(), IGraphicsPathBase::DrawFittedBitmap(), IGraphicsPathBase::DrawRotatedBitmap(), and EndFrame().
void IGraphics::DrawBitmap (const IBitmap & bitmap, const IRECT & bounds, int frame = 1, const IBlend * pBlend = 0)
Draws a bitmap into the graphics context.
NOTE: this helper method handles multi-frame bitmaps, indexable via frame
Parameters
bitmap - the bitmap to draw
bounds - where to draw the bitmap
frame - the frame index of the bitmap to draw (when bitmap is multi-frame)
pBlend - blend operation
Definition at line 545 of file IGraphics.cpp.
References Clip(), IBitmap::GetFramesAreHorizontal(), IBitmap::H(), IBitmap::N(), and IBitmap::W().
void IGraphics::DrawBitmapedText (const IBitmap & bitmap, IRECT & bounds, IText & text, IBlend * pBlend, const char * str, bool vCenter = true, bool multiline = false, int charWidth = 6, int charHeight = 12, int charOffset = 0)
Draws mono spaced bitmap text.
Useful for identical looking text on multiple platforms.
Parameters
bitmap the bitmap containing glyphs to draw
bounds where to draw the bitmap
text text properties (note - many of these are irrelevant for bitmapped text)
pBlend blend operation
str the string to draw
vCenter centre the text vertically
multiline should the text spill onto multiple lines
charWidth how wide is a character in the bitmap
charHeight how high is a character in the bitmap
charOffset what is the offset between characters drawn
Definition at line 567 of file IGraphics.cpp.
References IRECT::H(), and IRECT::W().
Referenced by IBTextControl::Draw(), and EndFrame().
virtual void IGraphics::DrawCircle (const IColor & color, float cx, float cy, float r, const IBlend * pBlend = 0, float thickness = 1.f) pure virtual
Draw a circle to the graphics context.
Parameters
color The color to draw the shape with
cx The X coordinate in the graphics context of the centre of the circle
cy The Y coordinate in the graphics context of the centre of the circle
r The radius of the circle
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestArcControl::Draw(), and EndFrame().
virtual void IGraphics::DrawConvexPolygon (const IColor & color, float * x, float * y, int nPoints, const IBlend * pBlend = 0, float thickness = 1.f) pure virtual
Draw a convex polygon to the graphics to the graphics context.
Parameters
color The color to draw the shape with
x Pointer to the first element in an array of X coordinates for the vertices of the polygon
y Pointer to the first element in an array of Y coordinates for the vertices of the polygon
nPoints The number of points in the coordinate arrays
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestPolyControl::Draw(), and EndFrame().
void IGraphics::DrawData (const IColor & color, const IRECT & bounds, float * normYPoints, int nPoints, float * normXPoints = nullptr, const IBlend * pBlend = 0, float thickness = 1.f) virtual
/todo
Parameters
color /todo
bounds /todo
normYPoints /todo
nPoints /todo
normXPoints /todo
pBlend /todo
thickness /todo
Reimplemented in IGraphicsPathBase.
Definition at line 690 of file IGraphics.cpp.
Referenced by IVPlotControl::Draw(), and EndFrame().
virtual void IGraphics::DrawDottedLine (const IColor & color, float x1, float y1, float x2, float y2, const IBlend * pBlend = 0, float thickness = 1.f, float dashLen = 2.f) pure virtual
Draw a dotted line to the graphics context.
Parameters
color The color to draw the shape with
x1 The X coordinate in the graphics context of the start of the line
y1 The Y coordinate in the graphics context of the start of the line
x2 The X coordinate in the graphics context of the end of the line
y2 The Y coordinate in the graphics context of the end of the line
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsPathBase, IGraphicsNanoVG, and IGraphicsLice.
Referenced by EndFrame().
virtual void IGraphics::DrawDottedRect (const IColor & color, const IRECT & bounds, const IBlend * pBlend = 0, float thickness = 1.f, float dashLen = 2.f) pure virtual
Draw a dotted rectangle to the graphics context.
Parameters
color The color to draw the shape with
bounds The rectangular region to draw the shape in
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsPathBase, IGraphicsNanoVG, and IGraphicsLice.
Referenced by TestCursorControl::Draw(), TestDrawContextControl::Draw(), TestLayerControl::Draw(), TestGradientControl::Draw(), TestImageControl::Draw(), TestMultiPathControl::Draw(), TestDropShadowControl::Draw(), TestSVGControl::Draw(), TestGesturesControl::Draw(), TestColorControl::Draw(), TestDirBrowseControl::Draw(), TestAnimationControl::Draw(), IGraphicsLiveEdit::Draw(), and EndFrame().
virtual void IGraphics::DrawEllipse (const IColor & color, const IRECT & bounds, const IBlend * pBlend = 0, float thickness = 1.f) pure virtual
Draw an ellipse within a rectangular region of the graphics context.
Parameters
color The color to draw the shape with
bounds The rectangular region to draw the shape in
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestMTControl::Draw(), ILEDControl< MAXNC, QUEUE_SIZE >::Draw(), and EndFrame().
virtual void IGraphics::DrawEllipse (const IColor & color, float x, float y, float r1, float r2, float angle = 0.0, const IBlend * pBlend = 0, float thickness = 1.f) pure virtual
Draw an ellipse around a central point given two radii and an angle of orientation.
Parameters
color The color to draw the shape with
x The X coordinate in the graphics context of the centre of the ellipse
y The Y coordinate in the graphics context of the centre of the ellipse
r1 The radius of the ellipse along the line found by rotating the x-axis by the angle
r2 The radius of the ellipse along the line found by rotating the y-axis by the angle
angle The angle rotates the radii r1 and r2 clockwise in degrees to adjust the orientation
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsPathBase, and IGraphicsLice.
virtual void IGraphics::DrawFittedBitmap (const IBitmap & bitmap, const IRECT & bounds, const IBlend * pBlend = 0) pure virtual
Draw a bitmap (raster) image to the graphics context, scaling the image to fit the bounds.
Parameters
bitmap The bitmap image to draw to the graphics context
bounds The rectangular region to draw the image in
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestMaskControl::Draw(), TestImageControl::Draw(), TestBlendControl::Draw(), and EndFrame().
void IGraphics::DrawFittedLayer (const ILayerPtr & layer, const IRECT & bounds, const IBlend * pBlend)
/todo
Parameters
layer /todo
bounds /todo
pBlend /todo
Definition at line 1849 of file IGraphics.cpp.
References IRECT::H(), and IRECT::W().
Referenced by EndFrame().
void IGraphics::DrawGrid (const IColor & color, const IRECT & bounds, float gridSizeH, float gridSizeV, const IBlend * pBlend = 0, float thickness = 1.f) virtual
Draw a grid to the graphics context.
Parameters
color The color to draw the grid lines with
bounds The rectangular region to fill the grid in
gridSizeH The width of the grid cells
gridSizeV The height of the grid cells
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Reimplemented in IGraphicsPathBase.
Definition at line 670 of file IGraphics.cpp.
References IRECT::H(), and IRECT::W().
Referenced by IGraphicsLiveEdit::Draw(), IVPlotControl::Draw(), and EndFrame().
void IGraphics::DrawHorizontalLine (const IColor & color, const IRECT & bounds, float y, const IBlend * pBlend = 0, float thickness = 1.f)
Draw a horizontal line, within a rectangular region of the graphics context.
Parameters
color The color to draw the line with
bounds The rectangular region to draw the line in
y
Definition at line 639 of file IGraphics.cpp.
References Clip().
Referenced by IVScopeControl< MAXNC, MAXBUF >::Draw(), IVXYPadControl::Draw(), and EndFrame().
void IGraphics::DrawHorizontalLine (const IColor & color, float yi, float xLo, float xHi, const IBlend * pBlend = 0, float thickness = 1.f)
Todo:
Parameters
color The color to draw the line with
yi
Definition at line 651 of file IGraphics.cpp.
void IGraphics::DrawLayer (const ILayerPtr & layer, const IBlend * pBlend = nullptr)
/todo
Parameters
layer /todo
pBlend /todo
Definition at line 1841 of file IGraphics.cpp.
Referenced by TestMaskControl::Draw(), GFXLabelControl::Draw(), TestLayerControl::Draw(), TestShadowGradientControl::Draw(), TestSVGControl::Draw(), TestMTControl::Draw(), TestDropShadowControl::Draw(), TestBlendControl::Draw(), TestKeyboardControl::Draw(), IVPlotControl::Draw(), ISVGControl::Draw(), IPopupMenuControl::DrawPanelShadow(), and EndFrame().
virtual void IGraphics::DrawLine (const IColor & color, float x1, float y1, float x2, float y2, const IBlend * pBlend = 0, float thickness = 1.f) pure virtual
Draw a line to the graphics context.
Parameters
color The color to draw the line with
x1 The X coordinate in the graphics context of the start of the line
y1 The Y coordinate in the graphics context of the start of the line
x2 The X coordinate in the graphics context of the end of the line
y2 The Y coordinate in the graphics context of the end of the line
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsLice, and IGraphicsPathBase.
Referenced by TestSizeControl::Draw(), IVKeyboardControl::Draw(), IURLControl::Draw(), PlaceHolder::Draw(), and EndFrame().
virtual void IGraphics::DrawPoint (const IColor & color, float x, float y, const IBlend * pBlend = 0) pure virtual
Fill a rectangle corresponding to a pixel on a 1:1 screen with a color.
Parameters
color The color to fill the point with
x The X coordinate in the graphics context at which to draw
y The Y coordinate in the graphics context at which to draw
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsLice, and IGraphicsPathBase.
Referenced by EndFrame().
void IGraphics::DrawRadialLine (const IColor & color, float cx, float cy, float angle, float rMin, float rMax, const IBlend * pBlend = 0, float thickness = 1.f)
Draw a radial line to the graphics context, useful for pointers on dials.
Parameters
color The color to draw the line with
cx centre point x coordinate
cy centre point y coordinate
angle The angle to draw at in degrees clockwise where 0 is up
rMin minima of the radial line (distance from cx,cy)
rMax maxima of the radial line (distance from cx,cy)
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Definition at line 656 of file IGraphics.cpp.
Referenced by TestLayerControl::Draw(), TestArcControl::Draw(), EndFrame(), and IVKnobControl::GetKnobDragBounds().
virtual void IGraphics::DrawRect (const IColor & color, const IRECT & bounds, const IBlend * pBlend = 0, float thickness = 1.f) pure virtual
Draw a rectangle to the graphics context.
Parameters
bounds The rectangular area in which to draw the shape
color The color to draw the shape to draw the shape with
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestArcControl::Draw(), TestFlexBoxControl::Draw(), TestMTControl::Draw(), TestBlendControl::Draw(), TestBezierControl::Draw(), IVMeterControl< MAXNC >::Draw(), TestDirBrowseControl::Draw(), IVLabelControl::Draw(), IVScopeControl< MAXNC, MAXBUF >::Draw(), IVDisplayControl::Draw(), IVMultiSliderControl< MAXNC >::Draw(), IFPSDisplayControl::Draw(), IVKeyboardControl::Draw(), IVRangeSliderControl::Draw(), IVXYPadControl::Draw(), IVPlotControl::Draw(), IVColorSwatchControl::Draw(), IPanelControl::Draw(), and EndFrame().
virtual void IGraphics::DrawRotatedBitmap (const IBitmap & bitmap, float destCentreX, float destCentreY, double angle, int yOffsetZeroDeg = 0, const IBlend * pBlend = 0) pure virtual
Draw a bitmap (raster) image to the graphics context with rotation.
Parameters
bitmap The bitmap image to draw to the graphics context
destCentreX The X coordinate in the graphics context of the centre point at which to rotate the image around.
Todo:
check this
Parameters
destCentreY The Y coordinate in the graphics context of the centre point at which to rotate the image around.
Todo:
check this
Parameters
angle The angle of rotation in degrees
yOffsetZeroDeg
Implemented in IGraphicsLice, and IGraphicsPathBase.
Referenced by IBKnobRotaterControl::Draw(), and EndFrame().
void IGraphics::DrawRotatedLayer (const ILayerPtr & layer, double angle)
/todo
Parameters
layer /todo
angle /todo
Definition at line 1861 of file IGraphics.cpp.
References IRECT::MH(), and IRECT::MW().
Referenced by EndFrame().
virtual void IGraphics::DrawRotatedSVG (const ISVG & svg, float destCentreX, float destCentreY, float width, float height, double angle, const IBlend * pBlend = 0) pure virtual
Draw an SVG image to the graphics context with rotation.
Parameters
svg The SVG image to draw to the graphics context
destCentreX The X coordinate in the graphics context of the centre point at which to rotate the image around.
Todo:
check this
Parameters
destCentreY The Y coordinate in the graphics context of the centre point at which to rotate the image around.
Todo:
check this
Parameters
width
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by ISVGKnobControl::Draw(), and EndFrame().
virtual void IGraphics::DrawRoundRect (const IColor & color, const IRECT & bounds, float cornerRadius = 5.f, const IBlend * pBlend = 0, float thickness = 1.f) pure virtual
Draw a rounded rectangle to the graphics context.
Parameters
color The color to draw the shape with
bounds The rectangular region to draw the shape in
cornerRadius The corner radius in pixels
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestPolyControl::Draw(), IVSliderControl::Draw(), IVectorBase::DrawPressableRectangle(), and EndFrame().
virtual void IGraphics::DrawRoundRect (const IColor & color, const IRECT & bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend * pBlend = 0, float thickness = 1.f) pure virtual
Draw a rounded rectangle to the graphics context with individual corner roundness.
Parameters
color The color to draw the shape with
bounds The rectangular region to draw the shape in
cRTL The top left corner radius in pixels
cRTR The top right corner radius in pixels
cRBR The bottom right corner radius in pixels
cRBL The bottom left corner radius in pixels
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsPathBase, and IGraphicsLice.
virtual void IGraphics::DrawSVG (const ISVG & svg, const IRECT & bounds, const IBlend * pBlend = 0) pure virtual
Draw an SVG image to the graphics context.
Parameters
svg The SVG image to the graphics context
bounds The rectangular region to draw the image in
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestDropShadowControl::Draw(), TestSVGControl::Draw(), ISVGButtonControl::Draw(), ISVGSwitchControl::Draw(), ISVGSliderControl::Draw(), ISVGControl::Draw(), and EndFrame().
void IGraphics::DrawText (const IText & text, const char * str, const IRECT & bounds, const IBlend * pBlend = 0)
Draw some text to the graphics context in a specific rectangle.
Parameters
text An IText struct containing font and text properties and layout info
str The text string to draw in the graphics context
bounds The rectangular region in the graphics where you would like to draw the text
Definition at line 523 of file IGraphics.cpp.
Referenced by TestCursorControl::Draw(), TestDrawContextControl::Draw(), GFXLabelControl::Draw(), TestLayerControl::Draw(), TestSizeControl::Draw(), TestTextControl::Draw(), TestGradientControl::Draw(), TestImageControl::Draw(), TestMultiPathControl::Draw(), TestMTControl::Draw(), TestFlexBoxControl::Draw(), TestBlendControl::Draw(), TestGesturesControl::Draw(), TestFontControl::Draw(), TestTextOrientationControl::Draw(), TestTextSizeControl::Draw(), IVLabelControl::Draw(), TestColorControl::Draw(), TestDirBrowseControl::Draw(), ITextEntryControl::Draw(), TestAnimationControl::Draw(), IFPSDisplayControl::Draw(), TestMPSControl::Draw(), TestKeyboardControl::Draw(), IVTabSwitchControl::Draw(), TestGLControl::Draw(), IVKeyboardControl::Draw(), IVColorSwatchControl::Draw(), ITextControl::Draw(), IURLControl::Draw(), PlaceHolder::Draw(), IPopupMenuControl::DrawCellText(), EndFrame(), IVRadioButtonControl::IVRadioButtonControl(), IVSwitchControl::OnInit(), and IBubbleControl::SetMaxBounds().
void IGraphics::DrawText (const IText & text, const char * str, float x, float y, const IBlend * pBlend = 0)
Draw some text to the graphics context at a point.
Parameters
text An IText struct containing font and text properties and layout info
str The text string to draw in the graphics context
x The x position in the graphics where you would like to draw the text
y The y position in the graphics where you would like to draw the text
Definition at line 539 of file IGraphics.cpp.
virtual void IGraphics::DrawTriangle (const IColor & color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend * pBlend = 0, float thickness = 1.f) pure virtual
Draw a triangle to the graphics context.
Parameters
color The color to draw the shape with
x1 The X coordinate in the graphics context of the first vertex
y1 The Y coordinate in the graphics context of the first vertex
x2 The X coordinate in the graphics context of the second vertex
y2 The Y coordinate in the graphics context of the second vertex
x3 The X coordinate in the graphics context of the third vertex
y3 The Y coordinate in the graphics context of the third vertex
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestArcControl::Draw(), IGraphicsLiveEdit::Draw(), IVectorBase::DrawPressableTriangle(), and EndFrame().
void IGraphics::DrawVerticalLine (const IColor & color, const IRECT & bounds, float x, const IBlend * pBlend = 0, float thickness = 1.f)
Draw a vertical line, within a rectangular region of the graphics context.
Parameters
color The color to draw the line with
bounds The rectangular region to draw the line in
x
Definition at line 632 of file IGraphics.cpp.
References Clip().
Referenced by IVXYPadControl::Draw(), and EndFrame().
void IGraphics::DrawVerticalLine (const IColor & color, float xi, float yLo, float yHi, const IBlend * pBlend = 0, float thickness = 1.f)
Todo:
Parameters
color The color to draw the line with
xi
Definition at line 646 of file IGraphics.cpp.
void IGraphics::EnableLiveEdit (bool enable, const char * file = 0, int gridsize = 10)
Live edit mode allows you to relocate controls at runtime in debug builds and save the locations to a predefined file (e.g.
main plugin .cpp file)
Todo:
we need a separate page for liveedit info
Parameters
enable Set true if you wish to enable live editing mode
file The absolute path of the file which contains the layout info (correctly tagged) for live editing
gridsize The size of the layout grid in pixels
Definition at line 1407 of file IGraphics.cpp.
References IControl::GetDelegate(), LoadSVG(), LoadWinResource(), and LocateResource().
Referenced by ShowControlBoundsEnabled().
void IGraphics::EnableMouseOver (bool enable) inline
Parameters
enable Set true if you want to handle mouse over messages. Note: this may increase the amount CPU usage if you redraw on mouse overs etc
Definition at line 1398 of file IGraphics.h.
References ReleaseMouseCapture().
Referenced by IGraphicsLiveEdit::OnInit().
bool IGraphics::EnableMultiTouch (bool enable) inline
Enable/disable multi touch, if platform supports it.
Returns
true if platform supports it
Definition at line 1048 of file IGraphics.h.
References PlatformSupportsMultiTouch().
void IGraphics::EnableTooltips (bool enable)
Parameters
enable Set true to enable tool tips when the user mouses over a control
Definition at line 1401 of file IGraphics.cpp.
Referenced by PlatformSupportsMultiTouch().
ILayerPtr IGraphics::EndLayer ()
/todo
Returns
ILayerPtr /todo
Definition at line 1796 of file IGraphics.cpp.
Referenced by TestMaskControl::Draw(), GFXLabelControl::Draw(), TestLayerControl::Draw(), TestShadowGradientControl::Draw(), TestSVGControl::Draw(), TestMTControl::Draw(), TestDropShadowControl::Draw(), TestBlendControl::Draw(), TestKeyboardControl::Draw(), IVPlotControl::Draw(), ISVGControl::Draw(), IPopupMenuControl::DrawPanelShadow(), and EndFrame().
virtual void IGraphics::FillArc (const IColor & color, float cx, float cy, float r, float a1, float a2, const IBlend * pBlend = 0) pure virtual
Fill an arc segment in the graphics context with a color.
Parameters
color The color to fill the shape with
cx The X coordinate in the graphics context of the centre of the circle on which the arc lies
cy The Y coordinate in the graphics context of the centre of the circle on which the arc lies
r The radius of the circle on which the arc lies
a1 the start angle of the arc at in degrees clockwise where 0 is up
a2 the end angle of the arc at in degrees clockwise where 0 is up
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestArcControl::Draw(), and EndFrame().
virtual void IGraphics::FillCircle (const IColor & color, float cx, float cy, float r, const IBlend * pBlend = 0) pure virtual
Fill a circle in the graphics context with a color.
Parameters
color The color to fill the shape with
cx The X coordinate in the graphics context of the centre of the circle
cy The Y coordinate in the graphics context of the centre of the circle
r The radius of the circle
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestLayerControl::Draw(), TestDropShadowControl::Draw(), TestArcControl::Draw(), IControl::DrawPTHighlight(), and EndFrame().
virtual void IGraphics::FillConvexPolygon (const IColor & color, float * x, float * y, int nPoints, const IBlend * pBlend = 0) pure virtual
Fill a convex polygon in the graphics context with a color.
Parameters
color The color to fill the shape with
x Pointer to the first element in an array of X coordinates for the vertices of the polygon
y Pointer to the first element in an array of Y coordinates for the vertices of the polygon
nPoints The number of points in the coordinate arrays
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestPolyControl::Draw(), and EndFrame().
virtual void IGraphics::FillEllipse (const IColor & color, const IRECT & bounds, const IBlend * pBlend = 0) pure virtual
Fill an ellipse within a rectangular region of the graphics context.
Parameters
color The color to fill the shape with
bounds The rectangular region to fill the shape in
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestMTControl::Draw(), ILEDControl< MAXNC, QUEUE_SIZE >::Draw(), and EndFrame().
virtual void IGraphics::FillEllipse (const IColor & color, float x, float y, float r1, float r2, float angle = 0.0, const IBlend * pBlend = 0) pure virtual
Fill an ellipse in the graphics context.
Parameters
color The color to draw the shape with
x The X coordinate in the graphics context of the centre of the ellipse
y The Y coordinate in the graphics context of the centre of the ellipse
r1 The radius of the ellipse along the line found by rotating the x-axis by the angle
r2 The radius of the ellipse along the line found by rotating the y-axis by the angle
angle The angle rotates the radii r1 and r2 clockwise in degrees to adjust the orientation
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsPathBase, and IGraphicsLice.
virtual void IGraphics::FillRect (const IColor & color, const IRECT & bounds, const IBlend * pBlend = 0) pure virtual
Fill a rectangular region of the graphics context with a color.
Parameters
color The color to fill the shape with
bounds The rectangular region to fill the shape in
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestMaskControl::Draw(), TestCursorControl::Draw(), GFXLabelControl::Draw(), TestShadowGradientControl::Draw(), TestImageControl::Draw(), TestTextControl::Draw(), TestArcControl::Draw(), TestFlexBoxControl::Draw(), TestSVGControl::Draw(), TestBlendControl::Draw(), TestBezierControl::Draw(), TestFontControl::Draw(), TestTextOrientationControl::Draw(), TestTextSizeControl::Draw(), TestDirBrowseControl::Draw(), ITextEntryControl::Draw(), TestAnimationControl::Draw(), IVNumberBoxControl::Draw(), IFPSDisplayControl::Draw(), TestKeyboardControl::Draw(), IVKeyboardControl::Draw(), IVRangeSliderControl::Draw(), IVColorSwatchControl::Draw(), IPanelControl::Draw(), ITextControl::Draw(), IURLControl::Draw(), PlaceHolder::Draw(), IPopupMenuControl::DrawCellBackground(), IPopupMenuControl::DrawSeparator(), EndFrame(), IVSwitchControl::OnInit(), and IVKeyboardControl::OnMidi().
virtual void IGraphics::FillRoundRect (const IColor & color, const IRECT & bounds, float cornerRadius = 5.f, const IBlend * pBlend = 0) pure virtual
Fill a rounded rectangle in the graphics context with a color.
Parameters
color The color to fill the shape with
bounds The rectangular region to fill the shape in
cornerRadius The corner radius in pixels
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestLayerControl::Draw(), TestPolyControl::Draw(), IVSlideSwitchControl::Draw(), IVKeyboardControl::Draw(), IVSliderControl::Draw(), IPopupMenuControl::DrawPanelBackground(), IPopupMenuControl::DrawPanelShadow(), IVectorBase::DrawPressableRectangle(), IPopupMenuControl::DrawTick(), EndFrame(), and IVKeyboardControl::OnMidi().
virtual void IGraphics::FillRoundRect (const IColor & color, const IRECT & bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend * pBlend = 0) pure virtual
Fill a rounded rectangle in the graphics context with a color.
Parameters
color The color to fill the shape with
bounds The rectangular region to fill the shape in
cRTL The top left corner radius in pixels
cRTR The top right corner radius in pixels
cRBR The bottom right corner radius in pixels
cRBL The bottom left corner radius in pixels
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsPathBase, and IGraphicsLice.
virtual void IGraphics::FillTriangle (const IColor & color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend * pBlend = 0) pure virtual
Fill a triangle in the graphics context with a color.
Parameters
color The color to fill the shape with
x1 The X coordinate in the graphics context of the first vertex
y1 The Y coordinate in the graphics context of the first vertex
x2 The X coordinate in the graphics context of the second vertex
y2 The Y coordinate in the graphics context of the second vertex
x3 The X coordinate in the graphics context of the third vertex
y3 The Y coordinate in the graphics context of the third vertex
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by TestArcControl::Draw(), ICornerResizerControl::Draw(), TestDirBrowseControl::Draw(), IGraphicsLiveEdit::Draw(), ICaptionControl::Draw(), IPopupMenuControl::DrawCalloutArrow(), IPopupMenuControl::DrawDownArrow(), IVectorBase::DrawPressableTriangle(), IPopupMenuControl::DrawSubMenuArrow(), IPopupMenuControl::DrawUpArrow(), and EndFrame().
virtual bool IGraphics::FlippedBitmap () const protected pure virtual
Returns
bool true if the drawing backend flips images (e.g. OpenGL)
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsSkia, IGraphicsLice, IGraphicsCairo, and IGraphicsCanvas.
Referenced by AssetsLoaded().
template<typename T , typename... Args> void IGraphics::ForAllControls (T method, Args... args)
/todo
Template Parameters
T /todo
Args /todo
Parameters
method /todo
args /todo
Definition at line 431 of file IGraphics.cpp.
Referenced by GetPlatformWindowScale().
void IGraphics::ForAllControlsFunc (std::function< void(IControl &control)> func)
/todo
Parameters
func /todo
Definition at line 400 of file IGraphics.cpp.
Referenced by GetPlatformWindowScale().
virtual void IGraphics::ForceEndUserEdit () pure virtual
Call to force end text entry (will cancel any half input text.
Todo:
check)
Referenced by SetMouseCursor().
void IGraphics::ForControlInGroup (const char * group, std::function< void(IControl &control)> func)
Todo:
Parameters
group /todo
func /todo
Definition at line 379 of file IGraphics.cpp.
References IControl::GetGroup().
Referenced by GetPlatformWindowScale(), and IVGroupControl::OnResize().
void IGraphics::ForControlWithParam (int paramIdx, std::function< void(IControl &control)> func)
/todo
Parameters
paramIdx /todo
func /todo
Definition at line 365 of file IGraphics.cpp.
References IControl::LinkedToParam().
Referenced by GetPlatformWindowScale().
template<typename T , typename... Args> void IGraphics::ForMatchingControls (T method, int paramIdx, Args... args)
/todo
Template Parameters
T /todo
Args /todo
Parameters
method /todo
paramIdx /todo
args /todo
Definition at line 437 of file IGraphics.cpp.
Referenced by GetPlatformWindowScale().
void IGraphics::ForStandardControlsFunc (std::function< void(IControl &control)> func)
For all standard controls in the main control stack perform a function.
Parameters
func A std::function to perform on each control
Definition at line 394 of file IGraphics.cpp.
Referenced by GetPlatformWindowScale().
int IGraphics::FPS () const inline
Gets the drawing frame rate.
Returns
A whole number representing the desired frame rate at which the graphics context is redrawn. NOTE: the actual frame rate might be different
Definition at line 1005 of file IGraphics.h.
virtual float IGraphics::GetBackingPixelScale () const protected pure virtual
Returns
float /todo
Implemented in IGraphicsPathBase, and IGraphicsLice.
Referenced by AssetsLoaded(), and GetPixelSnapped().
IRECT IGraphics::GetBounds () const inline
Returns an IRECT that represents the entire UI bounds This is useful for programatically arranging UI elements by slicing up the IRECT using the various IRECT methods.
Returns
An IRECT that corresponds to the entire UI area, with, L = 0, T = 0, R = Width() and B = Height()
Definition at line 1097 of file IGraphics.h.
References Height(), and Width().
Referenced by IPopupMenuControl::CreatePopupMenu(), IGraphicsLiveEdit::Draw(), ICornerResizerControl::OnRescale(), IGraphicsLiveEdit::OnResize(), and IBubbleControl::SetMaxBounds().
IControl* IGraphics::GetControl (int idx) inline
Parameters
idx The index of the control to get
Returns
A pointer to the IControl object at idx or nullptr if not found
Definition at line 1246 of file IGraphics.h.
References GetControlWithTag().
Referenced by IGraphicsLiveEdit::Draw(), GetTouches(), IGraphicsLiveEdit::OnMouseDown(), IGraphicsLiveEdit::OnMouseDrag(), IGraphicsLiveEdit::OnMouseOver(), and IGraphicsLiveEdit::OnMouseUp().
IControl* IGraphics::GetControlInTextEntry () inline
Returns
Ptr to the control that launched the text entry
Definition at line 1035 of file IGraphics.h.
IControl * IGraphics::GetControlWithTag (int ctrlTag)
Parameters
ctrlTag The tag to look for
Returns
A pointer to the IControl object with the tag of nullptr if not found
Definition at line 341 of file IGraphics.cpp.
References IControl::GetTag().
Referenced by GetControl().
IGEditorDelegate* IGraphics::GetDelegate () inline
Gets a pointer to the delegate class that handles communication to and from this graphics context.
Returns
pointer to the delegate
Definition at line 1026 of file IGraphics.h.
virtual void* IGraphics::GetDrawContext () pure virtual
Gets a void pointer to IGraphics Draw Class context data (e.g raw framebuffer).
See draw class implementation headers (e.g. IGraphicsLice.h) for what you can cast the void pointer to
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsSkia, IGraphicsLice, IGraphicsCairo, and IGraphicsCanvas.
Referenced by TestDrawContextControl::Draw(), IColorPickerControl::Draw(), IPopupMenuControl::DrawPanelShadow(), IGraphicsPathBase::DrawRotatedSVG(), EndFrame(), and IBubbleControl::SetMaxBounds().
virtual const char* IGraphics::GetDrawingAPIStr () pure virtual
Returns
A CString representing the Drawing API in use e.g. "LICE"
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsCairo, IGraphicsLice, IGraphicsSkia, and IGraphicsCanvas.
Referenced by GFXLabelControl::Draw(), IFPSDisplayControl::Draw(), and EndFrame().
float IGraphics::GetDrawScale () const inline
Gets the graphics context scaling factor.
Returns
The scaling applied to the graphics context
Definition at line 1009 of file IGraphics.h.
Referenced by IGraphicsPathBase::GetBackingPixelScale(), and ICornerResizerControl::OnRescale().
int IGraphics::GetLastClickedParamForPTAutomation ()
[AAX only]
Returns
An integer representing the last clicked parameter index (or -1 if none)
Definition at line 1299 of file IGraphics.cpp.
Referenced by SetTabletInput().
virtual void IGraphics::GetLayerBitmapData (const ILayerPtr & layer, RawBitmapData & data) pure virtual
/todo
Parameters
layer /todo
data /todo
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsSkia, IGraphicsLice, IGraphicsCairo, and IGraphicsCanvas.
Referenced by UpdateLayer().
void IGraphics::GetMouseDownPoint (float & x, float & y) const inline
Get the x, y position in the graphics context of the last mouse down message.
Does not get cleared on mouse up etc.
Parameters
x Where the X position will be stored
y Where the Y position will be stored
Definition at line 1412 of file IGraphics.h.
Referenced by IGraphicsLiveEdit::OnMouseDrag(), IGraphicsLiveEdit::OnPopupMenuSelection(), and SplashClickActionFunc().
int IGraphics::GetMouseOver () const inline
Returns
An integer representing the control index in IGraphics::mControls which the mouse is over, or -1 if it is not
Definition at line 1407 of file IGraphics.h.
int IGraphics::GetParamIdxForPTAutomation (float x, float y)
[AAX only] This can be called by the ProTools API class (e.g.
IPlugAAX) in order to ascertain the parameter linked to the control under the mouse. The purpose is to facillitate ProTool's special contextual menus (for configuring parameter automation)
Parameters
x The X coordinate in the graphics context to check
y The Y coordinate in the graphics contextto check
Returns
An integer representing the parameter index that was found (or -1 if not found)
Definition at line 1292 of file IGraphics.cpp.
References IControl::GetParamIdx().
Referenced by SetTabletInput().
IRECT IGraphics::GetPixelSnapped (IRECT & r) const inline
Gets the nearest backing pixel aligned rect to the input IRECT.
Parameters
r The IRECT to snap
Returns
The IRECT nearest to the input IRECT that is aligned exactly to backing pixels
Definition at line 1022 of file IGraphics.h.
References GetBackingPixelScale(), and IRECT::GetPixelSnapped().
virtual const char* IGraphics::GetPlatformAPIStr () inline virtual
Returns
A CString representing the Platform API in use e.g. "macOS"
Definition at line 818 of file IGraphics.h.
void* IGraphics::GetPlatformContext () inline
Get the platform level draw context - an HDC or CGContextRef.
Returns
void pointer to an HDC or CGContext
Definition at line 839 of file IGraphics.h.
virtual int IGraphics::GetPlatformWindowScale () const inline virtual
Returns a scaling factor for resizing parent windows via the host/plugin API.
Returns
A scaling factor for resizing parent windows
Definition at line 1122 of file IGraphics.h.
References AttachBackground(), AttachBubbleControl(), AttachCornerResizer(), AttachPanelBackground(), AttachPopupMenuControl(), Draw(), ForAllControls(), ForAllControlsFunc(), ForControlInGroup(), ForControlWithParam(), ForMatchingControls(), ForStandardControlsFunc(), and ShowFPSDisplay().
virtual IColor IGraphics::GetPoint (int x, int y) pure virtual
Get the color of a point in the graphics context.
On a 1:1 screen this corresponds to a pixel.
Todo:
check this
Parameters
x The X coordinate in the graphics context of the pixel
y The Y coordinate in the graphics context of the pixel
Returns
An IColor specifiying the color of the pixel at x,y
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsSkia, IGraphicsLice, IGraphicsCairo, and IGraphicsCanvas.
Referenced by EndFrame().
IPopupMenuControl* IGraphics::GetPopupMenuControl () inline
Returns
Pointer to the special pop-up menu control, if one has been attached.
Todo:
Definition at line 1274 of file IGraphics.h.
IPopupMenu& IGraphics::GetPromptMenu () inline
Returns
Get a persistant IPopupMenu (remember to clear it before use)
Definition at line 1029 of file IGraphics.h.
EUIResizerMode IGraphics::GetResizerMode () const inline
Returns
An EUIResizerMode Representing whether the graphics context should scale or be resized, e.g. when dragging a corner resizer
Definition at line 1041 of file IGraphics.h.
bool IGraphics::GetResizingInProcess () const inline
Returns
true if resizing is in process
Definition at line 1044 of file IGraphics.h.
IBitmap IGraphics::GetScaledBitmap (IBitmap & inBitmap)
Get a version of the input bitmap from the cache that corresponds to the current screen scale For example, when IControl::OnRescale() is called bitmap-based IControls can load in.
Parameters
inBitmap The source bitmap to find a scaled version of
Returns
IBitmap The scaled bitmap
Definition at line 1394 of file IGraphics.cpp.
References IBitmap::GetFramesAreHorizontal(), IBitmap::GetResourceName(), and IBitmap::N().
Referenced by EndFrame(), IBButtonControl::OnRescale(), IBSwitchControl::OnRescale(), IBKnobControl::OnRescale(), IBSliderControl::OnRescale(), IBTextControl::OnRescale(), and IBitmapControl::OnRescale().
int IGraphics::GetScreenScale () const inline
Gets the display scaling factor.
Returns
The scale factor of the display on which this graphics context is currently located
Definition at line 1013 of file IGraphics.h.
Referenced by IGraphicsLice::GetBackingPixelScale(), and IGraphicsPathBase::GetBackingPixelScale().
const char* IGraphics::GetSharedResourcesSubPath () const inline
Gets the name of the shared resources subpath.
Definition at line 1454 of file IGraphics.h.
ITextEntryControl* IGraphics::GetTextEntryControl () inline
Returns
Pointer to the special text entry control, if one has been attached.
Todo:
Definition at line 1277 of file IGraphics.h.
References StyleAllVectorControls(), and UpdatePeers().
virtual bool IGraphics::GetTextFromClipboard (WDL_String & str) pure virtual
Get text from the clipboard.
Parameters
str A WDL_String that will be filled with the text that is currently on the clipboard
Returns
/c true on success
Referenced by WindowIsOpen().
float IGraphics::GetTotalScale () const inline
Gets the combined screen and display scaling factor.
Returns
The draw scale * screen scale
Definition at line 1017 of file IGraphics.h.
virtual void* IGraphics::GetWindow () pure virtual
Get a pointer to the platform view e.g.
HWND or NSView for this graphics context return void pointer to platform window or view handle
Referenced by SetMouseCursor(), and WindowIsOpen().
virtual void* IGraphics::GetWinModuleHandle () inline virtual
Returns
a void pointer that can be cast back to HINSTANCE to get the module handle on windows, returns nullptr on other platforms
Definition at line 830 of file IGraphics.h.
int IGraphics::Height () const inline
Gets the height of the graphics context.
Returns
A whole number representing the height of the graphics context in pixels on a 1:1 screen
Definition at line 993 of file IGraphics.h.
Referenced by GetBounds().
void IGraphics::HideControl (int paramIdx, bool hide)
Hide controls linked to a specific parameter.
Parameters
paramIdx The parameter index
hide /true to hide
Definition at line 355 of file IGraphics.cpp.
References IControl::Hide().
Referenced by NControls().
virtual void IGraphics::HideMouseCursor (bool hide = true, bool lock = true) pure virtual
Call to hide the mouse cursor.
Parameters
hide /todo
lock /todo
Referenced by TestPolyControl::OnMouseDown(), TestArcControl::OnMouseDown(), IVNumberBoxControl::OnMouseDown(), IVXYPadControl::OnMouseDown(), IKnobControlBase::OnMouseDown(), ISliderControlBase::OnMouseDown(), TestPolyControl::OnMouseUp(), TestArcControl::OnMouseUp(), IVNumberBoxControl::OnMouseUp(), IVXYPadControl::OnMouseUp(), IKnobControlBase::OnMouseUp(), ISliderControlBase::OnMouseUp(), and PathClipRegion().
bool IGraphics::IsDirty (IRECTList & rects)
Called repeatedly at frame rate by the platform class to check what the graphics context says is dirty.
Parameters
rects The rectangular regions which will be added to to mark what is dirty in the context
Returns
/c true if a control is dirty
Definition at line 695 of file IGraphics.cpp.
References IRECTList::Add(), IRECT::GetPadded(), IControl::GetRECT(), IControl::IsDirty(), and IControl::OnGUIIdle().
Referenced by SetTranslation().
bool IGraphics::IsInPlatformTextEntry () inline
Returns
True if a platform text entry in is progress
Definition at line 1032 of file IGraphics.h.
bool IGraphics::LiveEditEnabled () const inline
Returns
true if live edit mode is enabled
Definition at line 1092 of file IGraphics.h.
virtual APIBitmap* IGraphics::LoadAPIBitmap (const char * fileNameOrResID, int scale, EResourceLocation location, const char * ext) protected pure virtual
/todo
Parameters
fileNameOrResID /todo
scale /todo
location /todo
ext /todo
Returns
APIBitmap* /todo
Implemented in IGraphicsAGG, IGraphicsSkia, IGraphicsNanoVG, IGraphicsLice, IGraphicsCairo, and IGraphicsCanvas.
Referenced by SetSharedResourcesSubPath().
virtual bool IGraphics::LoadAPIFont (const char * fontID, const PlatformFontPtr & font) protected pure virtual
/todo
Parameters
fontID /todo
font /todo
Returns
bool* /todo
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsSkia, IGraphicsLice, IGraphicsCairo, and IGraphicsCanvas.
Referenced by SetSharedResourcesSubPath().
IBitmap IGraphics::LoadBitmap (const char * fileNameOrResID, int nStates = 1, bool framesAreHorizontal = false, int targetScale = 0) virtual
Load a bitmap image from disk or from windows resource.
Parameters
fileNameOrResID CString file name or resource ID
nStates The number of states/frames in a multi-frame stacked bitmap
framesAreHorizontal Set true if the frames in a bitmap are stacked horizontally
targetScale Set to a number > 0 to explicity load e.g. an @2x.png
Returns
An IBitmap representing the image
Reimplemented in IGraphicsNanoVG.
Definition at line 1566 of file IGraphics.cpp.
References APIBitmap::GetScale().
Referenced by TestImageControl::OnDrop(), and SetSharedResourcesSubPath().
bool IGraphics::LoadFont (const char * fontID, const char * fileNameOrResID) virtual
Load a font to be used by the graphics context.
Parameters
fontID A CString that will be used to reference the font
fileNameOrResID A CString absolute path or resource ID
Returns
true on success
Definition at line 1952 of file IGraphics.cpp.
Referenced by EndFrame().
bool IGraphics::LoadFont (const char * fontID, const char * fontName, ETextStyle style)
Todo:
Parameters
fontID A CString that will be used to reference the font
fontName A CString font name
style A font style
Returns
true on success
Definition at line 1969 of file IGraphics.cpp.
virtual PlatformFontPtr IGraphics::LoadPlatformFont (const char * fontID, const char * fileNameOrResID) pure virtual
Load a font from disk or resource in a platform format.
Parameters
fontID A string that is used to reference the font
fileNameOrResID A resource or file name/path
Returns
PlatformFontPtr from which the platform font can be retrieved
Referenced by ClientToScreen().
virtual PlatformFontPtr IGraphics::LoadPlatformFont (const char * fontID, const char * fontName, ETextStyle style) pure virtual
Load a system font in a platform format.
Parameters
fontID A string that is used to reference the font
fontName A string defining the font name
style An ETextStyle defining the font style
Returns
PlatformFontPtr from which the platform font can be retrieved
ISVG IGraphics::LoadSVG (const char * fileNameOrResID, const char * units = "px", float dpi = 72.f) virtual
Load an SVG from disk or from windows resource.
Parameters
fileNameOrResID A CString absolute path or resource ID
Returns
An ISVG representing the image
Definition at line 1517 of file IGraphics.cpp.
References LoadWinResource(), and LocateResource().
Referenced by EnableLiveEdit(), TestSVGControl::OnMouseDown(), and SetSharedResourcesSubPath().
void IGraphics::MeasureText (const IText & text, const char * str, IRECT & bounds) const virtual
Measure the rectangular region that some text will occupy.
Parameters
text An IText struct containing font and text properties and layout info
str The text string to draw in the graphics context
bounds after calling the method this IRECT will be updated with the rectangular region the text will occupy
Definition at line 531 of file IGraphics.cpp.
Referenced by IPopupMenuControl::CreatePopupMenu(), GFXLabelControl::Draw(), TestTextOrientationControl::Draw(), ITextControl::Draw(), PlaceHolder::Draw(), EndFrame(), and IBubbleControl::SetMaxBounds().
virtual void IGraphics::MoveMouseCursor (float x, float y) pure virtual
Force move the mouse cursor to a specific position in the graphics context.
Parameters
x New X position in pixels
y New Y position in pixels
Referenced by PathClipRegion().
bool IGraphics::MultiTouchEnabled () const inline
Returns
/c true if multi touch is enabled
Definition at line 1062 of file IGraphics.h.
int IGraphics::NControls () const inline
Returns
The number of controls that have been added to this graphics context
Definition at line 1289 of file IGraphics.h.
References DisableControl(), HideControl(), OnKeyDown(), OnKeyUp(), OnMouseDblClick(), OnMouseOut(), OnMouseOver(), OnMouseWheel(), RemoveAllControls(), RemoveControl(), RemoveControls(), RemoveControlWithTag(), SetAllControlsClean(), and SetAllControlsDirty().
Referenced by IGraphicsLiveEdit::Draw(), and IGraphicsLiveEdit::OnMouseDown().
void IGraphics::OnDrop (const char * str, float x, float y)
Parameters
str A CString with the absolute path of the dropped item
x The X coordinate in the graphics context where the drag and drop occurred
y The Y coordinate in the graphics context where the drag and drop occurred
Definition at line 1184 of file IGraphics.cpp.
References IControl::OnDrop().
Referenced by OnSetCursor().
void IGraphics::OnGUIIdle ()
Todo:
Definition at line 1372 of file IGraphics.cpp.
References IControl::OnGUIIdle().
Referenced by OnSetCursor().
bool IGraphics::OnKeyDown (float x, float y, const IKeyPress & key)
Parameters
x The X coordinate in the graphics context of the mouse cursor at the time of the key press
y The Y coordinate in the graphics context of the mouse cursor at the time of the key press
key
Definition at line 1128 of file IGraphics.cpp.
References IControl::OnKeyDown().
Referenced by NControls().
bool IGraphics::OnKeyUp (float x, float y, const IKeyPress & key)
Parameters
x The X coordinate in the graphics context of the mouse cursor at the time of the key press
y The Y coordinate in the graphics context of the mouse cursor at the time of the key press
key
Definition at line 1156 of file IGraphics.cpp.
References IControl::OnKeyUp().
Referenced by NControls().
bool IGraphics::OnMouseDblClick (float x, float y, const IMouseMod & mod)
Parameters
x The X coordinate in the graphics context at which the mouse event occurred
y The Y coordinate in the graphics context at which the mouse event occurred
mod IMouseMod struct contain information about the modifiers held
Returns
<#return value>
Definition at line 1077 of file IGraphics.cpp.
References IControl::GetMouseDblAsSingleClick(), IControl::OnMouseDblClick(), and IFPSDisplayControl::OnMouseDown().
Referenced by NControls().
void IGraphics::OnMouseOut ()
Todo:
Definition at line 1031 of file IGraphics.cpp.
References IControl::OnMouseDrag(), and IControl::OnMouseOut().
Referenced by NControls().
bool IGraphics::OnMouseOver (float x, float y, const IMouseMod & mod)
Parameters
x The X coordinate in the graphics context at which to draw
y The Y coordinate in the graphics context at which to draw
mod IMouseMod struct contain information about the modifiers held
Returns
true if handled
Todo:
check this
Definition at line 1004 of file IGraphics.cpp.
References IControl::OnMouseOver().
Referenced by NControls().
void IGraphics::OnMouseWheel (float x, float y, const IMouseMod & mod, float delta)
Parameters
x The X coordinate in the graphics context at which the mouse event occurred
y The Y coordinate in the graphics context at which the mouse event occurred
mod IMouseMod struct contain information about the modifiers held
delta Delta value
Todo:
explain
Definition at line 1113 of file IGraphics.cpp.
References IControl::OnMouseWheel().
Referenced by NControls().
void IGraphics::OnSetCursor () inline
Todo:
Definition at line 1384 of file IGraphics.h.
References OnDragResize(), OnDrop(), OnGUIIdle(), and SetMouseCursor().
virtual void IGraphics::OnViewDestroyed () inline virtual
Called after a platform view is destroyed, so that drawing classes can e.g.
free any resources
Reimplemented in IGraphicsNanoVG, and IGraphicsSkia.
Definition at line 95 of file IGraphics.h.
virtual void IGraphics::OnViewInitialized (void * pContext) inline virtual
Called after platform view initialization, so that drawing classes can e.g.
create an OpenGL context.
Reimplemented in IGraphicsNanoVG, and IGraphicsSkia.
Definition at line 92 of file IGraphics.h.
virtual bool IGraphics::OpenURL (const char * url, const char * msgWindowTitle = 0, const char * confirmMsg = 0, const char * errMsgOnFailure = 0) pure virtual
Open a URL in the platforms default browser.
Parameters
url CString specifying the URL to open
msgWindowTitle
Referenced by IURLControl::OnMouseDown(), and WindowIsOpen().
virtual void* IGraphics::OpenWindow (void * pParentWnd) pure virtual
Open a new platform view for this graphics context.
Parameters
pParentWnd void pointer to parent platform window or view handle (if applicable)
Todo:
check
Returns
void pointer to newly created IGraphics platform view
Referenced by SetMouseCursor().
virtual void IGraphics::PathArc (float cx, float cy, float r, float a1, float a2, EWinding winding = EWinding::CW) inline virtual
/todo
Parameters
cx /todo
cy /todo
r /todo
a1 /todo
a2 /todo
Reimplemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsCairo, IGraphicsSkia, and IGraphicsCanvas.
Definition at line 612 of file IGraphics.h.
Referenced by TestMultiPathControl::Draw(), IVGroupControl::Draw(), IGraphicsPathBase::DrawArc(), IGraphicsPathBase::FillArc(), IGraphicsPathBase::PathCircle(), IGraphicsPathBase::PathRoundRect(), and IBubbleControl::SetMaxBounds().
virtual void IGraphics::PathCircle (float cx, float cy, float r) inline virtual
/todo
Parameters
cx /todo
cy /todo
r /todo
Reimplemented in IGraphicsPathBase.
Definition at line 618 of file IGraphics.h.
Referenced by TestMultiPathControl::Draw().
virtual void IGraphics::PathClipRegion (const IRECT r = IRECT()) inline virtual
/todo
Parameters
r /todo
Reimplemented in IGraphicsPathBase.
Definition at line 720 of file IGraphics.h.
References HideMouseCursor(), and MoveMouseCursor().
Referenced by IVDisplayControl::Draw(), and IVXYPadControl::Draw().
virtual void IGraphics::PathConvexPolygon (float * x, float * y, int nPoints) inline virtual
/todo
Parameters
x /todo
y /todo
nPoints /todo
Reimplemented in IGraphicsPathBase.
Definition at line 636 of file IGraphics.h.
virtual void IGraphics::PathCubicBezierTo (float c1x, float c1y, float c2x, float c2y, float x2, float y2) inline virtual
/todo
Parameters
c1x /todo
c1y /todo
c2x /todo
c2y /todo
x2 /todo
y2 /todo
Reimplemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsCairo, IGraphicsSkia, and IGraphicsCanvas.
Definition at line 659 of file IGraphics.h.
Referenced by TestMultiPathControl::Draw(), TestBezierControl::Draw(), and IGraphicsPathBase::DrawRotatedSVG().
virtual void IGraphics::PathEllipse (float x, float y, float r1, float r2, float angle = 0.0) inline virtual
/todo
Parameters
x /todo
y /todo
r1 /todo
r2 /todo
angle /todo
Reimplemented in IGraphicsPathBase.
Definition at line 626 of file IGraphics.h.
virtual void IGraphics::PathEllipse (const IRECT & bounds) inline virtual
/todo
Parameters
bounds /todo
Reimplemented in IGraphicsPathBase.
Definition at line 630 of file IGraphics.h.
virtual void IGraphics::PathFill (const IPattern & pattern, const IFillOptions & options = IFillOptions(), const IBlend * pBlend = 0) inline virtual
/todo
Parameters
pattern /todo
options /todo
pBlend /todo
Reimplemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsCairo, IGraphicsSkia, and IGraphicsCanvas.
Definition at line 679 of file IGraphics.h.
Referenced by TestMaskControl::Draw(), TestMultiPathControl::Draw(), TestGradientControl::Draw(), TestGesturesControl::Draw(), TestColorControl::Draw(), IFPSDisplayControl::Draw(), IPanelControl::Draw(), IGraphicsPathBase::DrawRotatedSVG(), IGraphicsPathBase::FillArc(), IGraphicsPathBase::FillCircle(), IGraphicsPathBase::FillConvexPolygon(), IGraphicsPathBase::FillEllipse(), IGraphicsPathBase::FillRect(), IGraphicsPathBase::FillRoundRect(), IGraphicsPathBase::FillTriangle(), and IBubbleControl::SetMaxBounds().
void IGraphics::PathLine (float x1, float y1, float x2, float y2) inline
/todo
Parameters
x1 /todo
y1 /todo
x2 /todo
y2 /todo
Definition at line 566 of file IGraphics.h.
References PathLineTo(), PathMoveTo(), and PathRadialLine().
virtual void IGraphics::PathLineTo (float x, float y) inline virtual
/todo
Parameters
x /todo
y /todo
Reimplemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsCairo, IGraphicsSkia, and IGraphicsCanvas.
Definition at line 646 of file IGraphics.h.
Referenced by TestMultiPathControl::Draw(), IVScopeControl< MAXNC, MAXBUF >::Draw(), IVDisplayControl::Draw(), IFPSDisplayControl::Draw(), IVGroupControl::Draw(), IGraphicsPathBase::DrawData(), IGraphicsPathBase::DrawDottedLine(), IGraphicsPathBase::DrawGrid(), IGraphicsPathBase::DrawLine(), IGraphicsPathBase::PathConvexPolygon(), PathLine(), IGraphicsPathBase::PathRect(), IGraphicsPathBase::PathTriangle(), and IBubbleControl::SetMaxBounds().
virtual void IGraphics::PathMoveTo (float x, float y) inline virtual
/todo
Parameters
x /todo
y /todo
Reimplemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsCairo, IGraphicsSkia, and IGraphicsCanvas.
Definition at line 641 of file IGraphics.h.
Referenced by TestMultiPathControl::Draw(), TestBezierControl::Draw(), IVScopeControl< MAXNC, MAXBUF >::Draw(), IVDisplayControl::Draw(), IFPSDisplayControl::Draw(), IVGroupControl::Draw(), IGraphicsPathBase::DrawData(), IGraphicsPathBase::DrawDottedLine(), IGraphicsPathBase::DrawGrid(), IGraphicsPathBase::DrawLine(), IGraphicsPathBase::DrawRotatedSVG(), IGraphicsPathBase::FillArc(), IGraphicsPathBase::PathCircle(), IGraphicsPathBase::PathConvexPolygon(), PathLine(), IGraphicsPathBase::PathRect(), IGraphicsPathBase::PathRoundRect(), IGraphicsPathBase::PathTriangle(), and IBubbleControl::SetMaxBounds().
virtual void IGraphics::PathQuadraticBezierTo (float cx, float cy, float x2, float y2) inline virtual
/todo
Parameters
cx /todo
cy /todo
x2 /todo
y2 /todo
Reimplemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsCairo, IGraphicsSkia, and IGraphicsCanvas.
Definition at line 666 of file IGraphics.h.
Referenced by TestBezierControl::Draw().
void IGraphics::PathRadialLine (float cx, float cy, float angle, float rMin, float rMax)
/todo
Parameters
cx /todo
cy /todo
angle /todo
rMin /todo
rMax /todo
Definition at line 663 of file IGraphics.cpp.
Referenced by PathLine().
virtual void IGraphics::PathRect (const IRECT & bounds) inline virtual
/todo
Parameters
bounds /todo
Reimplemented in IGraphicsPathBase.
Definition at line 591 of file IGraphics.h.
Referenced by TestMaskControl::Draw(), TestMultiPathControl::Draw(), TestGesturesControl::Draw(), TestColorControl::Draw(), and IPanelControl::Draw().
virtual void IGraphics::PathRoundRect (const IRECT & bounds, float ctl, float ctr, float cbl, float cbr) inline virtual
/todo
Parameters
bounds /todo
ctl /todo
ctr /todo
cbl /todo
cbr /todo
Reimplemented in IGraphicsPathBase.
Definition at line 599 of file IGraphics.h.
Referenced by TestGradientControl::Draw(), and TestMultiPathControl::Draw().
virtual void IGraphics::PathRoundRect (const IRECT & bounds, float cr = 5.f) inline virtual
/todo
Parameters
bounds /todo
cr /todo
Reimplemented in IGraphicsPathBase.
Definition at line 604 of file IGraphics.h.
virtual void IGraphics::PathSetWinding (bool clockwise) inline virtual
/todo
Parameters
clockwise /todo
Reimplemented in IGraphicsNanoVG.
Definition at line 650 of file IGraphics.h.
Referenced by IGraphicsPathBase::DrawRotatedSVG().
virtual void IGraphics::PathStroke (const IPattern & pattern, float thickness, const IStrokeOptions & options = IStrokeOptions(), const IBlend * pBlend = 0) inline virtual
/todo
Parameters
pattern /todo
thickness /todo
options /todo
pBlend /todo
Reimplemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsCairo, IGraphicsSkia, and IGraphicsCanvas.
Definition at line 673 of file IGraphics.h.
Referenced by TestGradientControl::Draw(), TestMultiPathControl::Draw(), TestBezierControl::Draw(), IVScopeControl< MAXNC, MAXBUF >::Draw(), IVDisplayControl::Draw(), IVGroupControl::Draw(), IGraphicsPathBase::DrawArc(), IGraphicsPathBase::DrawCircle(), IGraphicsPathBase::DrawConvexPolygon(), IGraphicsPathBase::DrawData(), IGraphicsPathBase::DrawDottedLine(), IGraphicsPathBase::DrawDottedRect(), IGraphicsPathBase::DrawEllipse(), IGraphicsPathBase::DrawGrid(), IGraphicsPathBase::DrawLine(), IGraphicsPathBase::DrawRect(), IGraphicsPathBase::DrawRotatedSVG(), IGraphicsPathBase::DrawRoundRect(), IGraphicsPathBase::DrawTriangle(), and IBubbleControl::SetMaxBounds().
virtual void IGraphics::PathTransformMatrix (const IMatrix & matrix) inline virtual
/todo
Parameters
matrix /todo
Reimplemented in IGraphicsPathBase.
Definition at line 716 of file IGraphics.h.
virtual void IGraphics::PathTransformReset (bool clearStates = false) inline virtual
/todo
Parameters
clearStates /todo
Reimplemented in IGraphicsPathBase.
Definition at line 689 of file IGraphics.h.
virtual void IGraphics::PathTransformRotate (float angle) inline virtual
/todo
Parameters
angle /todo
Reimplemented in IGraphicsPathBase.
Definition at line 707 of file IGraphics.h.
Referenced by TestGesturesControl::Draw().
virtual void IGraphics::PathTransformScale (float scaleX, float scaleY) inline virtual
/todo
Parameters
scaleX /todo
scaleY /todo
Reimplemented in IGraphicsPathBase.
Definition at line 699 of file IGraphics.h.
Referenced by TestGesturesControl::Draw().
virtual void IGraphics::PathTransformScale (float scale) inline virtual
/todo
Parameters
scale /todo
Reimplemented in IGraphicsPathBase.
Definition at line 703 of file IGraphics.h.
virtual void IGraphics::PathTransformSkew (float xAngle, float yAngle) inline virtual
/todo
Parameters
xAngle /todo
yAngle /todo
Reimplemented in IGraphicsPathBase.
Definition at line 712 of file IGraphics.h.
virtual void IGraphics::PathTransformTranslate (float x, float y) inline virtual
/todo
Parameters
x /todo
y /todo
Reimplemented in IGraphicsPathBase.
Definition at line 694 of file IGraphics.h.
Referenced by TestGesturesControl::Draw().
virtual void IGraphics::PathTriangle (float x1, float y1, float x2, float y2, float x3, float y3) inline virtual
/todo
Parameters
x1 /todo
y1 /todo
x2 /todo
y2 /todo
x3 /todo
y3 /todo
Reimplemented in IGraphicsPathBase.
Definition at line 587 of file IGraphics.h.
virtual bool IGraphics::PlatformSupportsMultiTouch () const inline virtual
Returns
/c true if the platform supports multi touch
Definition at line 1065 of file IGraphics.h.
References AssignParamNameToolTips(), and EnableTooltips().
Referenced by EnableMultiTouch().
ILayer * IGraphics::PopLayer ()
/todo
Returns
ILayer* /todo
Definition at line 1810 of file IGraphics.cpp.
Referenced by UpdateLayer().
void IGraphics::PopupHostContextMenuForParam (int controlIdx, int paramIdx, float x, float y)
[VST3 primarily] In VST3 plug-ins this enable support for the IContextMenu interface, which allows the host to add contextual options to e.g.
automate a parameter associated with a control
Parameters
controlIdx The index of the control in the control stack
paramIdx The parameter index associated with the control
x The X coordinate in the graphics context at which to popup the context menu
y The Y coordinate in the graphics context at which to popup the context menu
Definition at line 1367 of file IGraphics.cpp.
Referenced by SetTabletInput().
void IGraphics::PopupHostContextMenuForParam (IControl * pControl, int paramIdx, float x, float y)
/todo
Parameters
pControl /todo
paramIdx /todo
x /todo
y /todo
Definition at line 1311 of file IGraphics.cpp.
References IControl::CreateContextMenu(), and IControl::GetDelegate().
virtual bool IGraphics::PromptForColor (IColor & color, const char * str = "", IColorPickerHandlerFunc func = nullptr) pure virtual
Create a platform color chooser dialog.
NOTE: this method will block the main thread
Parameters
color When a color is chosen the IColor referenced will be updated with the new color
str The text to display in the dialog box e.g. "Please choose a color... (Windows only)"
IColorPickerHandlerFunc func callback for asynchronous color pickers
Returns
/true if prompt completed successfully
Referenced by IVColorSwatchControl::OnMouseDown(), and WindowIsOpen().
virtual void IGraphics::PromptForDirectory (WDL_String & dir) pure virtual
Create a platform file prompt dialog to choose a directory path for opening/saving a directory.
NOTE: this method will block the main thread
Parameters
dir Non const WDL_String reference specifying the directory path. Set this prior to calling the method for save dialogs, to provide a default path. For load dialogs, on successful selection of a directory this will get set to the full path.
Referenced by WindowIsOpen().
virtual void IGraphics::PromptForFile (WDL_String & fileName, WDL_String & path, EFileAction action = EFileAction::Open, const char * extensions = 0) pure virtual
Create a platform file prompt dialog to choose a file/directory path for opening/saving a file/directory.
NOTE: this method will block the main thread
Parameters
fileName Non const WDL_String reference specifying the file name. Set this prior to calling the method for save dialogs, to provide a default file name. For load dialogs, on successful selection of a file this will get set to the files name.
path WDL_String reference where the path will be put on success or empty string on failure/user cancelled
action Determines whether this is an open dialog or a save dialog
extensions A comma separated CString list of file extensions to filter in the dialog (e.g. .wav, .aif
Todo:
check
Referenced by TestImageControl::OnMouseDown(), TestSVGControl::OnMouseDown(), and WindowIsOpen().
void IGraphics::PromptUserInput (IControl & control, const IRECT & bounds, int valIdx = 0)
Prompt for user input either using a text entry or pop up menu.
Parameters
control Reference to the control which the prompt relates to
bounds Rectangular region of the graphics context that the prompt (e.g. text entry box) should occupy
valIdx The value index for the control value that the prompt relates to
Definition at line 482 of file IGraphics.cpp.
References IParam::GetDisplayForHost(), IParam::GetDisplayText(), IParam::GetNameForHost(), IControl::GetParam(), IControl::GetText(), IParam::NDisplayTexts(), and IParam::Type().
Referenced by IControl::PromptUserInput(), and SetTranslation().
void IGraphics::PushLayer (ILayer * layer)
/todo
Parameters
layer /todo
Definition at line 1801 of file IGraphics.cpp.
References ILayer::Bounds().
Referenced by UpdateLayer().
void IGraphics::ReleaseBitmap (const IBitmap & bitmap) virtual
Releases an IBitmap from the cache/static storage.
Parameters
bitmap The bitmap to release
Reimplemented in IGraphicsNanoVG.
Definition at line 1628 of file IGraphics.cpp.
References IBitmap::GetAPIBitmap().
Referenced by EndFrame().
void IGraphics::ReleaseMouseCapture ()
Used to tell the graphics context to stop tracking mouse interaction with a control.
Todo:
internal only?
Definition at line 1190 of file IGraphics.cpp.
References IRECT::Contains(), IControl::GetIgnoreMouse(), IControl::GetMouseEventsWhenDisabled(), IControl::GetMouseOverWhenDisabled(), IControl::GetRECT(), IControl::GetWantsMultiTouch(), IControl::IsDisabled(), IControl::IsHidden(), and IControl::IsHit().
Referenced by EnableMouseOver(), and IURLControl::OnMouseDown().
void IGraphics::RemoveAllControls ()
Removes all regular IControls from the control list, as well as special controls (frees memory).
Definition at line 152 of file IGraphics.cpp.
Referenced by NControls().
void IGraphics::RemoveControls (int fromIdx)
Remove controls from the control list above a particular index, (frees memory).
Definition at line 127 of file IGraphics.cpp.
Referenced by NControls().
void IGraphics::RemoveControlWithTag (int ctrlTag)
Remove controls from the control list with a particular tag.
Definition at line 121 of file IGraphics.cpp.
Referenced by NControls().
void IGraphics::Resize (int w, int h, float scale)
Todo:
detailed description of how this works
Parameters
w New width in pixels
h New height in pixels
scale New scale ratio
Definition at line 89 of file IGraphics.cpp.
References Clip(), IControl::GetDelegate(), IGEditorDelegate::LayoutUI(), and IControl::OnResize().
Referenced by ICornerResizerControl::OnMouseDblClick(), and SetSizeConstraints().
void IGraphics::ResumeLayer (ILayerPtr & layer)
/todo
Parameters
layer /todo
Definition at line 1783 of file IGraphics.cpp.
Referenced by TestMTControl::Draw(), TestKeyboardControl::Draw(), and EndFrame().
void IGraphics::RetainBitmap (const IBitmap & bitmap, const char * cacheName) virtual
Adds an IBitmap to the cache/static storage.
Parameters
bitmap The bitmap to cache
cacheName The name by which this bitmap is identified int the cache
Reimplemented in IGraphicsNanoVG.
Definition at line 1634 of file IGraphics.cpp.
References IBitmap::GetAPIBitmap(), and IBitmap::GetScale().
Referenced by EndFrame().
virtual bool IGraphics::RevealPathInExplorerOrFinder (WDL_String & path, bool select = false) inline virtual
Parameters
path WDL_String reference where the path will be put on success or empty string on failure
select et true if you want to select the item in Explorer/Finder
Returns
true on success (if the path was valid)
Definition at line 823 of file IGraphics.h.
IBitmap IGraphics::ScaleBitmap (const IBitmap & inBitmap, const char * cacheName, int targetScale) virtual
Returns a new IBitmap, an integer scaled version of the input, and adds it to the cache.
Parameters
inbitmap The source bitmap to be scaled
cacheName The name by which this bitmap is identified int the cache (along with targetScale)
targetScale An integer scale factor of the new bitmap
Returns
IBitmap The new IBitmap that has been added to the cache
Definition at line 1640 of file IGraphics.cpp.
References IBitmap::GetDrawScale(), IBitmap::GetFramesAreHorizontal(), IBitmap::H(), IBitmap::N(), and IBitmap::W().
Referenced by EndFrame().
APIBitmap * IGraphics::SearchBitmapInCache (const char * fileName, int targetScale, int & sourceScale) protected
Search the static storage cache for a bitmap image resource matching the target scale.
Parameters
fileName /todo
targetScale /todo
sourceScale /todo
Returns
pointer to the bitmap in the cache, or null pointer if not found
Definition at line 1695 of file IGraphics.cpp.
Referenced by AssetsLoaded().
EResourceLocation IGraphics::SearchImageResource (const char * fileName, const char * type, WDL_String & result, int targetScale, int & sourceScale) protected
Search for a bitmap image resource matching the target scale.
Parameters
fileName /todo
type /todo
result /todo
targetScale /todo
sourceScale /todo
Returns
EResourceLocation /todo
Definition at line 1672 of file IGraphics.cpp.
References LocateResource().
Referenced by AssetsLoaded().
void IGraphics::SearchNextScale (int & sourceScale, int targetScale) inline protected
Utility used by SearchImageResource/SearchBitmapInCache.
Parameters
sourceScale /todo
targetScale /todo
Definition at line 1661 of file IGraphics.cpp.
Referenced by AssetsLoaded().
void IGraphics::SetControlValueAfterPopupMenu (IPopupMenu * pMenu)
Called by PopupMenuControl in order to update a control with a new value after returning from the non-blocking menu.
The base class has a record of the control, so it is not needed here.
Parameters
pMenu The menu that was clicked
Definition at line 190 of file IGraphics.cpp.
Referenced by IPopupMenuControl::CalculateMenuPanels(), and CreatePopupMenu().
void IGraphics::SetControlValueAfterTextEdit (const char * str)
Called by the platform class after returning from a text entry in order to update a control with a new value.
The base class has a record of the control, so it is not needed here.
Parameters
str The new value as a CString
Definition at line 170 of file IGraphics.cpp.
References IParam::StringToValue(), and IParam::ToNormalized().
Referenced by CreatePopupMenu().
void IGraphics::SetDisplayTickFunc (IDisplayTickFunc func) inline
Sets a function that is called at the frame rate, prior to checking for dirty controls.
Parameters
func The function to call
Definition at line 1101 of file IGraphics.h.
void IGraphics::SetKeyHandlerFunc (IKeyHandlerFunc func) inline
/todo
Parameters
keyHandlerFunc /todo
Definition at line 1105 of file IGraphics.h.
References AttachImGui(), OnGestureRecognized(), RespondsToGesture(), and SetQwertyMidiKeyHandlerFunc().
virtual ECursor IGraphics::SetMouseCursor (ECursor cursorType = ECursor::ARROW) inline virtual
Sets the mouse cursor to one of ECursor (implementations should return the result of the base implementation)
Parameters
cursorType The cursor type
Returns
the previous cursor type so it can be restored later
Definition at line 746 of file IGraphics.h.
References CloseWindow(), ForceEndUserEdit(), GetWindow(), and OpenWindow().
Referenced by TestCursorControl::OnMouseDown(), TestCursorControl::OnMouseOut(), ICornerResizerControl::OnMouseOut(), IURLControl::OnMouseOut(), ICornerResizerControl::OnMouseOver(), IGraphicsLiveEdit::OnMouseOver(), IURLControl::OnMouseOver(), and OnSetCursor().
virtual void IGraphics::SetPlatformContext (void * pContext) inline virtual
Set the platform draw context Used in order to set the platform level draw context - CGContextRef context on macOS and the GDI HDC draw context handle on Windows.
Parameters
pContext void pointer to CGContextRef or HDC
Reimplemented in IGraphicsCairo.
Definition at line 835 of file IGraphics.h.
Referenced by IGraphicsCairo::SetPlatformContext().
void IGraphics::SetPTParameterHighlight (int paramIdx, bool isHighlighted, int color)
[AAX only]
Todo:
Parameters
paramIdx The index of the parameter to highlight
isHighlighted /c true if the parameter should be highlighted
color An integer corresponding to AAX_EParameterHighlight
Todo:
check Enum name
Definition at line 1306 of file IGraphics.cpp.
References IControl::SetPTParameterHighlight().
Referenced by SetTabletInput().
void IGraphics::SetQwertyMidiKeyHandlerFunc (std::function< void(const IMidiMsg &msg)> func = nullptr)
A helper to set the IGraphics KeyHandlerFunc in order to make an instrument playable via QWERTY keys.
Parameters
func A function to do something when a MIDI message is triggered
Definition at line 2034 of file IGraphics.cpp.
References Clip(), IControl::GetDelegate(), IMidiMsg::MakeNoteOffMsg(), IMidiMsg::MakeNoteOnMsg(), and IEditorDelegate::SendMidiMsgFromUI().
Referenced by SetKeyHandlerFunc().
void IGraphics::SetScaleConstraints (float lo, float hi) inline
/todo
Parameters
lo /todo
hi /todo
Definition at line 955 of file IGraphics.h.
void IGraphics::SetScreenScale (int scale)
Called by the platform IGraphics class when moving to a new screen to set DPI.
Parameters
scale The scale of the display, typically 2 on a macOS retina screen
Definition at line 80 of file IGraphics.cpp.
References IControl::GetDelegate(), and IControl::OnRescale().
Referenced by GetBundleID().
void IGraphics::SetSharedResourcesSubPath (const char * sharedResourcesSubPath) inline
Sets the name of the shared resources subpath.
Definition at line 1457 of file IGraphics.h.
References AttachGestureRecognizer(), AttachGestureRecognizerToRegion(), ClearGestureRegions(), CreateAPIBitmap(), LoadAPIBitmap(), LoadAPIFont(), LoadBitmap(), and LoadSVG().
void IGraphics::SetSizeConstraints (int widthLo, int widthHi, int heightLo, int heightHi) inline
/todo
Parameters
widthLo /todo
widthHi /todo
heightLo /todo
heightHi /todo
Definition at line 966 of file IGraphics.h.
References Resize(), and SetStrictDrawing().
void IGraphics::SetStrictDrawing (bool strict)
Enables strict drawing mode.
Todo:
explain strict drawing
Parameters
strict Set /true to enable strict drawing mode
Definition at line 823 of file IGraphics.cpp.
References IEditorDelegate::BeginInformHostOfParamChangeFromUI(), IEditorDelegate::EndInformHostOfParamChangeFromUI(), IControl::GetDelegate(), IControl::GetParamIdx(), IControl::GetValIdxForPos(), IControl::NVals(), IControl::OnMouseDown(), IControl::OnMouseUp(), and IControl::OnTouchCancelled().
Referenced by SetSizeConstraints().
void IGraphics::SetTabletInput (bool tablet) inline
Set by the platform class if the mouse input is coming from a tablet/stylus.
Parameters
tablet true means input is from a tablet
Definition at line 1416 of file IGraphics.h.
References GetLastClickedParamForPTAutomation(), GetParamIdxForPTAutomation(), PopupHostContextMenuForParam(), and SetPTParameterHighlight().
virtual bool IGraphics::SetTextInClipboard (const char * str) pure virtual
Set text in the clipboard.
Parameters
str A CString that will be used to set the current text in the clipboard
Returns
/c true on success
Referenced by WindowIsOpen().
void IGraphics::SetTranslation (float x, float y) inline
Called by some platform IGraphics classes in order to translate the graphics context, in response to e.g.
iOS onscreen keyboard appearing
Definition at line 902 of file IGraphics.h.
References CreatePopupMenu(), Draw(), IsDirty(), and PromptUserInput().
virtual void IGraphics::SetWinModuleHandle (void * pHinstance) inline virtual
Used on Windows to set the HINSTANCE module handle, which allows graphics APIs to load resources from the binary.
Parameters
pHinstance void pointer to the platform instance
Definition at line 827 of file IGraphics.h.
void IGraphics::ShowAreaDrawn (bool enable) inline
Parameters
enable Set true if you wish to show the rectangular region that is drawn on each frame, in order to debug redraw problems
Definition at line 1077 of file IGraphics.h.
References SetAllControlsDirty().
bool IGraphics::ShowAreaDrawnEnabled () const inline
Returns
true if showning the area drawn on each frame
Definition at line 1080 of file IGraphics.h.
void IGraphics::ShowControlBounds (bool enable) inline
Parameters
enable Set true if you wish to draw the rectangular region of the graphics context occupied by each IControl in mControls
Definition at line 1074 of file IGraphics.h.
References SetAllControlsDirty().
bool IGraphics::ShowControlBoundsEnabled () const inline
Returns
true if showning the control bounds
Definition at line 1083 of file IGraphics.h.
References EnableLiveEdit().
void IGraphics::ShowFPSDisplay (bool enable)
Shows a control to display the frame rate of drawing.
Parameters
enable true to show
Definition at line 322 of file IGraphics.cpp.
References IControl::GetDelegate().
Referenced by GetPlatformWindowScale().
bool IGraphics::ShowingFPSDisplay () inline
Returns
true if performance display is shown
Definition at line 1232 of file IGraphics.h.
References AttachControl(), and AttachTextEntryControl().
virtual EMsgBoxResult IGraphics::ShowMessageBox (const char * str, const char * caption, EMsgBoxType type, IMsgBoxCompletionHanderFunc completionHandler = nullptr) pure virtual
Pop up a modal platform message box dialog.
NOTE: this method will block the main thread
Parameters
str The text message to display in the dialogue
caption The title of the message box window
Todo:
check
Parameters
type EMsgBoxType describing the button options available
See also
EMsgBoxType
Returns
Todo:
check
Referenced by WindowIsOpen().
void IGraphics::StartLayer (IControl * owner, const IRECT & r)
/todo
Parameters
r /todo
Definition at line 1773 of file IGraphics.cpp.
References IRECT::GetPixelAligned(), IControl::GetRECT(), IRECT::H(), and IRECT::W().
Referenced by TestMaskControl::Draw(), GFXLabelControl::Draw(), TestLayerControl::Draw(), TestShadowGradientControl::Draw(), TestSVGControl::Draw(), TestMTControl::Draw(), TestDropShadowControl::Draw(), TestBlendControl::Draw(), TestKeyboardControl::Draw(), IVPlotControl::Draw(), ISVGControl::Draw(), IPopupMenuControl::DrawPanelShadow(), and EndFrame().
void IGraphics::StyleAllVectorControls (const IVStyle & style)
Helper method to style all of the controls which inherit IVectorBase.
Parameters
IVStyle Style for the controls
Definition at line 1711 of file IGraphics.cpp.
Referenced by GetTextEntryControl().
bool IGraphics::TooltipsEnabled () const inline
Returns
true if tool tips are enabled
Definition at line 1038 of file IGraphics.h.
void IGraphics::UpdatePeers (IControl * pCaller, int callerValIdx)
This method is called after interacting with a control, so that any other controls linked to the same parameter index, will also be set dirty, and have their values updated.
Parameters
pCaller The control that triggered the parameter change.
callerValIdx The index of the value in the control that triggered the parameter change.
Definition at line 463 of file IGraphics.cpp.
References IControl::GetParamIdx(), and IControl::GetValue().
Referenced by GetTextEntryControl(), and IControl::SetDirty().
virtual void IGraphics::UpdateTooltips () pure virtual
Call this if you modify control tool tips at runtime.
Todo:
explain
Referenced by IPopupMenuControl::CalculateMenuPanels(), and WindowIsOpen().
int IGraphics::Width () const inline
Gets the width of the graphics context.
Returns
A whole number representing the width of the graphics context in pixels on a 1:1 screen
Definition at line 989 of file IGraphics.h.
Referenced by GetBounds().
int IGraphics::WindowHeight () const inline
Gets the height of the graphics context including scaling (not display scaling!)
Returns
A whole number representing the height of the graphics context with scaling in pixels on a 1:1 screen
Definition at line 1001 of file IGraphics.h.
virtual bool IGraphics::WindowIsOpen () inline virtual
Returns
/true if the platform window/view is open
Definition at line 769 of file IGraphics.h.
References GetTextFromClipboard(), GetWindow(), OpenURL(), PromptForColor(), PromptForDirectory(), PromptForFile(), SetTextInClipboard(), ShowMessageBox(), and UpdateTooltips().
int IGraphics::WindowWidth () const inline
Gets the width of the graphics context including scaling (not display scaling!)
Returns
A whole number representing the width of the graphics context with scaling in pixels on a 1:1 screen
Definition at line 997 of file IGraphics.h.
The documentation for this class was generated from the following files:
IGraphics.h
IGraphics.cpp