iPlug2: ILayer Class Reference
ILayer Class Reference
IGraphics::Structs
An abstraction that is used to store a temporary raster image/framebuffer.
#include <IGraphicsStructs.h>
Public Member Functions
ILayer (APIBitmap *pBitmap, const IRECT &r, IControl *pControl, const IRECT &cr)
/todo
ILayer (const ILayer &)=delete
ILayer operator= (const ILayer &)=delete
void Invalidate ()
/todo
const APIBitmap * GetAPIBitmap () const
IBitmap GetBitmap () const
const IRECT & Bounds () const
Detailed Description
An abstraction that is used to store a temporary raster image/framebuffer.
The layer is drawn with a specific offset to the graphics context. ILayers take ownership of the underlying bitmaps In GPU-based backends (NanoVG), this is a texture.
Definition at line 2190 of file IGraphicsStructs.h.
Constructor & Destructor Documentation
ILayer::ILayer (APIBitmap * pBitmap, const IRECT & r, IControl * pControl, const IRECT & cr) inline
/todo
Parameters
pBitmap /todo
r /todo
pControl /todo
cr /todo
Definition at line 2200 of file IGraphicsStructs.h.
Member Function Documentation
const IRECT& ILayer::Bounds () const inline
Returns
const IRECT& /todo
Definition at line 2221 of file IGraphicsStructs.h.
Referenced by IGraphicsLice::DoDrawText(), and IGraphics::PushLayer().
const APIBitmap* ILayer::GetAPIBitmap () const inline
Returns
const APIBitmap* /todo
Definition at line 2215 of file IGraphicsStructs.h.
Referenced by IGraphicsLice::DoDrawText().
IBitmap ILayer::GetBitmap () const inline
Returns
IBitmap /todo
Definition at line 2218 of file IGraphicsStructs.h.
The documentation for this class was generated from the following file:
IGraphicsStructs.h