iPlug2: IGraphicsCanvas Class Reference
IGraphicsCanvas Class Reference
IGraphics::DrawClasses
IGraphics draw class HTML5 canvas.
#include <IGraphicsCanvas.h>
Classes
class Bitmap
struct Font
Public Member Functions
IGraphicsCanvas (IGEditorDelegate &dlg, int w, int h, int fps, float scale)
const char * GetDrawingAPIStr () override
void DrawBitmap (const IBitmap &bitmap, const IRECT &bounds, int srcX, int srcY, const IBlend *pBlend) override
Draw a bitmap (raster) image to the graphics context.
void DrawResize () override
/todo
void PathClear () override
/todo
void PathClose () override
/todo
void PathArc (float cx, float cy, float r, float a1, float a2, EWinding winding) override
/todo
void PathMoveTo (float x, float y) override
/todo
void PathLineTo (float x, float y) override
/todo
void PathCubicBezierTo (float c1x, float c1y, float c2x, float c2y, float x2, float y2) override
/todo
void PathQuadraticBezierTo (float cx, float cy, float x2, float y2) override
/todo
void PathStroke (const IPattern &pattern, float thickness, const IStrokeOptions &options, const IBlend *pBlend) override
/todo
void PathFill (const IPattern &pattern, const IFillOptions &options, const IBlend *pBlend) override
/todo
IColor GetPoint (int x, int y) override
Get the color of a point in the graphics context.
void * GetDrawContext () override
Gets a void pointer to IGraphics Draw Class context data (e.g raw framebuffer).
bool BitmapExtSupported (const char *ext) override
Checks a file extension and reports whether this drawing API supports loading that extension.
Public Member Functions inherited from IGraphicsPathBase
IGraphicsPathBase (IGEditorDelegate &dlg, int w, int h, int fps, float scale)
void DrawRotatedBitmap (const IBitmap &bitmap, float destCtrX, float destCtrY, double angle, int yOffsetZeroDeg, const IBlend *pBlend) override
Draw a bitmap (raster) image to the graphics context with rotation.
void DrawPoint (const IColor &color, float x, float y, const IBlend *pBlend) override
Fill a rectangle corresponding to a pixel on a 1:1 screen with a color.
void DrawLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend, float thickness) override
Draw a line to the graphics context.
void DrawGrid (const IColor &color, const IRECT &bounds, float gridSizeH, float gridSizeV, const IBlend *pBlend, float thickness) override
Draw a grid to the graphics context.
void DrawData (const IColor &color, const IRECT &bounds, float *normYPoints, int nPoints, float *normXPoints, const IBlend *pBlend, float thickness) override
/todo
void DrawDottedLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend, float thickness, float dashLen) override
Draw a dotted line to the graphics context.
void DrawTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend, float thickness) override
Draw a triangle to the graphics context.
void DrawRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend, float thickness) override
Draw a rectangle to the graphics context.
void DrawRoundRect (const IColor &color, const IRECT &bounds, float cornerRadius, const IBlend *pBlend, float thickness) override
Draw a rounded rectangle to the graphics context.
void DrawRoundRect (const IColor &color, const IRECT &bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend *pBlend, float thickness) override
Draw a rounded rectangle to the graphics context with individual corner roundness.
void DrawConvexPolygon (const IColor &color, float *x, float *y, int nPoints, const IBlend *pBlend, float thickness) override
Draw a convex polygon to the graphics to the graphics context.
void DrawArc (const IColor &color, float cx, float cy, float r, float a1, float a2, const IBlend *pBlend, float thickness) override
Draw an arc to the graphics context.
void DrawCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend, float thickness) override
Draw a circle to the graphics context.
void DrawDottedRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend, float thickness, float dashLen) override
Draw a dotted rectangle to the graphics context.
void DrawEllipse (const IColor &color, const IRECT &bounds, const IBlend *pBlend, float thickness) override
Draw an ellipse within a rectangular region of the graphics context.
void DrawEllipse (const IColor &color, float x, float y, float r1, float r2, float angle, const IBlend *pBlend, float thickness) override
Draw an ellipse around a central point given two radii and an angle of orientation.
void FillTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend) override
Fill a triangle in the graphics context with a color.
void FillRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend) override
Fill a rectangular region of the graphics context with a color.
void FillRoundRect (const IColor &color, const IRECT &bounds, float cornerRadius, const IBlend *pBlend) override
Fill a rounded rectangle in the graphics context with a color.
void FillRoundRect (const IColor &color, const IRECT &bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend *pBlend) override
Fill a rounded rectangle in the graphics context with a color.
void FillConvexPolygon (const IColor &color, float *x, float *y, int nPoints, const IBlend *pBlend) override
Fill a convex polygon in the graphics context with a color.
void FillArc (const IColor &color, float cx, float cy, float r, float a1, float a2, const IBlend *pBlend) override
Fill an arc segment in the graphics context with a color.
void FillCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend) override
Fill a circle in the graphics context with a color.
void FillEllipse (const IColor &color, const IRECT &bounds, const IBlend *pBlend) override
Fill an ellipse within a rectangular region of the graphics context.
void FillEllipse (const IColor &color, float x, float y, float r1, float r2, float angle, const IBlend *pBlend) override
Fill an ellipse in the graphics context.
bool HasPathSupport () const override
void PathTriangle (float x1, float y1, float x2, float y2, float x3, float y3) override
/todo
void PathRect (const IRECT &bounds) override
/todo
void PathRoundRect (const IRECT &bounds, float ctl, float ctr, float cbl, float cbr) override
/todo
void PathRoundRect (const IRECT &bounds, float cr) override
/todo
void PathEllipse (float x, float y, float r1, float r2, float angle=0.0) override
/todo
void PathEllipse (const IRECT &bounds) override
/todo
void PathCircle (float cx, float cy, float r) override
/todo
void PathConvexPolygon (float *x, float *y, int nPoints) override
/todo
void PathTransformSave () override
/todo
void PathTransformRestore () override
/todo
void PathTransformReset (bool clearStates=false) override
/todo
void PathTransformTranslate (float x, float y) override
/todo
void PathTransformScale (float scaleX, float scaleY) override
/todo
void PathTransformScale (float scale) override
/todo
void PathTransformRotate (float angle) override
/todo
void PathTransformSkew (float xAngle, float yAngle) override
/todo
void PathTransformMatrix (const IMatrix &matrix) override
/todo
void PathClipRegion (const IRECT r=IRECT()) override
/todo
void DrawFittedBitmap (const IBitmap &bitmap, const IRECT &bounds, const IBlend *pBlend) override
Draw a bitmap (raster) image to the graphics context, scaling the image to fit the bounds.
void DrawSVG (const ISVG &svg, const IRECT &dest, const IBlend *pBlend) override
Draw an SVG image to the graphics context.
void DrawRotatedSVG (const ISVG &svg, float destCtrX, float destCtrY, float width, float height, double angle, const IBlend *pBlend) override
Draw an SVG image to the graphics context with rotation.
Public Member Functions inherited from IGraphics
virtual void BeginFrame ()
Called at the beginning of drawing.
virtual void OnViewInitialized (void *pContext)
Called after platform view initialization, so that drawing classes can e.g.
virtual void OnViewDestroyed ()
Called after a platform view is destroyed, so that drawing classes can e.g.
virtual void EndFrame ()
Called by some drawing API classes to finally blit the draw bitmap onto the screen or perform other cleanup after drawing.
void DrawText (const IText &text, const char *str, const IRECT &bounds, const IBlend *pBlend=0)
Draw some text to the graphics context in a specific rectangle.
void DrawText (const IText &text, const char *str, float x, float y, const IBlend *pBlend=0)
Draw some text to the graphics context at a point.
virtual void MeasureText (const IText &text, const char *str, IRECT &bounds) const
Measure the rectangular region that some text will occupy.
virtual IBitmap ScaleBitmap (const IBitmap &inBitmap, const char *cacheName, int targetScale)
Returns a new IBitmap, an integer scaled version of the input, and adds it to the cache.
virtual void RetainBitmap (const IBitmap &bitmap, const char *cacheName)
Adds an IBitmap to the cache/static storage.
virtual void ReleaseBitmap (const IBitmap &bitmap)
Releases an IBitmap from the cache/static storage.
IBitmap GetScaledBitmap (IBitmap &inBitmap)
Get a version of the input bitmap from the cache that corresponds to the current screen scale For example, when IControl::OnRescale() is called bitmap-based IControls can load in.
void DrawBitmap (const IBitmap &bitmap, const IRECT &bounds, int frame=1, const IBlend *pBlend=0)
Draws a bitmap into the graphics context.
void DrawBitmapedText (const IBitmap &bitmap, IRECT &bounds, IText &text, IBlend *pBlend, const char *str, bool vCenter=true, bool multiline=false, int charWidth=6, int charHeight=12, int charOffset=0)
Draws mono spaced bitmap text.
void DrawVerticalLine (const IColor &color, const IRECT &bounds, float x, const IBlend *pBlend=0, float thickness=1.f)
Draw a vertical line, within a rectangular region of the graphics context.
void DrawHorizontalLine (const IColor &color, const IRECT &bounds, float y, const IBlend *pBlend=0, float thickness=1.f)
Draw a horizontal line, within a rectangular region of the graphics context.
void DrawVerticalLine (const IColor &color, float xi, float yLo, float yHi, const IBlend *pBlend=0, float thickness=1.f)
void DrawHorizontalLine (const IColor &color, float yi, float xLo, float xHi, const IBlend *pBlend=0, float thickness=1.f)
void DrawRadialLine (const IColor &color, float cx, float cy, float angle, float rMin, float rMax, const IBlend *pBlend=0, float thickness=1.f)
Draw a radial line to the graphics context, useful for pointers on dials.
virtual bool LoadFont (const char *fontID, const char *fileNameOrResID)
Load a font to be used by the graphics context.
bool LoadFont (const char *fontID, const char *fontName, ETextStyle style)
void StartLayer (IControl *owner, const IRECT &r)
/todo
void ResumeLayer (ILayerPtr &layer)
/todo
ILayerPtr EndLayer ()
/todo
bool CheckLayer (const ILayerPtr &layer)
/todo
void DrawLayer (const ILayerPtr &layer, const IBlend *pBlend=nullptr)
/todo
void DrawFittedLayer (const ILayerPtr &layer, const IRECT &bounds, const IBlend *pBlend)
/todo
void DrawRotatedLayer (const ILayerPtr &layer, double angle)
/todo
void ApplyLayerDropShadow (ILayerPtr &layer, const IShadow &shadow)
Applies a dropshadow directly onto a layer.
virtual void UpdateLayer ()
/todo
void PushLayer (ILayer *layer)
/todo
ILayer * PopLayer ()
/todo
void PathLine (float x1, float y1, float x2, float y2)
/todo
void PathRadialLine (float cx, float cy, float angle, float rMin, float rMax)
/todo
virtual void PathSetWinding (bool clockwise)
/todo
virtual void HideMouseCursor (bool hide=true, bool lock=true)=0
Call to hide the mouse cursor.
virtual void MoveMouseCursor (float x, float y)=0
Force move the mouse cursor to a specific position in the graphics context.
virtual ECursor SetMouseCursor (ECursor cursorType=ECursor::ARROW)
Sets the mouse cursor to one of ECursor (implementations should return the result of the base implementation)
virtual void ForceEndUserEdit ()=0
Call to force end text entry (will cancel any half input text.
virtual void * OpenWindow (void *pParentWnd)=0
Open a new platform view for this graphics context.
virtual void CloseWindow ()=0
Close the platform view for this graphics context.
virtual void * GetWindow ()=0
Get a pointer to the platform view e.g.
virtual bool WindowIsOpen ()
virtual bool GetTextFromClipboard (WDL_String &str)=0
Get text from the clipboard.
virtual bool SetTextInClipboard (const char *str)=0
Set text in the clipboard.
virtual void UpdateTooltips ()=0
Call this if you modify control tool tips at runtime.
virtual EMsgBoxResult ShowMessageBox (const char *str, const char *caption, EMsgBoxType type, IMsgBoxCompletionHanderFunc completionHandler=nullptr)=0
Pop up a modal platform message box dialog.
virtual void PromptForFile (WDL_String &fileName, WDL_String &path, EFileAction action=EFileAction::Open, const char *extensions=0)=0
Create a platform file prompt dialog to choose a file/directory path for opening/saving a file/directory.
virtual void PromptForDirectory (WDL_String &dir)=0
Create a platform file prompt dialog to choose a directory path for opening/saving a directory.
virtual bool PromptForColor (IColor &color, const char *str="", IColorPickerHandlerFunc func=nullptr)=0
Create a platform color chooser dialog.
virtual bool OpenURL (const char *url, const char *msgWindowTitle=0, const char *confirmMsg=0, const char *errMsgOnFailure=0)=0
Open a URL in the platforms default browser.
virtual const char * GetPlatformAPIStr ()
virtual bool RevealPathInExplorerOrFinder (WDL_String &path, bool select=false)
virtual void SetWinModuleHandle (void *pHinstance)
Used on Windows to set the HINSTANCE module handle, which allows graphics APIs to load resources from the binary.
virtual void * GetWinModuleHandle ()
virtual void SetPlatformContext (void *pContext)
Set the platform draw context Used in order to set the platform level draw context - CGContextRef context on macOS and the GDI HDC draw context handle on Windows.
void * GetPlatformContext ()
Get the platform level draw context - an HDC or CGContextRef.
virtual void ClientToScreen (float &x, float &y)
Convert an x, y position in the view to screen coordinates.
virtual PlatformFontPtr LoadPlatformFont (const char *fontID, const char *fileNameOrResID)=0
Load a font from disk or resource in a platform format.
virtual PlatformFontPtr LoadPlatformFont (const char *fontID, const char *fontName, ETextStyle style)=0
Load a system font in a platform format.
virtual void CachePlatformFont (const char *fontID, const PlatformFontPtr &font)=0
Called to indicate that the platform should cache data about the platform font if needed.
virtual const char * GetBundleID ()
Get the bundle ID on macOS and iOS, returns emtpy string on other OSs.
IGraphics (IGEditorDelegate &dlg, int w, int h, int fps=0, float scale=1.)
IGraphics (const IGraphics &)=delete
IGraphics & operator= (const IGraphics &)=delete
void SetScreenScale (int scale)
Called by the platform IGraphics class when moving to a new screen to set DPI.
void SetTranslation (float x, float y)
Called by some platform IGraphics classes in order to translate the graphics context, in response to e.g.
bool IsDirty (IRECTList &rects)
Called repeatedly at frame rate by the platform class to check what the graphics context says is dirty.
void Draw (IRECTList &rects)
Called by the platform class indicating a number of rectangles in the UI that need to redraw.
void PromptUserInput (IControl &control, const IRECT &bounds, int valIdx=0)
Prompt for user input either using a text entry or pop up menu.
void CreatePopupMenu (IControl &control, IPopupMenu &menu, const IRECT &bounds, int valIdx=0)
Shows a pop up/contextual menu in relation to a rectangular region of the graphics context.
void CreatePopupMenu (IControl &control, IPopupMenu &menu, float x, float y, int valIdx=0)
Shows a pop up/contextual menu at point in the graphics context.
void CreateTextEntry (IControl &control, const IText &text, const IRECT &bounds, const char *str="", int valIdx=0)
Create a text entry box.
void SetControlValueAfterTextEdit (const char *str)
Called by the platform class after returning from a text entry in order to update a control with a new value.
void SetControlValueAfterPopupMenu (IPopupMenu *pMenu)
Called by PopupMenuControl in order to update a control with a new value after returning from the non-blocking menu.
void SetScaleConstraints (float lo, float hi)
/todo
void SetSizeConstraints (int widthLo, int widthHi, int heightLo, int heightHi)
/todo
void Resize (int w, int h, float scale)
void SetStrictDrawing (bool strict)
Enables strict drawing mode.
void SetLayoutOnResize (bool layoutOnResize)
int Width () const
Gets the width of the graphics context.
int Height () const
Gets the height of the graphics context.
int WindowWidth () const
Gets the width of the graphics context including scaling (not display scaling!)
int WindowHeight () const
Gets the height of the graphics context including scaling (not display scaling!)
int FPS () const
Gets the drawing frame rate.
float GetDrawScale () const
Gets the graphics context scaling factor.
int GetScreenScale () const
Gets the display scaling factor.
float GetTotalScale () const
Gets the combined screen and display scaling factor.
IRECT GetPixelSnapped (IRECT &r) const
Gets the nearest backing pixel aligned rect to the input IRECT.
IGEditorDelegate * GetDelegate ()
Gets a pointer to the delegate class that handles communication to and from this graphics context.
IPopupMenu & GetPromptMenu ()
bool IsInPlatformTextEntry ()
IControl * GetControlInTextEntry ()
bool TooltipsEnabled () const
EUIResizerMode GetResizerMode () const
bool GetResizingInProcess () const
bool EnableMultiTouch (bool enable)
Enable/disable multi touch, if platform supports it.
bool MultiTouchEnabled () const
virtual bool PlatformSupportsMultiTouch () const
void EnableTooltips (bool enable)
void AssignParamNameToolTips ()
Call this method in order to create tool tips for every IControl that show the associated parameter's name.
void ShowControlBounds (bool enable)
void ShowAreaDrawn (bool enable)
bool ShowAreaDrawnEnabled () const
bool ShowControlBoundsEnabled () const
void EnableLiveEdit (bool enable, const char *file=0, int gridsize=10)
Live edit mode allows you to relocate controls at runtime in debug builds and save the locations to a predefined file (e.g.
bool LiveEditEnabled () const
IRECT GetBounds () const
Returns an IRECT that represents the entire UI bounds This is useful for programatically arranging UI elements by slicing up the IRECT using the various IRECT methods.
void SetDisplayTickFunc (IDisplayTickFunc func)
Sets a function that is called at the frame rate, prior to checking for dirty controls.
void SetKeyHandlerFunc (IKeyHandlerFunc func)
/todo
void SetQwertyMidiKeyHandlerFunc (std::function< void(const IMidiMsg &msg)> func=nullptr)
A helper to set the IGraphics KeyHandlerFunc in order to make an instrument playable via QWERTY keys.
void AttachImGui (std::function< void(IGraphics *)> drawFunc, std::function< void()> setupFunc=nullptr)
/todo
bool RespondsToGesture (float x, float y)
Called by platform class to see if the point at x, y is linked to a gesture recognizer.
void OnGestureRecognized (const IGestureInfo &info)
Called by platform class when a gesture is recognized.
virtual int GetPlatformWindowScale () const
Returns a scaling factor for resizing parent windows via the host/plugin API.
void ForAllControlsFunc (std::function< void(IControl &control)> func)
/todo
template<typename T , typename... Args>
void ForAllControls (T method, Args...args)
/todo
void ForStandardControlsFunc (std::function< void(IControl &control)> func)
For all standard controls in the main control stack perform a function.
template<typename T , typename... Args>
void ForMatchingControls (T method, int paramIdx, Args...args)
/todo
void ForControlWithParam (int paramIdx, std::function< void(IControl &control)> func)
/todo
void ForControlInGroup (const char *group, std::function< void(IControl &control)> func)
void AttachBackground (const char *fileName)
Attach an IBitmapControl as the lowest IControl in the control stack to be the background for the graphics context.
void AttachPanelBackground (const IPattern &color)
Attach an IPanelControl as the lowest IControl in the control stack to fill the background with a solid color.
void AttachCornerResizer (EUIResizerMode sizeMode=EUIResizerMode::Scale, bool layoutOnResize=false)
Attach the default control to scale or increase the UI size by dragging the plug-in bottom right-hand corner.
void AttachCornerResizer (ICornerResizerControl *pControl, EUIResizerMode sizeMode=EUIResizerMode::Scale, bool layoutOnResize=false)
Attach your own control to scale or increase the UI size by dragging the plug-in bottom right-hand corner.
void AttachPopupMenuControl (const IText &text=DEFAULT_TEXT, const IRECT &bounds=IRECT())
Attach a control for pop-up menus, to override platform style menus.
void AttachBubbleControl (const IText &text=DEFAULT_TEXT)
Attach the default control to show text as a control changes.
void AttachBubbleControl (IBubbleControl *pControl)
Attach a custom control to show text as a control changes.
void ShowBubbleControl (IControl *pCaller, float x, float y, const char *str, EDirection dir=EDirection::Horizontal, IRECT minimumContentBounds=IRECT())
void ShowFPSDisplay (bool enable)
Shows a control to display the frame rate of drawing.
bool ShowingFPSDisplay ()
void AttachTextEntryControl ()
Attach a control for text entry, to override platform text entry.
IControl * AttachControl (IControl *pControl, int ctrlTag=kNoTag, const char *group="")
Attach an IControl to the graphics context and add it to the top of the control stack.
IControl * GetControl (int idx)
IControl * GetControlWithTag (int ctrlTag)
bool ControlIsCaptured () const
Check to see if any control is captured.
bool ControlIsCaptured (IControl *pControl) const
Check to see if the control is already captured.
void GetTouches (IControl *pControl, std::vector< ITouchID > &touchesOnThisControl) const
Populate a vector with the touchIDs active on pControl.
IControl * GetBackgroundControl ()
IPopupMenuControl * GetPopupMenuControl ()
ITextEntryControl * GetTextEntryControl ()
void StyleAllVectorControls (const IVStyle &style)
Helper method to style all of the controls which inherit IVectorBase.
void UpdatePeers (IControl *pCaller, int callerValIdx)
This method is called after interacting with a control, so that any other controls linked to the same parameter index, will also be set dirty, and have their values updated.
int NControls () const
void RemoveControl (IControl *pControl)
Remove control from the control list.
void RemoveControlWithTag (int ctrlTag)
Remove controls from the control list with a particular tag.
void RemoveControls (int fromIdx)
Remove controls from the control list above a particular index, (frees memory).
void RemoveAllControls ()
Removes all regular IControls from the control list, as well as special controls (frees memory).
void HideControl (int paramIdx, bool hide)
Hide controls linked to a specific parameter.
void DisableControl (int paramIdx, bool diable)
Disable or enable controls linked to a specific parameter.
void SetAllControlsDirty ()
Calls SetDirty() on every control.
void SetAllControlsClean ()
Calls SetClean() on every control.
void OnMouseDown (const std::vector< IMouseInfo > &points)
void OnMouseUp (const std::vector< IMouseInfo > &points)
void OnMouseDrag (const std::vector< IMouseInfo > &points)
void OnTouchCancelled (const std::vector< IMouseInfo > &points)
bool OnMouseDblClick (float x, float y, const IMouseMod &mod)
void OnMouseWheel (float x, float y, const IMouseMod &mod, float delta)
bool OnKeyDown (float x, float y, const IKeyPress &key)
bool OnKeyUp (float x, float y, const IKeyPress &key)
bool OnMouseOver (float x, float y, const IMouseMod &mod)
void OnMouseOut ()
void OnSetCursor ()
void OnDrop (const char *str, float x, float y)
void OnGUIIdle ()
void OnDragResize (float x, float y)
Called by ICornerResizerControl as the corner is dragged to resize.
void EnableMouseOver (bool enable)
void ReleaseMouseCapture ()
Used to tell the graphics context to stop tracking mouse interaction with a control.
bool CanEnableMouseOver () const
int GetMouseOver () const
void GetMouseDownPoint (float &x, float &y) const
Get the x, y position in the graphics context of the last mouse down message.
void SetTabletInput (bool tablet)
Set by the platform class if the mouse input is coming from a tablet/stylus.
int GetParamIdxForPTAutomation (float x, float y)
[AAX only] This can be called by the ProTools API class (e.g.
int GetLastClickedParamForPTAutomation ()
[AAX only]
void SetPTParameterHighlight (int paramIdx, bool isHighlighted, int color)
[AAX only]
void PopupHostContextMenuForParam (int controlIdx, int paramIdx, float x, float y)
[VST3 primarily] In VST3 plug-ins this enable support for the IContextMenu interface, which allows the host to add contextual options to e.g.
void PopupHostContextMenuForParam (IControl *pControl, int paramIdx, float x, float y)
/todo
const char * GetSharedResourcesSubPath () const
Gets the name of the shared resources subpath.
void SetSharedResourcesSubPath (const char *sharedResourcesSubPath)
Sets the name of the shared resources subpath.
virtual IBitmap LoadBitmap (const char *fileNameOrResID, int nStates=1, bool framesAreHorizontal=false, int targetScale=0)
Load a bitmap image from disk or from windows resource.
virtual ISVG LoadSVG (const char *fileNameOrResID, const char *units="px", float dpi=72.f)
Load an SVG from disk or from windows resource.
virtual void AttachGestureRecognizer (EGestureType type)
Registers a gesture recognizer with the graphics context.
void AttachGestureRecognizerToRegion (const IRECT &bounds, EGestureType type, IGestureFunc func)
Attach a gesture recognizer to a rectangular region of the GUI, i.e.
void ClearGestureRegions ()
Remove all gesture recognizers linked to regions.
Protected Member Functions
APIBitmap * LoadAPIBitmap (const char *fileNameOrResID, int scale, EResourceLocation location, const char *ext) override
/todo
APIBitmap * CreateAPIBitmap (int width, int height, int scale, double drawScale) override
Creates a new API bitmap, either in memory or as a GPU texture.
bool LoadAPIFont (const char *fontID, const PlatformFontPtr &font) override
/todo
bool AssetsLoaded () override
Specialized in IGraphicsCanvas drawing backend.
int AlphaChannel () const override
bool FlippedBitmap () const override
void GetLayerBitmapData (const ILayerPtr &layer, RawBitmapData &data) override
/todo
void ApplyShadowMask (ILayerPtr &layer, RawBitmapData &mask, const IShadow &shadow) override
/todo
void DoMeasureText (const IText &text, const char *str, IRECT &bounds) const override
/todo
void DoDrawText (const IText &text, const char *str, const IRECT &bounds, const IBlend *pBlend) override
/todo
Protected Member Functions inherited from IGraphicsPathBase
void DoTextRotation (const IText &text, const IRECT &bounds, const IRECT &rect)
float GetBackingPixelScale () const override
IMatrix GetTransformMatrix () const
Protected Member Functions inherited from IGraphics
virtual void ActivateGLContext ()
virtual void DeactivateGLContext ()
virtual void CreatePlatformTextEntry (int paramIdx, const IText &text, const IRECT &bounds, int length, const char *str)=0
/todo
virtual IPopupMenu * CreatePlatformPopupMenu (IPopupMenu &menu, const IRECT &bounds, bool &isAsync)=0
Calls the platform backend to create the platform popup menu.
void SearchNextScale (int &sourceScale, int targetScale)
Utility used by SearchImageResource/SearchBitmapInCache.
EResourceLocation SearchImageResource (const char *fileName, const char *type, WDL_String &result, int targetScale, int &sourceScale)
Search for a bitmap image resource matching the target scale.
APIBitmap * SearchBitmapInCache (const char *fileName, int targetScale, int &sourceScale)
Search the static storage cache for a bitmap image resource matching the target scale.
void DoMeasureTextRotation (const IText &text, const IRECT &bounds, IRECT &rect) const
/todo
void CalculateTextRotation (const IText &text, const IRECT &bounds, IRECT &rect, double &tx, double &ty) const
/todo text
Additional Inherited Members
Protected Attributes inherited from IGraphics
IGEditorDelegate * mDelegate
void * mPlatformContext = nullptr
bool mCursorHidden = false
bool mCursorLock = false
bool mTabletInput = false
float mCursorX = -1.f
float mCursorY = -1.f
float mXTranslation = 0.f
float mYTranslation = 0.f
std::stack< ILayer * > mLayers
Detailed Description
IGraphics draw class HTML5 canvas.
Definition at line 30 of file IGraphicsCanvas.h.
Member Function Documentation
int IGraphicsCanvas::AlphaChannel () const inline override protected virtual
Returns
int The index of the alpha component in a drawing backend's pixel (RGBA or ARGB)
Implements IGraphics.
Definition at line 69 of file IGraphicsCanvas.h.
void IGraphicsCanvas::ApplyShadowMask (ILayerPtr & layer, RawBitmapData & mask, const IShadow & shadow) override protected virtual
/todo
Parameters
layer /todo
mask /todo
shadow /todo
Implements IGraphics.
Definition at line 503 of file IGraphicsCanvas.cpp.
References APIBitmap::GetBitmap(), APIBitmap::GetDrawScale(), APIBitmap::GetHeight(), APIBitmap::GetScale(), and APIBitmap::GetWidth().
APIBitmap * IGraphicsCanvas::CreateAPIBitmap (int width, int height, int scale, double drawScale) override protected virtual
Creates a new API bitmap, either in memory or as a GPU texture.
Parameters
width The desired width
height The desired height
scale The scale in relation to 1:1 pixels
drawScale /todo
Returns
APIBitmap* The new API Bitmap
Implements IGraphics.
Definition at line 356 of file IGraphicsCanvas.cpp.
void IGraphicsCanvas::DoDrawText (const IText & text, const char * str, const IRECT & bounds, const IBlend * pBlend) override protected virtual
/todo
Parameters
text /todo
str /todo
bounds /todo
pBlend /todo
Implements IGraphics.
Definition at line 310 of file IGraphicsCanvas.cpp.
References IRECT::H(), IMatrix::Scale(), IMatrix::Transform(), IMatrix::Translate(), and IRECT::W().
void IGraphicsCanvas::DoMeasureText (const IText & text, const char * str, IRECT & bounds) const override protected virtual
/todo
Parameters
text /todo
str /todo
bounds /todo
pBlend /todo
Implements IGraphics.
Definition at line 302 of file IGraphicsCanvas.cpp.
void IGraphicsCanvas::DrawBitmap (const IBitmap & bitmap, const IRECT & bounds, int srcX, int srcY, const IBlend * pBlend) override virtual
Draw a bitmap (raster) image to the graphics context.
Parameters
bitmap The bitmap image to draw to the graphics context
bounds The rectangular region to draw the image in
srcX The X coordinate in the source image to draw from
Todo:
Parameters
srcY The Y coordinate in the source image to draw from
Todo:
Parameters
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 103 of file IGraphicsCanvas.cpp.
References BlendWeight(), IBitmap::GetAPIBitmap(), APIBitmap::GetBitmap(), IBitmap::GetDrawScale(), IBitmap::GetScale(), IRECT::H(), IRECT::Scale(), and IRECT::W().
bool IGraphicsCanvas::FlippedBitmap () const inline override protected virtual
Returns
bool true if the drawing backend flips images (e.g. OpenGL)
Implements IGraphics.
Definition at line 70 of file IGraphicsCanvas.h.
void* IGraphicsCanvas::GetDrawContext () inline override virtual
Gets a void pointer to IGraphics Draw Class context data (e.g raw framebuffer).
See draw class implementation headers (e.g. IGraphicsLice.h) for what you can cast the void pointer to
Implements IGraphics.
Definition at line 57 of file IGraphicsCanvas.h.
const char* IGraphicsCanvas::GetDrawingAPIStr () inline override virtual
Returns
A CString representing the Drawing API in use e.g. "LICE"
Implements IGraphics.
Definition at line 40 of file IGraphicsCanvas.h.
void IGraphicsCanvas::GetLayerBitmapData (const ILayerPtr & layer, RawBitmapData & data) override protected virtual
/todo
Parameters
layer /todo
data /todo
Implements IGraphics.
Definition at line 484 of file IGraphicsCanvas.cpp.
References APIBitmap::GetBitmap(), APIBitmap::GetHeight(), and APIBitmap::GetWidth().
IColor IGraphicsCanvas::GetPoint (int x, int y) inline override virtual
Get the color of a point in the graphics context.
On a 1:1 screen this corresponds to a pixel.
Todo:
check this
Parameters
x The X coordinate in the graphics context of the pixel
y The Y coordinate in the graphics context of the pixel
Returns
An IColor specifiying the color of the pixel at x,y
Implements IGraphics.
Definition at line 56 of file IGraphicsCanvas.h.
APIBitmap * IGraphicsCanvas::LoadAPIBitmap (const char * fileNameOrResID, int scale, EResourceLocation location, const char * ext) override protected virtual
/todo
Parameters
fileNameOrResID /todo
scale /todo
location /todo
ext /todo
Returns
APIBitmap* /todo
Implements IGraphics.
Definition at line 351 of file IGraphicsCanvas.cpp.
bool IGraphicsCanvas::LoadAPIFont (const char * fontID, const PlatformFontPtr & font) override protected virtual
/todo
Parameters
fontID /todo
font /todo
Returns
bool* /todo
Implements IGraphics.
Definition at line 415 of file IGraphicsCanvas.cpp.
void IGraphicsCanvas::PathArc (float cx, float cy, float r, float a1, float a2, EWinding winding) override virtual
/todo
Parameters
cx /todo
cy /todo
r /todo
a1 /todo
a2 /todo
Reimplemented from IGraphics.
Definition at line 132 of file IGraphicsCanvas.cpp.
void IGraphicsCanvas::PathCubicBezierTo (float c1x, float c1y, float c2x, float c2y, float x2, float y2) override virtual
/todo
Parameters
c1x /todo
c1y /todo
c2x /todo
c2y /todo
x2 /todo
y2 /todo
Reimplemented from IGraphics.
Definition at line 147 of file IGraphicsCanvas.cpp.
void IGraphicsCanvas::PathFill (const IPattern & pattern, const IFillOptions & options, const IBlend * pBlend) override virtual
/todo
Parameters
pattern /todo
options /todo
pBlend /todo
Reimplemented from IGraphics.
Definition at line 194 of file IGraphicsCanvas.cpp.
References BlendWeight(), IPattern::GetStop(), IMatrix::Invert(), IRECT::MH(), IRECT::MW(), IPattern::NStops(), and IMatrix::TransformPoint().
void IGraphicsCanvas::PathLineTo (float x, float y) override virtual
/todo
Parameters
x /todo
y /todo
Reimplemented from IGraphics.
Definition at line 142 of file IGraphicsCanvas.cpp.
void IGraphicsCanvas::PathMoveTo (float x, float y) override virtual
/todo
Parameters
x /todo
y /todo
Reimplemented from IGraphics.
Definition at line 137 of file IGraphicsCanvas.cpp.
void IGraphicsCanvas::PathQuadraticBezierTo (float cx, float cy, float x2, float y2) override virtual
/todo
Parameters
cx /todo
cy /todo
x2 /todo
y2 /todo
Reimplemented from IGraphics.
Definition at line 152 of file IGraphicsCanvas.cpp.
void IGraphicsCanvas::PathStroke (const IPattern & pattern, float thickness, const IStrokeOptions & options, const IBlend * pBlend) override virtual
/todo
Parameters
pattern /todo
thickness /todo
options /todo
pBlend /todo
Reimplemented from IGraphics.
Definition at line 157 of file IGraphicsCanvas.cpp.
The documentation for this class was generated from the following files:
IGraphicsCanvas.h
IGraphicsCanvas.cpp