iPlug2: IParam Class Reference
IParam Class Reference
IPlug's parameter class.
#include <IPlugParameter.h>
Classes
struct Shape
Base struct for parameter shaping.
struct ShapeExp
Exponential parameter shaping.
struct ShapeLinear
Linear parameter shaping.
struct ShapePowCurve
PowCurve parameter shaping.
Public Types
enum EParamType {
kTypeNone, kTypeBool, kTypeInt, kTypeEnum,
kTypeDouble
}
Defines types or parameter.
enum EParamUnit {
kUnitPercentage, kUnitSeconds, kUnitMilliseconds, kUnitSamples,
kUnitDB, kUnitLinearGain, kUnitPan, kUnitPhase,
kUnitDegrees, kUnitMeters, kUnitRate, kUnitRatio,
kUnitFrequency, kUnitOctaves, kUnitCents, kUnitAbsCents,
kUnitSemitones, kUnitMIDINote, kUnitMIDICtrlNum, kUnitBPM,
kUnitBeats, kUnitCustom
}
Used by AudioUnit plugins to determine the appearance of parameters, based on the kind of data they represent.
enum EDisplayType {
kDisplayLinear, kDisplayLog, kDisplayExp, kDisplaySquared,
kDisplaySquareRoot, kDisplayCubed, kDisplayCubeRoot
}
Used by AudioUnit plugins to determine the mapping of parameters.
enum EFlags {
kFlagsNone = 0, kFlagCannotAutomate = 0x1, kFlagStepped = 0x2, kFlagNegateDisplay = 0x4,
kFlagSignDisplay = 0x8, kFlagMeta = 0x10
}
Flags to determine characteristics of the parameter.
using DisplayFunc = std::function< void(double, WDL_String &)>
Public Member Functions
IParam (const IParam &)=delete
IParam & operator= (const IParam &)=delete
void InitBool (const char *name, bool defaultValue, const char *label="", int flags=0, const char *group="", const char *offText="off", const char *onText="on")
Initialize the parameter as boolean.
void InitEnum (const char *name, int defaultValue, int nEnums, const char *label="", int flags=0, const char *group="", const char *listItems=0,...)
/todo
void InitEnum (const char *name, int defaultValue, const std::initializer_list< const char * > &listItems, int flags=0, const char *group="")
/todo
void InitInt (const char *name, int defaultValue, int minVal, int maxVal, const char *label="", int flags=0, const char *group="")
/todo
void InitDouble (const char *name, double defaultVal, double minVal, double maxVal, double step, const char *label="", int flags=0, const char *group="", const Shape &shape=ShapeLinear(), EParamUnit unit=kUnitCustom, DisplayFunc displayFunc=nullptr)
/todo
void InitSeconds (const char *name, double defaultVal=1., double minVal=0., double maxVal=10., double step=0.1, int flags=0, const char *group="")
/todo
void InitMilliseconds (const char *name, double defaultVal=1., double minVal=0., double maxVal=100., int flags=0, const char *group="")
/todo
void InitFrequency (const char *name, double defaultVal=1000., double minVal=0.1, double maxVal=10000., double step=0.1, int flags=0, const char *group="")
/todo
void InitPitch (const char *name, int defaultVal=60, int minVal=0, int maxVal=128, int flags=0, const char *group="", bool middleCisC4=false)
/todo
void InitGain (const char *name, double defaultVal=0., double minVal=-70., double maxVal=24., double step=0.5, int flags=0, const char *group="")
/todo
void InitPercentage (const char *name, double defaultVal=0., double minVal=0., double maxVal=100., int flags=0, const char *group="")
/todo
void InitAngleDegrees (const char *name, double defaultVal=0., double minVal=0., double maxVal=360., int flags=0, const char *group="")
/todo
void Init (const IParam &p, const char *searchStr="", const char *replaceStr="", const char *newGroup="")
/todo
double StringToValue (const char *str) const
/todo
double Constrain (double value) const
Constrains the input value between mMin and mMax.
double ToNormalized (double nonNormalizedValue) const
Convert a real value to normalized value for this parameter.
double FromNormalized (double normalizedValue) const
Convert a normalized value to real value for this parameter.
void Set (double value)
Sets the parameter value.
void SetNormalized (double normalizedValue)
Sets the parameter value from a normalized range (usually coming from the linked IControl)
void SetString (const char *str)
/todo
void SetToDefault ()
/todo
void SetDefault (double value)
/todo
void SetDisplayText (double value, const char *str)
/todo
void SetLabel (const char *label)
Set the parameters label after creation.
double Value () const
Gets a readable value of the parameter.
bool Bool () const
Returns the parameter's value as a boolean.
int Int () const
double DBToAmp () const
/todo
double GetNormalized () const
/todo
void GetDisplayForHost (WDL_String &display, bool withDisplayText=true) const
/todo
void GetDisplayForHostWithLabel (WDL_String &display, bool withDisplayText=true) const
void GetDisplayForHost (double value, bool normalized, WDL_String &display, bool withDisplayText=true) const
/todo
const char * GetNameForHost () const
/todo
const char * GetLabelForHost () const
/todo
const char * GetGroupForHost () const
/todo
const char * GetCustomUnit () const
/todo
int NDisplayTexts () const
/todo
const char * GetDisplayText (double value) const
/todo
const char * GetDisplayTextAtIdx (int idx, double *pValue=nullptr) const
/todo
bool MapDisplayText (const char *str, double *pValue) const
/todo
EParamType Type () const
/todo
EParamUnit Unit () const
/todo
EDisplayType DisplayType () const
/todo
double GetDefault (bool normalized=false) const
/todo
double GetMin () const
double GetMax () const
void GetBounds (double &lo, double &hi) const
/todo
double GetRange () const
/todo
double GetStep () const
/todo
int GetDisplayPrecision () const
/todo
int GetFlags () const
/todo
bool GetCanAutomate () const
/todo
bool GetStepped () const
/todo
bool GetNegateDisplay () const
/todo
bool GetSignDisplay () const
/todo
bool GetMeta () const
/todo
void GetJSON (WDL_String &json, int idx) const
/todo
void PrintDetails () const
/todo
Detailed Description
IPlug's parameter class.
Definition at line 30 of file IPlugParameter.h.
Member Enumeration Documentation
enum IParam::EFlags
Flags to determine characteristics of the parameter.
Enumerator
kFlagStepped
Indicates that the parameter is not automatable.
kFlagNegateDisplay
Indicates that the parameter ???
kFlagSignDisplay
Indicates that the parameter should be displayed as a negative value.
kFlagMeta
Indicates that the parameter should be displayed as a signed value.
Definition at line 44 of file IPlugParameter.h.
enum IParam::EParamType
Defines types or parameter.
Definition at line 35 of file IPlugParameter.h.
Member Function Documentation
bool IParam::Bool () const inline
Returns the parameter's value as a boolean.
Returns
true if value >= 0.5, else otherwise
Definition at line 318 of file IPlugParameter.h.
Referenced by IPluginBase::DumpPresetSrcCode().
double IParam::Constrain (double value) const inline
Constrains the input value between mMin and mMax.
Parameters
value The input value to constrain
Returns
double The resulting constrained value
Definition at line 266 of file IPlugParameter.h.
References Clip(), and kFlagStepped.
Referenced by FromNormalized(), Set(), and ToNormalized().
double IParam::DBToAmp () const inline
/todo
Returns
double /todo
Definition at line 325 of file IPlugParameter.h.
References DBToAmp().
EDisplayType IParam::DisplayType () const inline
/todo
Returns
EDisplayType /todo
Definition at line 398 of file IPlugParameter.h.
double IParam::FromNormalized (double normalizedValue) const inline
Convert a normalized value to real value for this parameter.
Parameters
normalizedValue The normalized input value in the range 0. to 1.
Returns
The corresponding real value, for this parameter
Definition at line 279 of file IPlugParameter.h.
References Constrain().
Referenced by SetNormalized(), IVNumberBoxControl::SetValueFromDelegate(), and IVNumberBoxControl::SetValueFromUserInput().
void IParam::GetBounds (double & lo, double & hi) const
/todo
Parameters
lo /todo
hi /todo
Definition at line 375 of file IPlugParameter.cpp.
Referenced by GetMax(), and IPlugVST2::HostSpecificInit().
bool IParam::GetCanAutomate () const inline
/todo
Returns
true /todo
Definition at line 434 of file IPlugParameter.h.
const char* IParam::GetCustomUnit () const inline
/todo
Returns
const char* /todo
Definition at line 364 of file IPlugParameter.h.
References GetDisplayText(), GetDisplayTextAtIdx(), MapDisplayText(), and NDisplayTexts().
double IParam::GetDefault (bool normalized = false) const inline
/todo
Parameters
normalized /todo
Returns
double /todo
Definition at line 403 of file IPlugParameter.h.
References GetDefault(), and ToNormalized().
Referenced by GetDefault(), IVNumberBoxControl::OnInit(), and IControl::SetValueToDefault().
void IParam::GetDisplayForHost (WDL_String & display, bool withDisplayText = true) const inline
/todo
Parameters
display /todo
withDisplayText /todo
Definition at line 334 of file IPlugParameter.h.
References GetDisplayForHost(), GetGroupForHost(), GetLabelForHost(), and GetNameForHost().
Referenced by ICaptionControl::Draw(), GetDisplayForHost(), IGraphics::PromptUserInput(), and IVSwitchControl::SetDirty().
void IParam::GetDisplayForHost (double value, bool normalized, WDL_String & display, bool withDisplayText = true) const
/todo
Parameters
value /todo
normalized /todo
display /todo
withDisplayText /todo
Definition at line 257 of file IPlugParameter.cpp.
int IParam::GetDisplayPrecision () const inline
/todo
Returns
int /todo
Definition at line 426 of file IPlugParameter.h.
const char * IParam::GetDisplayText (double value) const
/todo
Parameters
value /todo
Returns
const char* /todo
Definition at line 322 of file IPlugParameter.cpp.
Referenced by GetCustomUnit(), and IGraphics::PromptUserInput().
const char * IParam::GetDisplayTextAtIdx (int idx, double * pValue = nullptr) const
/todo
Parameters
idx /todo
pValue /todo
Returns
const char* /todo
Definition at line 332 of file IPlugParameter.cpp.
Referenced by GetCustomUnit(), and Init().
int IParam::GetFlags () const inline
/todo
Returns
int /todo
Definition at line 430 of file IPlugParameter.h.
const char * IParam::GetGroupForHost () const
/todo
Returns
const char* /todo
Definition at line 312 of file IPlugParameter.cpp.
Referenced by IPluginBase::CopyParamValues(), IPluginBase::ForParamInGroup(), and GetDisplayForHost().
void IParam::GetJSON (WDL_String & json, int idx) const
/todo
Parameters
json /todo
idx /todo
Definition at line 381 of file IPlugParameter.cpp.
Referenced by GetMeta().
const char * IParam::GetLabelForHost () const
/todo
Returns
const char* /todo
Definition at line 307 of file IPlugParameter.cpp.
Referenced by ICaptionControl::Draw(), and GetDisplayForHost().
double IParam::GetMax () const inline
Returns
double /todo
Definition at line 409 of file IPlugParameter.h.
References GetBounds().
Referenced by IParam::ShapeExp::Init(), IParam::ShapePowCurve::NormalizedToValue(), IVNumberBoxControl::OnInit(), and IParam::ShapePowCurve::ValueToNormalized().
bool IParam::GetMeta () const inline
/todo
Returns
false /todo
Definition at line 450 of file IPlugParameter.h.
References GetJSON(), kFlagMeta, and PrintDetails().
double IParam::GetMin () const inline
Returns
double /todo
Definition at line 406 of file IPlugParameter.h.
Referenced by IParam::ShapeExp::Init(), IParam::ShapePowCurve::NormalizedToValue(), IVNumberBoxControl::OnInit(), and IParam::ShapePowCurve::ValueToNormalized().
const char * IParam::GetNameForHost () const
/todo
Returns
const char* /todo
Definition at line 302 of file IPlugParameter.cpp.
Referenced by GetDisplayForHost(), IVSwitchControl::OnInit(), IVTabSwitchControl::OnInit(), IVKnobControl::OnInit(), IVSliderControl::OnInit(), IGraphics::PromptUserInput(), IPluginBase::SerializeParams(), and IPluginBase::UnserializeParams().
bool IParam::GetNegateDisplay () const inline
/todo
Returns
false /todo
Definition at line 442 of file IPlugParameter.h.
References kFlagNegateDisplay.
double IParam::GetNormalized () const inline
/todo
Returns
double /todo
Definition at line 329 of file IPlugParameter.h.
References ToNormalized().
double IParam::GetRange () const inline
/todo
Returns
double /todo
Definition at line 418 of file IPlugParameter.h.
Referenced by ISwitchControlBase::OnInit().
bool IParam::GetSignDisplay () const inline
/todo
Returns
false /todo
Definition at line 446 of file IPlugParameter.h.
References kFlagSignDisplay.
double IParam::GetStep () const inline
/todo
Returns
double /todo
Definition at line 422 of file IPlugParameter.h.
bool IParam::GetStepped () const inline
/todo
Returns
true /todo
Definition at line 438 of file IPlugParameter.h.
References kFlagStepped.
void IParam::Init (const IParam & p, const char * searchStr = "", const char * replaceStr = "", const char * newGroup = "")
/todo
Parameters
p /todo
searchStr /todo
replaceStr /todo
newGroup /todo
Definition at line 214 of file IPlugParameter.cpp.
References GetDisplayTextAtIdx(), NDisplayTexts(), and Type().
void IParam::InitAngleDegrees (const char * name, double defaultVal = 0., double minVal = 0., double maxVal = 360., int flags = 0, const char * group = "")
/todo
Parameters
name /todo
defaultVal /todo
minVal /todo
maxVal /todo
flags /todo
group /todo
Definition at line 209 of file IPlugParameter.cpp.
Referenced by IParam::ShapeExp::GetDisplayType().
void IParam::InitBool (const char * name, bool defaultValue, const char * label = "", int flags = 0, const char * group = "", const char * offText = "off", const char * onText = "on")
Initialize the parameter as boolean.
Parameters
name The parameter's name
defaultValue The default value of the parameter
label The parameter's label
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
offText The display text when the parameter value == 0.
onText The display text when the parameter value == 1.
Definition at line 92 of file IPlugParameter.cpp.
Referenced by IParam::ShapeExp::GetDisplayType().
void IParam::InitDouble (const char * name, double defaultVal, double minVal, double maxVal, double step, const char * label = "", int flags = 0, const char * group = "", const Shape & shape = ShapeLinear(), EParamUnit unit = kUnitCustom, DisplayFunc displayFunc = nullptr)
/todo
Parameters
name /todo
defaultVal /todo
minVal /todo
maxVal /todo
step /todo
label /todo
flags /todo
group /todo
shape /todo
unit /todo
displayFunc /todo
Definition at line 140 of file IPlugParameter.cpp.
References IParam::Shape::Clone().
Referenced by IParam::ShapeExp::GetDisplayType().
void IParam::InitEnum (const char * name, int defaultValue, int nEnums, const char * label = "", int flags = 0, const char * group = "", const char * listItems = 0, ...)
/todo
Parameters
name /todo
defaultValue /todo
nEnums /todo
label /todo
flags /todo
group /todo
listItems /todo
... /todo
Definition at line 102 of file IPlugParameter.cpp.
Referenced by IParam::ShapeExp::GetDisplayType().
void IParam::InitEnum (const char * name, int defaultValue, const std::initializer_list< const char * > & listItems, int flags = 0, const char * group = "")
/todo
Parameters
name /todo
defaultValue /todo
listItems /todo
label /todo
flags /todo
group /todo
Definition at line 120 of file IPlugParameter.cpp.
void IParam::InitFrequency (const char * name, double defaultVal = 1000., double minVal = 0.1, double maxVal = 10000., double step = 0.1, int flags = 0, const char * group = "")
/todo
Parameters
name /todo
defaultVal /todo
minVal /todo
maxVal /todo
step /todo
flags /todo
group /todo
Definition at line 173 of file IPlugParameter.cpp.
Referenced by IParam::ShapeExp::GetDisplayType().
void IParam::InitGain (const char * name, double defaultVal = 0., double minVal = -70., double maxVal = 24., double step = 0.5, int flags = 0, const char * group = "")
/todo
Parameters
name /todo
defaultVal /todo
minVal /todo
maxVal /todo
step /todo
flags /todo
group /todo
Definition at line 199 of file IPlugParameter.cpp.
Referenced by IParam::ShapeExp::GetDisplayType().
void IParam::InitInt (const char * name, int defaultValue, int minVal, int maxVal, const char * label = "", int flags = 0, const char * group = "")
/todo
Parameters
name /todo
defaultValue /todo
minVal /todo
maxVal /todo
label /todo
flags /todo
group /todo
Definition at line 133 of file IPlugParameter.cpp.
Referenced by IParam::ShapeExp::GetDisplayType().
void IParam::InitMilliseconds (const char * name, double defaultVal = 1., double minVal = 0., double maxVal = 100., int flags = 0, const char * group = "")
/todo
Parameters
name /todo
defaultVal /todo
minVal /todo
maxVal /todo
step /todo
flags /todo
group /todo
Definition at line 183 of file IPlugParameter.cpp.
Referenced by IParam::ShapeExp::GetDisplayType().
void IParam::InitPercentage (const char * name, double defaultVal = 0., double minVal = 0., double maxVal = 100., int flags = 0, const char * group = "")
/todo
Parameters
name /todo
defaultVal /todo
minVal /todo
maxVal /todo
flags /todo
group /todo
Definition at line 204 of file IPlugParameter.cpp.
Referenced by IParam::ShapeExp::GetDisplayType().
void IParam::InitPitch (const char * name, int defaultVal = 60, int minVal = 0, int maxVal = 128, int flags = 0, const char * group = "", bool middleCisC4 = false)
/todo
Parameters
name /todo
defaultVal /todo
minVal /todo
maxVal /todo
flags /todo
group /todo
Definition at line 188 of file IPlugParameter.cpp.
References MidiNoteName().
Referenced by IParam::ShapeExp::GetDisplayType().
void IParam::InitSeconds (const char * name, double defaultVal = 1., double minVal = 0., double maxVal = 10., double step = 0.1, int flags = 0, const char * group = "")
/todo
Parameters
name /todo
defaultVal /todo
minVal /todo
maxVal /todo
step /todo
flags /todo
group /todo
Definition at line 178 of file IPlugParameter.cpp.
Referenced by IParam::ShapeExp::GetDisplayType().
int IParam::Int () const inline
Returns
Current value of the parameter as an integer
Definition at line 321 of file IPlugParameter.h.
Referenced by IPluginBase::DumpPresetSrcCode().
bool IParam::MapDisplayText (const char * str, double * pValue) const
/todo
Parameters
str /todo
pValue /todo
Returns
true /todo
false /todo
Definition at line 339 of file IPlugParameter.cpp.
Referenced by GetCustomUnit().
int IParam::NDisplayTexts () const
/todo
Returns
int /todo
Definition at line 317 of file IPlugParameter.cpp.
Referenced by GetCustomUnit(), Init(), and IGraphics::PromptUserInput().
void IParam::Set (double value) inline
Sets the parameter value.
Parameters
value Value to be set. Will be stepped and clamped between mMin and mMax
Definition at line 286 of file IPlugParameter.h.
References Constrain().
Referenced by SetNormalized(), and IPluginBase::UnserializeParams().
void IParam::SetDefault (double value) inline
/todo
Parameters
value /todo
Definition at line 301 of file IPlugParameter.h.
References SetDisplayText(), and SetToDefault().
void IParam::SetDisplayText (double value, const char * str)
/todo
Parameters
value /todo
str /todo
Definition at line 248 of file IPlugParameter.cpp.
Referenced by SetDefault().
void IParam::SetLabel (const char * label) inline
Set the parameters label after creation.
WARNING: if this is called after the host has queried plugin parameters, the host may display the label as it was previously
Parameters
label /todo
Definition at line 310 of file IPlugParameter.h.
void IParam::SetNormalized (double normalizedValue) inline
Sets the parameter value from a normalized range (usually coming from the linked IControl)
Parameters
normalizedValue The expected normalized value between 0. and 1.
Definition at line 290 of file IPlugParameter.h.
References FromNormalized(), and Set().
Referenced by IPluginBase::RandomiseParamValues(), and IEditorDelegate::SendParameterValueFromUI().
void IParam::SetString (const char * str) inline
/todo
Parameters
str /todo
Definition at line 294 of file IPlugParameter.h.
References StringToValue().
double IParam::StringToValue (const char * str) const
/todo
Parameters
str /todo
Returns
double /todo
Definition at line 353 of file IPlugParameter.cpp.
Referenced by IParam::ShapeExp::GetDisplayType(), IPlugVST2::HostSpecificInit(), IGraphics::SetControlValueAfterTextEdit(), and SetString().
double IParam::ToNormalized (double nonNormalizedValue) const inline
Convert a real value to normalized value for this parameter.
Parameters
nonNormalizedValue The real input value
Returns
The corresponding normalized value, for this parameter
Definition at line 271 of file IPlugParameter.h.
References Clip(), and Constrain().
Referenced by GetDefault(), GetNormalized(), IPlugVST2::HostSpecificInit(), IGraphics::SetControlValueAfterTextEdit(), and IVNumberBoxControl::SetValueFromUserInput().
EParamType IParam::Type () const inline
/todo
Returns
EParamType /todo
Definition at line 390 of file IPlugParameter.h.
Referenced by IPluginBase::DumpPresetSrcCode(), IPlugVST2::HostSpecificInit(), Init(), IPluginBase::MakePreset(), IPluginBase::MakePresetFromNamedParams(), ITextEntryControl::OnKeyDown(), and IGraphics::PromptUserInput().
EParamUnit IParam::Unit () const inline
/todo
Returns
EParamUnit /todo
Definition at line 394 of file IPlugParameter.h.
double IParam::Value () const inline
Gets a readable value of the parameter.
Returns
Current value of the parameter
Definition at line 314 of file IPlugParameter.h.
Referenced by IPluginBase::CloneParamRange(), IPluginBase::CopyParamValues(), IPluginBase::DumpPresetSrcCode(), IPluginBase::SerializeParams(), and IPluginBase::UnserializeParams().
The documentation for this class was generated from the following files:
IPlugParameter.h
IPlugParameter.cpp