iPlug2: IControl Class Reference
IControl Class Reference abstract
IGraphics::IControls::BaseControls
The lowest level base class of an IGraphics control.
#include <IControl.h>
Public Member Functions
IControl (const IRECT &bounds, int paramIdx=kNoParameter, IActionFunction actionFunc=nullptr)
Constructor.
IControl (const IRECT &bounds, const std::initializer_list< int > &params, IActionFunction actionFunc=nullptr)
Constructor (range of parameters)
IControl (const IRECT &bounds, IActionFunction actionFunc)
Constructor (no paramIdx)
IControl (const IControl &)=delete
void operator= (const IControl &)=delete
virtual ~IControl ()
Destructor.
virtual void OnMouseDown (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse down event on this control.
virtual void OnMouseUp (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse up event on this control.
virtual void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod)
Implement this method to respond to a mouse drag event on this control.
virtual void OnMouseDblClick (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse double click event on this control.
virtual void OnMouseWheel (float x, float y, const IMouseMod &mod, float d)
Implement this method to respond to a mouse wheel event on this control.
virtual bool OnKeyDown (float x, float y, const IKeyPress &key)
Implement this method to respond to a key down event on this control.
virtual bool OnKeyUp (float x, float y, const IKeyPress &key)
Implement this method to respond to a key up event on this control.
virtual void OnMouseOver (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouseover event on this control.
virtual void OnMouseOut ()
Implement this method to respond to a mouseout event on this control.
virtual void OnTouchCancelled (float x, float y, const IMouseMod &mod)
Implement this method to respond to a touch cancel event on this control.
virtual void OnDrop (const char *str)
Implement to do something when something was drag 'n dropped onto this control.
virtual void OnRescale ()
Implement to do something when graphics is scaled globally (e.g.
virtual void OnResize ()
Called when IControl is constructed or resized using SetRect().
virtual void OnInit ()
Called just prior to when the control is attached, after its delegate and graphics member variable set.
virtual void OnAttached ()
Called after the control has been attached, and its delegate and graphics member variable set.
virtual void OnMsgFromDelegate (int msgTag, int dataSize, const void *pData)
Implement to receive messages sent to the control, see IEditorDelegate:SendControlMsgFromDelegate()
virtual void OnMidi (const IMidiMsg &msg)
Implement to receive MIDI messages sent to the control if mWantsMidi == true, see IEditorDelegate:SendMidiMsgFromDelegate()
virtual bool OnGesture (const IGestureInfo &info)
virtual void CreateContextMenu (IPopupMenu &contextMenu)
Called by default when the user right clicks a control.
virtual void OnPopupMenuSelection (IPopupMenu *pSelectedMenu, int valIdx)
Implement this method to handle popup menu selection after IGraphics::CreatePopupMenu/IControl::PromptUserInput.
virtual void OnTextEntryCompletion (const char *str, int valIdx)
Implement this method to handle text input after IGraphics::CreateTextEntry/IControl::PromptUserInput.
virtual void OnContextSelection (int itemSelected)
Implement this to respond to a menu selection from CreateContextMenu();.
virtual void Draw (IGraphics &g)=0
Draw the control to the graphics context.
virtual void DrawPTHighlight (IGraphics &g)
Implement this to customise how a colored highlight is drawn on the control in ProTools (AAX format only), when a control is linked to a parameter that is automated.
void PromptUserInput (int valIdx=0)
Call this method in response to a mouse event to create an edit box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter)
void PromptUserInput (const IRECT &bounds, int valIdx=0)
Create a text entry box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter), specifying the bounds.
void SetActionFunction (IActionFunction actionFunc)
Set an Action Function for this control.
void SetAnimationEndActionFunction (IActionFunction actionFunc)
Set an Action Function to be called at the end of an animation.
void SetTooltip (const char *str)
Set a tooltip for the control.
const char * GetTooltip () const
int GetParamIdx (int valIdx=0) const
Get the index of a parameter that the control is linked to Normaly controls are either linked to a single parameter or no parameter but some may be linked to multiple parameters.
void SetParamIdx (int paramIdx, int valIdx=0)
Set the index of a parameter that the control is linked to.
int LinkedToParam (int paramIdx) const
Check if the control is linked to a particular parameter.
int NVals () const
virtual int GetValIdxForPos (float x, float y) const
Check to see which of the control's values relates to this x and y coordinate.
const IParam * GetParam (int valIdx=0) const
Get a const pointer to the IParam object (owned by the editor delegate class), associated with this control.
virtual void SetValueFromDelegate (double value, int valIdx=0)
Set the control's value from the delegate This method is called from the class implementing the IEditorDelegate interface in order to update a control's value members and set it to be marked dirty for redraw.
virtual void SetValueFromUserInput (double value, int valIdx=0)
Set the control's value after user input.
virtual void SetValueToDefault (int valIdx=kNoValIdx)
Set one or all of the control's values to the default value of the associated parameter.
virtual void SetValue (double value, int valIdx=0)
Set one of the control's values.
double GetValue (int valIdx=0) const
Get the control's value.
void SetGroup (const char *groupName)
Assign the control to a control group.
const char * GetGroup () const
Get the group that the control belongs to, if any.
const IText & GetText () const
Get the Text object for the control.
void SetText (const IText &txt)
Set the Text object typically used to determine font/layout/size etc of the main text in a control.
void SetBlend (const IBlend &blend)
Set the Blend for this control.
IBlend GetBlend () const
Get the Blend for this control.
int GetTextEntryLength () const
Get the max number of characters that are allowed in text entry.
void SetTextEntryLength (int len)
Set the max number of characters that are allowed in text entry.
const IRECT & GetRECT () const
Get the rectangular draw area for this control, within the graphics context.
void SetRECT (const IRECT &bounds)
Set the rectangular draw area for this control, within the graphics context.
const IRECT & GetTargetRECT () const
Get the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetRECT (const IRECT &bounds)
Set the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetAndDrawRECTs (const IRECT &bounds)
Set BOTH the draw rect and the target area, within the graphics context for this control.
virtual void SetPosition (float x, float y)
Set the position of the control, preserving the width and height.
virtual void SetSize (float w, float h)
Set the size of the control, preserving the current position.
void SetPTParameterHighlight (bool isHighlighted, int color)
Used internally by the AAX wrapper view interface to set the control parmeter highlight.
bool GetMouseDblAsSingleClick () const
Get double click as single click By default, mouse double click has its own handler.
virtual void Hide (bool hide)
Shows or hides the IControl.
bool IsHidden () const
virtual void SetDisabled (bool disable)
Sets disabled mode for the control, the default implementation modifies the mBlend member.
bool IsDisabled () const
void SetMouseOverWhenDisabled (bool allow)
Specify whether the control should respond to mouse overs when disabled.
void SetMouseEventsWhenDisabled (bool allow)
Specify whether the control should respond to other mouse events when disabled.
bool GetMouseOverWhenDisabled () const
bool GetMouseEventsWhenDisabled () const
bool GetIgnoreMouse () const
virtual bool IsHit (float x, float y) const
Hit test the control.
virtual void SetDirty (bool triggerAction=true, int valIdx=kNoValIdx)
Mark the control as dirty, i.e.
virtual void SetClean ()
void Animate ()
virtual bool IsDirty ()
Called at each display refresh by the IGraphics draw loop, after IControl::Animate(), to determine if the control is marked as dirty.
void DisablePrompt (bool disable)
Disable/enable right-clicking the control to prompt for user input /todo check this.
virtual void OnGUIIdle ()
This is an idle call from the GUI thread, only active if USE_IDLE_CALLS is defined.
void SetTag (int tag)
Set the control's tag.
int GetTag () const
Get the control's tag.
void SetWantsMidi (bool enable=true)
Specify whether this control wants to know about MIDI messages sent to the UI.
bool GetWantsMidi () const
void SetWantsMultiTouch (bool enable=true)
Specify whether this control supports multiple touches.
bool GetWantsMultiTouch () const
IControl * AttachGestureRecognizer (EGestureType type, IGestureFunc func)
Add a IGestureFunc that should be triggered in response to a certain type of gesture.
bool GetWantsGestures () const
EGestureType GetLastGesture () const
IGEditorDelegate * GetDelegate ()
Gets a pointer to the class implementing the IEditorDelegate interface that handles parameter changes from this IGraphics instance.
void SetDelegate (IGEditorDelegate &dlg)
Used internally to set the mDelegate (and mGraphics) variables.
IGraphics * GetUI ()
const IGraphics * GetUI () const
bool GetMouseIsOver () const
virtual void SnapToMouse (float x, float y, EDirection direction, const IRECT &bounds, int valIdx=-1, double minClip=0., double maxClip=1.)
Set control value based on x, y position within a rectangle.
virtual void OnEndAnimation ()
void StartAnimation (int duration)
void SetAnimation (IAnimationFunction func)
Set the animation function.
void SetAnimation (IAnimationFunction func, int duration)
Set the animation function and starts it.
IAnimationFunction GetAnimationFunction ()
/todo
IAnimationFunction GetActionFunction ()
/todo
double GetAnimationProgress () const
/todo
Milliseconds GetAnimationDuration () const
/todo
Protected Member Functions
template<typename T , typename... Args>
void ForValIdx (int valIdx, T func, Args...args)
A helper template function to call a method for an individual value, or for all values.
void SetNVals (int nVals)
Protected Attributes
int mTag = kNoTag
IRECT mRECT
IRECT mTargetRECT
WDL_String mGroup
Controls can be grouped for hiding and showing panels.
IText mText
IBlend mBlend
int mTextEntryLength = DEFAULT_TEXT_ENTRY_LEN
bool mDirty = true
bool mHide = false
bool mDisabled = false
bool mDisablePrompt = true
bool mDblAsSingleClick = false
bool mMouseOverWhenDisabled = false
bool mMouseEventsWhenDisabled = false
bool mIgnoreMouse = false
bool mWantsMidi = false
bool mWantsMultiTouch = false
bool mMouseIsOver = false
if mGraphics::mHandleMouseOver = true, this will be true when the mouse is over control.
WDL_String mTooltip
IColor mPTHighlightColor = COLOR_RED
bool mPTisHighlighted = false
Detailed Description
The lowest level base class of an IGraphics control.
A control is anything on the GUI
Definition at line 42 of file IControl.h.
Constructor & Destructor Documentation
IControl::IControl (const IRECT & bounds, int paramIdx = kNoParameter, IActionFunction actionFunc = nullptr)
Constructor.
Creates an IControl NOTE: An IControl does not know about the delegate or graphics context to which it belongs in the constructor If you need to do something once those things are known, see IControl::OnInit()
Parameters
bounds The rectangular area that the control occupies
paramIdx If this is > -1 (kNoParameter) this control will be associated with a plugin parameter
actionFunc pass in a lambda function to provide custom functionality when the control "action" happens (usually mouse down).
Definition at line 82 of file IControl.cpp.
Referenced by IVPlotControl::AddPlotFunc(), GetAnimationProgress(), IBitmapControl::IBitmapControl(), IButtonControlBase::OnMouseDown(), IVRangeSliderControl::OnMouseDrag(), IKnobControlBase::OnMouseWheel(), IVGroupControl::OnResize(), and PlaceHolder::OnResize().
IControl::IControl (const IRECT & bounds, const std::initializer_list< int > & params, IActionFunction actionFunc = nullptr)
Constructor (range of parameters)
Creates an IControl which is linked to multiple parameters NOTE: An IControl does not know about the delegate or graphics context to which it belongs in the constructor If you need to do something once those things are know, see IControl::OnInit()
Parameters
bounds The rectangular area that the control occupies
params An initializer list of valid integer parameter indexes
actionFunc pass in a lambda function to provide custom functionality when the control "action" happens (usually mouse down).
Definition at line 90 of file IControl.cpp.
IControl::IControl (const IRECT & bounds, IActionFunction actionFunc)
Constructor (no paramIdx)
Creates an IControl which is not linked to a parameter NOTE: An IControl does not know about the delegate or graphics context to which it belongs in the constructor If you need to do something once those things are known, see IControl::OnInit()
Parameters
bounds The rectangular area that the control occupies
actionFunc pass in a lambda function to provide custom functionality when the control "action" happens (usually mouse down).
Definition at line 101 of file IControl.cpp.
virtual IControl::~IControl () inline virtual
Destructor.
Clean up any resources that your control owns.
Definition at line 79 of file IControl.h.
References OnMouseDown().
Member Function Documentation
IControl * IControl::AttachGestureRecognizer (EGestureType type, IGestureFunc func)
Add a IGestureFunc that should be triggered in response to a certain type of gesture.
Parameters
type The type of gesture to recognize on this control
func the function to trigger
Definition at line 316 of file IControl.cpp.
References IGraphics::AttachGestureRecognizer(), and GetUI().
Referenced by IGraphics::AttachGestureRecognizerToRegion(), GetWantsMultiTouch(), and TestGesturesControl::OnInit().
virtual void IControl::CreateContextMenu (IPopupMenu & contextMenu) inline virtual
Called by default when the user right clicks a control.
If IGRAPHICS_NO_CONTEXT_MENU is enabled as a preprocessor macro right clicking control will mean IControl::CreateContextMenu() and IControl::OnContextSelection() do not function on right clicking control. VST3 provides contextual menu support which is hard wired to right click controls by default. You can add custom items to the menu by implementing IControl::CreateContextMenu() and handle them in IControl::OnContextSelection(). In non-VST 3 hosts right clicking will still create the menu, but it will not feature entries added by the host.
Definition at line 166 of file IControl.h.
References OnPopupMenuSelection().
Referenced by IGraphics::PopupHostContextMenuForParam().
void IControl::DisablePrompt (bool disable) inline
Disable/enable right-clicking the control to prompt for user input /todo check this.
Parameters
disable true
Definition at line 398 of file IControl.h.
Referenced by IVRadioButtonControl::GetButtonForPoint(), and IVKnobControl::OnInit().
virtual void IControl::Draw (IGraphics & g) pure virtual
Draw the control to the graphics context.
Parameters
g The graphics context to which this control belongs.
Implemented in PlaceHolder, ICaptionControl, IURLControl, ITextControl, ISVGControl, IBitmapControl, ILambdaControl, IPanelControl, IBTextControl, IBSliderControl, IBKnobRotaterControl, IBKnobControl, IBSwitchControl, IBButtonControl, ISVGSliderControl, ISVGSwitchControl, ISVGButtonControl, ISVGKnobControl, IVColorSwatchControl, IVPanelControl, IVGroupControl, IVPlotControl, IVXYPadControl, IVRangeSliderControl, IVSliderControl, IVKeyboardControl, TestGLControl, IVKnobControl, IGraphicsLiveEdit, IVTabSwitchControl, IBubbleControl, ILEDControl< MAXNC, QUEUE_SIZE >, TestKeyboardControl, IVSlideSwitchControl, TestMPSControl, IVSwitchControl, IFPSDisplayControl, IVMultiSliderControl< MAXNC >, IPopupMenuControl, IVDisplayControl, IVButtonControl, IVNumberBoxControl, TestAnimationControl, ITextEntryControl, IVScopeControl< MAXNC, MAXBUF >, IVLabelControl, TestColorControl, TestDirBrowseControl, IVPresetManagerControl, IVMeterControl< MAXNC >, TestTextSizeControl, IColorPickerControl, ICornerResizerControl, TestTextOrientationControl, TestBezierControl, TestFontControl, TestBlendControl, TestGesturesControl, TestArcControl, TestDropShadowControl, TestFlexBoxControl, TestMTControl, TestSVGControl, TestGradientControl, TestImageControl, TestMultiPathControl, TestSizeControl, TestTextControl, TestCursorControl, TestDrawContextControl, GFXLabelControl, TestLayerControl, TestPolyControl, TestShadowGradientControl, and TestMaskControl.
Referenced by IGraphics::BeginFrame(), and OnContextSelection().
void IControl::DrawPTHighlight (IGraphics & g) virtual
Implement this to customise how a colored highlight is drawn on the control in ProTools (AAX format only), when a control is linked to a parameter that is automated.
Parameters
g The graphics context to which this control belongs.
Definition at line 394 of file IControl.cpp.
References IGraphics::FillCircle().
Referenced by IGraphics::BeginFrame(), and OnContextSelection().
template<typename T , typename... Args> void IControl::ForValIdx (int valIdx, T func, Args... args) inline protected
A helper template function to call a method for an individual value, or for all values.
Parameters
valIdx If this is > kNoValIdx execute the function for an individual value. If equal to kNoValIdx call the function for all values
func A function that takes a single integer argument, the valIdx
Todo:
Parameters
args Arguments to the function
Definition at line 505 of file IControl.h.
References NVals().
Referenced by SetDirty(), SetValueToDefault(), and SnapToMouse().
IGEditorDelegate* IControl::GetDelegate () inline
Gets a pointer to the class implementing the IEditorDelegate interface that handles parameter changes from this IGraphics instance.
If you need to call other methods on that class, you can use static_cast<PLUG_CLASS_NAME>(GetDelegate();
Returns
The class implementing the IEditorDelegate interface that handles communication to/from from this IGraphics instance.
Definition at line 436 of file IControl.h.
Referenced by IGraphics::AttachBackground(), IGraphics::AttachBubbleControl(), IGraphics::AttachControl(), IGraphics::AttachCornerResizer(), IGraphics::AttachPanelBackground(), IGraphics::AttachPopupMenuControl(), IGraphics::AttachTextEntryControl(), IVKeyboardControl::Draw(), IGraphics::EnableLiveEdit(), IVNumberBoxControl::OnMouseDown(), IVNumberBoxControl::OnMouseUp(), IGraphics::PopupHostContextMenuForParam(), IGraphics::Resize(), SetDirty(), IGraphics::SetQwertyMidiKeyHandlerFunc(), IGraphics::SetScreenScale(), IGraphics::SetStrictDrawing(), and IGraphics::ShowFPSDisplay().
const char* IControl::GetGroup () const inline
Get the group that the control belongs to, if any.
Returns
A CString indicating the control group that this control belongs to (may be empty)
Definition at line 277 of file IControl.h.
References mGroup.
Referenced by IGraphics::ForControlInGroup().
bool IControl::GetIgnoreMouse () const inline
Returns
true if the control ignores mouse events
Definition at line 372 of file IControl.h.
Referenced by IGraphics::ReleaseMouseCapture().
EGestureType IControl::GetLastGesture () const inline
Returns
the last recognized gesture
Definition at line 431 of file IControl.h.
bool IControl::GetMouseDblAsSingleClick () const inline
Get double click as single click By default, mouse double click has its own handler.
A control can set mDblAsSingleClick to true which maps double click to single click for this control (and also causes the mouse to be captured by the control on double click).
Returns
/c true if double clicks should be mapped to single clicks
Definition at line 341 of file IControl.h.
References Hide().
Referenced by IGraphics::OnMouseDblClick().
bool IControl::GetMouseEventsWhenDisabled () const inline
Returns
true if the control responds to other mouse events when disabled
Definition at line 369 of file IControl.h.
Referenced by IGraphics::ReleaseMouseCapture().
bool IControl::GetMouseOverWhenDisabled () const inline
Returns
true if the control responds to mouse overs when disabled
Definition at line 366 of file IControl.h.
Referenced by IGraphics::ReleaseMouseCapture().
const IParam * IControl::GetParam (int valIdx = 0) const
Get a const pointer to the IParam object (owned by the editor delegate class), associated with this control.
Returns
const pointer to an IParam or nullptr if the control is not associated with a parameter
Definition at line 120 of file IControl.cpp.
References IEditorDelegate::GetParam(), and GetParamIdx().
Referenced by ICaptionControl::Draw(), GetValIdxForPos(), IVNumberBoxControl::OnInit(), IVSwitchControl::OnInit(), IVTabSwitchControl::OnInit(), IVKnobControl::OnInit(), IVSliderControl::OnInit(), ISwitchControlBase::OnInit(), IVNumberBoxControl::OnMouseDown(), IVNumberBoxControl::OnMouseUp(), OnPopupMenuSelection(), ICaptionControl::OnResize(), PromptUserInput(), IGraphics::PromptUserInput(), IVSwitchControl::SetDirty(), IVKnobControl::SetDirty(), IVSliderControl::SetDirty(), IVNumberBoxControl::SetValueFromDelegate(), IVNumberBoxControl::SetValueFromUserInput(), SetValueToDefault(), ShowBubbleHorizontalActionFunc(), and ShowBubbleVerticalActionFunc().
int IControl::GetParamIdx (int valIdx = 0) const
Get the index of a parameter that the control is linked to Normaly controls are either linked to a single parameter or no parameter but some may be linked to multiple parameters.
Parameters
valIdx An index to choose which of the controls linked parameters to retrieve. NOTE: since controls usually have only 1 parameter you can omit this argument and use the default index of 0
Returns
Parameter index, or kNoParameter if there is no parameter linked with this control at valIdx
Definition at line 108 of file IControl.cpp.
References NVals().
Referenced by IGraphics::CreateTextEntry(), GetParam(), IGraphics::GetParamIdxForPTAutomation(), GetTooltip(), ISwitchControlBase::OnInit(), IVNumberBoxControl::OnMouseDown(), IVNumberBoxControl::OnMouseUp(), OnPopupMenuSelection(), PromptUserInput(), IGEditorDelegate::SendParameterValueFromDelegate(), SetDirty(), IGraphics::SetStrictDrawing(), and IGraphics::UpdatePeers().
const IRECT& IControl::GetRECT () const inline
Get the rectangular draw area for this control, within the graphics context.
Returns
The control's bounds
Definition at line 304 of file IControl.h.
Referenced by IGraphics::BeginFrame(), IVNumberBoxControl::Draw(), IGraphicsLiveEdit::Draw(), IGraphics::IsDirty(), ITextEntryControl::OnKeyDown(), IVNumberBoxControl::OnMouseDblClick(), IGraphicsLiveEdit::OnMouseDown(), IGraphicsLiveEdit::OnMouseDrag(), IGraphicsLiveEdit::OnMouseOver(), IGraphicsLiveEdit::OnMouseUp(), IVNumberBoxControl::OnResize(), IGraphics::ReleaseMouseCapture(), IBubbleControl::SetMaxBounds(), ShowBubbleHorizontalActionFunc(), ShowBubbleVerticalActionFunc(), and IGraphics::StartLayer().
int IControl::GetTag () const inline
Get the control's tag.
See also
Control Tags
Definition at line 408 of file IControl.h.
Referenced by IGraphics::GetControlWithTag(), IGEditorDelegate::SendControlMsgFromDelegate(), and IGEditorDelegate::SendControlValueFromDelegate().
const IRECT& IControl::GetTargetRECT () const inline
Get the rectangular mouse tracking target area, within the graphics context for this control.
Returns
The control's target bounds within the graphics context
Definition at line 312 of file IControl.h.
Referenced by IGraphicsLiveEdit::OnMouseDown().
const IText& IControl::GetText () const inline
Get the Text object for the control.
Returns
const IText& The control's mText object, typically used to determine font/layout/size etc of the main text in a control.
Definition at line 281 of file IControl.h.
Referenced by ITextEntryControl::OnKeyDown(), and IGraphics::PromptUserInput().
int IControl::GetTextEntryLength () const inline
Get the max number of characters that are allowed in text entry.
Returns
int The max number of characters allowed in text entry
Definition at line 296 of file IControl.h.
Referenced by IGraphics::CreateTextEntry().
const char* IControl::GetTooltip () const inline
Returns
Currently set tooltip text
Definition at line 213 of file IControl.h.
References GetParamIdx(), LinkedToParam(), and SetParamIdx().
IGraphics* IControl::GetUI () inline
Returns
A pointer to the IGraphics context that owns this control
Definition at line 449 of file IControl.h.
Referenced by AttachGestureRecognizer(), IPopupMenuControl::CalculateMenuPanels(), IPopupMenuControl::CreatePopupMenu(), ICornerResizerControl::Draw(), ITextControl::Draw(), IBubbleControl::IBubbleControl(), IVPresetManagerControl::OnAttached(), IVNumberBoxControl::OnAttached(), TestDropShadowControl::OnDrop(), TestImageControl::OnDrop(), TestSVGControl::OnDrop(), IGraphicsLiveEdit::OnInit(), TestTextControl::OnMouseDblClick(), ICornerResizerControl::OnMouseDblClick(), IVNumberBoxControl::OnMouseDblClick(), PlaceHolder::OnMouseDblClick(), TestCursorControl::OnMouseDown(), TestImageControl::OnMouseDown(), ICornerResizerControl::OnMouseDown(), IGraphicsLiveEdit::OnMouseDown(), TestSVGControl::OnMouseDown(), TestPolyControl::OnMouseDown(), TestArcControl::OnMouseDown(), TestDirBrowseControl::OnMouseDown(), IVNumberBoxControl::OnMouseDown(), IVXYPadControl::OnMouseDown(), IVColorSwatchControl::OnMouseDown(), IKnobControlBase::OnMouseDown(), ISliderControlBase::OnMouseDown(), IURLControl::OnMouseDown(), IGraphicsLiveEdit::OnMouseDrag(), TestCursorControl::OnMouseOut(), ICornerResizerControl::OnMouseOut(), IURLControl::OnMouseOut(), ICornerResizerControl::OnMouseOver(), IGraphicsLiveEdit::OnMouseOver(), IURLControl::OnMouseOver(), TestPolyControl::OnMouseUp(), TestArcControl::OnMouseUp(), IGraphicsLiveEdit::OnMouseUp(), IVNumberBoxControl::OnMouseUp(), IVXYPadControl::OnMouseUp(), IKnobControlBase::OnMouseUp(), ISliderControlBase::OnMouseUp(), IGraphicsLiveEdit::OnPopupMenuSelection(), ICornerResizerControl::OnRescale(), IBButtonControl::OnRescale(), IBSwitchControl::OnRescale(), IBKnobControl::OnRescale(), IBSliderControl::OnRescale(), IBTextControl::OnRescale(), IBitmapControl::OnRescale(), TestSizeControl::OnResize(), IGraphicsLiveEdit::OnResize(), IVGroupControl::OnResize(), PromptUserInput(), SetDirty(), IBubbleControl::SetMaxBounds(), SetValueFromDelegate(), ShowBubbleHorizontalActionFunc(), ShowBubbleVerticalActionFunc(), and SplashClickActionFunc().
const IGraphics* IControl::GetUI () const inline
Returns
A const pointer to the IGraphics context that owns this control
Definition at line 452 of file IControl.h.
References mMouseIsOver, SnapToMouse(), and StartAnimation().
virtual int IControl::GetValIdxForPos (float x, float y) const inline virtual
Check to see which of the control's values relates to this x and y coordinate.
Parameters
x x coordinate to check
y x coordinate to check
Returns
An integer specifying which value matches the x, y coordinates, or kNoValIdx if the position is not linked to a value.
Reimplemented in IVMultiSliderControl< MAXNC >.
Definition at line 238 of file IControl.h.
References GetParam(), GetValue(), SetValue(), SetValueFromDelegate(), SetValueFromUserInput(), and SetValueToDefault().
Referenced by OnMouseDblClick(), OnMouseDown(), and IGraphics::SetStrictDrawing().
double IControl::GetValue (int valIdx = 0) const
Get the control's value.
Returns
Value of the control, normalized in the range 0-1
Parameters
valIdx The index of the value to set, which should be between 0 and NVals()
Definition at line 151 of file IControl.cpp.
References NVals().
Referenced by TestLayerControl::Draw(), TestPolyControl::Draw(), TestGradientControl::Draw(), TestMultiPathControl::Draw(), TestArcControl::Draw(), TestBlendControl::Draw(), TestTextOrientationControl::Draw(), TestTextSizeControl::Draw(), IVButtonControl::Draw(), ILEDControl< MAXNC, QUEUE_SIZE >::Draw(), IVSliderControl::Draw(), IVRangeSliderControl::Draw(), IVXYPadControl::Draw(), ISVGKnobControl::Draw(), ISVGButtonControl::Draw(), ISVGSliderControl::Draw(), IBKnobRotaterControl::Draw(), IBSliderControl::Draw(), IVKnobControl::GetKnobDragBounds(), GetValIdxForPos(), IVSwitchControl::OnInit(), IBSwitchControl::OnMouseDown(), ISwitchControlBase::OnMouseDown(), ITextToggleControl::OnMouseDown(), IVRangeSliderControl::OnMouseDrag(), IKnobControlBase::OnMouseDrag(), ISliderControlBase::OnMouseDrag(), IKnobControlBase::OnMouseWheel(), ISliderControlBase::OnMouseWheel(), ISVGSliderControl::OnResize(), SetDirty(), ITextToggleControl::SetDirty(), SetValueFromDelegate(), SetValueFromUserInput(), IVMultiSliderControl< MAXNC >::SnapToMouse(), and IGraphics::UpdatePeers().
bool IControl::GetWantsGestures () const inline
Returns
/c true if this control supports multiple gestures
Definition at line 428 of file IControl.h.
Referenced by IGraphics::OnGestureRecognized(), and IGraphics::RespondsToGesture().
bool IControl::GetWantsMidi () const inline
Returns
/c true if this control wants to know about MIDI messages send to the UI. See OnMIDIMsg()
Definition at line 414 of file IControl.h.
Referenced by IGEditorDelegate::SendMidiMsgFromDelegate().
bool IControl::GetWantsMultiTouch () const inline
Returns
/c true if this control supports multiple touches
Definition at line 420 of file IControl.h.
References AttachGestureRecognizer().
Referenced by IGraphics::ReleaseMouseCapture().
void IControl::Hide (bool hide) virtual
Shows or hides the IControl.
Parameters
hide Set to true to hide the control
Definition at line 237 of file IControl.cpp.
References SetDirty().
Referenced by IPopupMenuControl::CalculateMenuPanels(), GetMouseDblAsSingleClick(), IGraphics::HideControl(), IBubbleControl::IBubbleControl(), and IBubbleControl::SetMaxBounds().
bool IControl::IsDirty () virtual
Called at each display refresh by the IGraphics draw loop, after IControl::Animate(), to determine if the control is marked as dirty.
Returns
true if the control is marked dirty.
Reimplemented in IGraphicsLiveEdit, TestMTControl, and IFPSDisplayControl.
Definition at line 229 of file IControl.cpp.
References GetAnimationFunction().
Referenced by TestMTControl::IsDirty(), IGraphics::IsDirty(), and IsHit().
bool IControl::IsDisabled () const inline
Returns
true if the control is disabled
Definition at line 355 of file IControl.h.
Referenced by IVLabelControl::Draw(), IVButtonControl::Draw(), IVSwitchControl::Draw(), IVSlideSwitchControl::Draw(), IVTabSwitchControl::Draw(), IGraphicsLiveEdit::Draw(), IVKeyboardControl::Draw(), IVSliderControl::Draw(), IVRangeSliderControl::Draw(), IVXYPadControl::Draw(), IVKnobControl::GetKnobDragBounds(), IVSwitchControl::OnInit(), IRTTextControl< MAXNC, T >::OnMsgFromDelegate(), IVMeterControl< MAXNC >::OnMsgFromDelegate(), IVScopeControl< MAXNC, MAXBUF >::OnMsgFromDelegate(), IVDisplayControl::OnMsgFromDelegate(), ILEDControl< MAXNC, QUEUE_SIZE >::OnMsgFromDelegate(), and IGraphics::ReleaseMouseCapture().
bool IControl::IsHidden () const inline
Returns
true if the control is hidden.
Definition at line 348 of file IControl.h.
References SetDisabled().
Referenced by IGraphics::BeginFrame(), IGraphicsLiveEdit::Draw(), and IGraphics::ReleaseMouseCapture().
virtual bool IControl::IsHit (float x, float y) const inline virtual
Hit test the control.
Override this method if you want the control to be hit only if a visible part of it is hit, or whatever.
Parameters
x The X coordinate within the control to test
y The y coordinate within the control to test
Returns
Return true if the control was hit.
Reimplemented in IVSliderControl, IVKnobControl, IVTabSwitchControl, IVSwitchControl, and IVButtonControl.
Definition at line 378 of file IControl.h.
References IRECT::Contains(), IsDirty(), and SetDirty().
Referenced by IVSwitchControl::OnMouseOut(), IVTabSwitchControl::OnMouseOut(), IVKnobControl::OnMouseOut(), IVSliderControl::OnMouseOut(), and IGraphics::ReleaseMouseCapture().
int IControl::LinkedToParam (int paramIdx) const
Check if the control is linked to a particular parameter.
Parameters
paramIdx The paramIdx to test
Returns
the valIdx if linked, or kNoValIdx if not
Definition at line 130 of file IControl.cpp.
References NVals().
Referenced by IGraphics::ForControlWithParam(), and GetTooltip().
int IControl::NVals () const inline
Returns
The number of values for this control
Definition at line 232 of file IControl.h.
Referenced by IVRangeSliderControl::Draw(), ForValIdx(), GetParamIdx(), IVMultiSliderControl< MAXNC >::GetValIdxForPos(), GetValue(), LinkedToParam(), IVRangeSliderControl::OnMouseDrag(), IVRangeSliderControl::OnMouseOver(), IGEditorDelegate::SendParameterValueFromDelegate(), SetDirty(), SetParamIdx(), IGraphics::SetStrictDrawing(), SetValue(), SetValueToDefault(), and IVMultiSliderControl< MAXNC >::SnapToMouse().
virtual void IControl::OnAttached () inline virtual
Called after the control has been attached, and its delegate and graphics member variable set.
Use this method for controls that might need to attach sub controls that should be above their parent in the stack
Reimplemented in IVNumberBoxControl, and IVPresetManagerControl.
Definition at line 154 of file IControl.h.
Referenced by IGraphics::AttachControl().
virtual void IControl::OnContextSelection (int itemSelected) inline virtual
Implement this to respond to a menu selection from CreateContextMenu();.
See also
CreateContextMenu()
Definition at line 179 of file IControl.h.
References Draw(), DrawPTHighlight(), and PromptUserInput().
Referenced by GetAnimationDuration().
bool IControl::OnGesture (const IGestureInfo & info) virtual
Returns
true if supports this gesture
Definition at line 325 of file IControl.cpp.
Referenced by IGraphics::OnGestureRecognized(), and OnMidi().
virtual void IControl::OnGUIIdle () inline virtual
This is an idle call from the GUI thread, only active if USE_IDLE_CALLS is defined.
/todo check this
Definition at line 401 of file IControl.h.
Referenced by IGraphics::IsDirty(), and IGraphics::OnGUIIdle().
virtual bool IControl::OnKeyDown (float x, float y, const IKeyPress & key) inline virtual
Implement this method to respond to a key down event on this control.
Parameters
x The X coordinate of the mouse at the time of this key down event
y The Y coordinate of the mouse at the time of this key down event
key
Reimplemented in TestKeyboardControl, and ITextEntryControl.
Definition at line 118 of file IControl.h.
Referenced by IGraphics::OnKeyDown().
virtual bool IControl::OnKeyUp (float x, float y, const IKeyPress & key) inline virtual
Implement this method to respond to a key up event on this control.
Parameters
x The X coordinate of the mouse at the time of this key down event
y The Y coordinate of the mouse at the time of this key down event
key
Definition at line 124 of file IControl.h.
References OnMouseOut(), and OnMouseOver().
Referenced by IGraphics::OnKeyUp().
void IControl::OnMouseDblClick (float x, float y, const IMouseMod & mod) virtual
Implement this method to respond to a mouse double click event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented in PlaceHolder, ILambdaControl, IVNumberBoxControl, IGraphicsLiveEdit, ITextEntryControl, ICornerResizerControl, and TestTextControl.
Definition at line 263 of file IControl.cpp.
References GetValIdxForPos(), PromptUserInput(), and SetValueToDefault().
Referenced by IGraphics::OnMouseDblClick(), and OnMouseDrag().
void IControl::OnMouseDown (float x, float y, const IMouseMod & mod) virtual
Implement this method to respond to a mouse down event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented in ICaptionControl, ITextToggleControl, IURLControl, ILambdaControl, ISwitchControlBase, IButtonControlBase, ISliderControlBase, IKnobControlBase, IBSwitchControl, IVColorSwatchControl, IVXYPadControl, IVRangeSliderControl, IVSliderControl, IVKnobControl, TestMultiPathControl, IVMultiSliderControl< MAXNC >, IColorPickerControl, IVTabSwitchControl, TestKeyboardControl, IVKeyboardControl, IVNumberBoxControl, TestDirBrowseControl, TestMTControl, IPopupMenuControl, TestAnimationControl, TestBezierControl, TestArcControl, TestLayerControl, TestPolyControl, IFPSDisplayControl, TestFontControl, TestSVGControl, IGraphicsLiveEdit, TestGradientControl, TestTextOrientationControl, ITextEntryControl, TestTextSizeControl, ICornerResizerControl, TestImageControl, TestTextControl, and TestCursorControl.
Definition at line 250 of file IControl.cpp.
References GetValIdxForPos(), PromptUserInput(), and SetValueToDefault().
Referenced by IPopupMenuControl::OnMouseDown(), IKnobControlBase::OnMouseDown(), ISliderControlBase::OnMouseDown(), IVRangeSliderControl::OnMouseOut(), IBSwitchControl::OnRescale(), IGraphics::SetStrictDrawing(), and ~IControl().
virtual void IControl::OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod & mod) inline virtual
Implement this method to respond to a mouse drag event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
dX The X delta (difference) since the last event
dY The Y delta (difference) since the last event
mod A struct indicating which modifier keys are held for the event
Reimplemented in ILambdaControl, ISliderControlBase, IKnobControlBase, IVXYPadControl, IVRangeSliderControl, IVMultiSliderControl< MAXNC >, IVKeyboardControl, IGraphicsLiveEdit, IVNumberBoxControl, TestMTControl, TestBezierControl, IPopupMenuControl, TestTextOrientationControl, TestTextSizeControl, and ITextEntryControl.
Definition at line 99 of file IControl.h.
References OnMouseDblClick().
Referenced by IVRangeSliderControl::OnMouseDown(), IVXYPadControl::OnMouseDown(), IGraphics::OnMouseOut(), IVRangeSliderControl::OnMouseUp(), and IKnobControlBase::OnMouseUp().
void IControl::OnMouseOut () virtual
Implement this method to respond to a mouseout event on this control.
Implementations should call base class, if you wish to use mMouseIsOver.
Reimplemented in IURLControl, IVColorSwatchControl, IVRangeSliderControl, IVSliderControl, IVKnobControl, IVTabSwitchControl, IVKeyboardControl, IVSwitchControl, ICornerResizerControl, IPopupMenuControl, and TestCursorControl.
Definition at line 280 of file IControl.cpp.
References mMouseIsOver, and SetDirty().
Referenced by OnKeyUp(), TestCursorControl::OnMouseOut(), ICornerResizerControl::OnMouseOut(), IVSwitchControl::OnMouseOut(), IVTabSwitchControl::OnMouseOut(), IVKnobControl::OnMouseOut(), IVSliderControl::OnMouseOut(), IVRangeSliderControl::OnMouseOut(), IGraphics::OnMouseOut(), and IURLControl::OnMouseOut().
void IControl::OnMouseOver (float x, float y, const IMouseMod & mod) virtual
Implement this method to respond to a mouseover event on this control.
Implementations should call base class, if you wish to use mMouseIsOver.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented in IURLControl, IVColorSwatchControl, IVRangeSliderControl, IVSliderControl, IVKnobControl, IVKeyboardControl, IVTabSwitchControl, IGraphicsLiveEdit, TestBezierControl, IPopupMenuControl, and ICornerResizerControl.
Definition at line 272 of file IControl.cpp.
References mMouseIsOver, and SetDirty().
Referenced by OnKeyUp(), ICornerResizerControl::OnMouseOver(), IVTabSwitchControl::OnMouseOver(), IVKnobControl::OnMouseOver(), IVSliderControl::OnMouseOver(), IVRangeSliderControl::OnMouseOver(), IGraphics::OnMouseOver(), and IURLControl::OnMouseOver().
virtual void IControl::OnMouseUp (float x, float y, const IMouseMod & mod) inline virtual
Implement this method to respond to a mouse up event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented in ILambdaControl, ISwitchControlBase, ISliderControlBase, IKnobControlBase, IVXYPadControl, IVRangeSliderControl, IVSliderControl, IVKnobControl, IVKeyboardControl, IVNumberBoxControl, IGraphicsLiveEdit, TestMTControl, TestBezierControl, TestArcControl, TestPolyControl, TestTextOrientationControl, TestTextSizeControl, and ITextEntryControl.
Definition at line 91 of file IControl.h.
Referenced by IGraphics::SetStrictDrawing().
virtual void IControl::OnMouseWheel (float x, float y, const IMouseMod & mod, float d) inline virtual
Implement this method to respond to a mouse wheel event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
d The delta value (difference) since the last mouse wheel event
Reimplemented in ISliderControlBase, IKnobControlBase, IVNumberBoxControl, and IPopupMenuControl.
Definition at line 112 of file IControl.h.
Referenced by IKnobControlBase::OnMouseUp(), and IGraphics::OnMouseWheel().
void IControl::OnPopupMenuSelection (IPopupMenu * pSelectedMenu, int valIdx) virtual
Implement this method to handle popup menu selection after IGraphics::CreatePopupMenu/IControl::PromptUserInput.
Parameters
pSelectedMenu If pSelectedMenu is invalid it means the user didn't select anything
valIdx An index that indicates which of the controls vals the menu relates to
Reimplemented in IGraphicsLiveEdit, TestDirBrowseControl, and IVPresetManagerControl.
Definition at line 288 of file IControl.cpp.
References GetParam(), GetParamIdx(), and SetValueFromUserInput().
Referenced by CreateContextMenu().
virtual void IControl::OnRescale () inline virtual
Implement to do something when graphics is scaled globally (e.g.
moves to different DPI screen)
Reimplemented in IBitmapControl, IBTextControl, IBSliderControl, IBKnobControl, IBSwitchControl, IBButtonControl, ICornerResizerControl, and TestSizeControl.
Definition at line 145 of file IControl.h.
Referenced by IGraphics::CreatePopupMenu(), SetDelegate(), and IGraphics::SetScreenScale().
virtual void IControl::OnResize () inline virtual
Called when IControl is constructed or resized using SetRect().
NOTE: if you call SetDirty() in this method, you should call SetDirty(false) to avoid triggering parameter changes
Reimplemented in PlaceHolder, ICaptionControl, IVTrackControlBase, IBSliderControl, ISVGSliderControl, IVColorSwatchControl, IVPanelControl, IVGroupControl, IVPlotControl, IVXYPadControl, IVSliderControl, IVKnobControl, IGraphicsLiveEdit, IVKeyboardControl, IVTabSwitchControl, IVSlideSwitchControl, IVScopeControl< MAXNC, MAXBUF >, IVSwitchControl, IVButtonControl, IVNumberBoxControl, TestGradientControl, IVDisplayControl, TestFlexBoxControl, TestSizeControl, TestDirBrowseControl, and TestColorControl.
Definition at line 148 of file IControl.h.
Referenced by IVSwitchControl::OnMouseOut(), IVTabSwitchControl::OnMouseOut(), IVKnobControl::OnMouseOut(), IVSliderControl::OnMouseOut(), IBSliderControl::OnRescale(), PlaceHolder::OnTextEntryCompletion(), IGraphics::Resize(), SetDelegate(), SetRECT(), and SetTargetAndDrawRECTs().
virtual void IControl::OnTextEntryCompletion (const char * str, int valIdx) inline virtual
Implement this method to handle text input after IGraphics::CreateTextEntry/IControl::PromptUserInput.
Parameters
str A CString with the inputted text
valIdx An index that indicates which of the controls vals the text completion relates to
Reimplemented in PlaceHolder, and IVNumberBoxControl.
Definition at line 176 of file IControl.h.
virtual void IControl::OnTouchCancelled (float x, float y, const IMouseMod & mod) inline virtual
Implement this method to respond to a touch cancel event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented in TestMTControl.
Definition at line 139 of file IControl.h.
Referenced by IGraphics::SetStrictDrawing().
void IControl::PromptUserInput (int valIdx = 0)
Call this method in response to a mouse event to create an edit box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter)
Parameters
valIdx An index to choose which of the controls linked parameters to retrieve. NOTE: since controls usually have only 1 parameter you can omit this argument and use the default index of 0
Definition at line 339 of file IControl.cpp.
References GetParam(), GetParamIdx(), GetUI(), IRECT::MH(), IRECT::MW(), IGraphics::PromptUserInput(), and SetDirty().
Referenced by OnContextSelection(), OnMouseDblClick(), OnMouseDown(), IVKnobControl::OnMouseDown(), IVSliderControl::OnMouseDown(), and ICaptionControl::OnMouseDown().
void IControl::PromptUserInput (const IRECT & bounds, int valIdx = 0)
Create a text entry box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter), specifying the bounds.
Parameters
bounds The rectangle for the text entry. Pop-up menu's will appear below the rectangle. /todo check
valIdx An index to choose which of the controls linked parameters to retrieve. NOTE: since controls usually have only 1 parameter you can omit this argument and use the default index of 0
Definition at line 362 of file IControl.cpp.
References GetParamIdx(), GetUI(), and IGraphics::PromptUserInput().
void IControl::SetActionFunction (IActionFunction actionFunc) inline
Set an Action Function for this control.
actionfunc
See also
Action Functions
Definition at line 202 of file IControl.h.
Referenced by IVRadioButtonControl::GetButtonForPoint(), IBubbleControl::IBubbleControl(), IPopupMenuControl::IPopupMenuControl(), IVSwitchControl::OnInit(), and IURLControl::OnMouseDown().
void IControl::SetAnimation (IAnimationFunction func) inline
Set the animation function.
Parameters
func A std::function conforming to IAnimationFunction
Definition at line 474 of file IControl.h.
Referenced by DefaultClickActionFunc(), ILambdaControl::Draw(), IBubbleControl::IBubbleControl(), IPopupMenuControl::IPopupMenuControl(), IVSwitchControl::OnInit(), TestKeyboardControl::OnKeyDown(), ILambdaControl::OnMouseDown(), and SplashClickActionFunc().
void IControl::SetAnimation (IAnimationFunction func, int duration) inline
Set the animation function and starts it.
Parameters
func A std::function conforming to IAnimationFunction
duration Duration in milliseconds for the animation
Definition at line 479 of file IControl.h.
References StartAnimation().
void IControl::SetAnimationEndActionFunction (IActionFunction actionFunc) inline
Set an Action Function to be called at the end of an animation.
actionfunc
See also
Action Functions
Definition at line 206 of file IControl.h.
Referenced by IBubbleControl::IBubbleControl(), IVPresetManagerControl::OnAttached(), IVNumberBoxControl::OnAttached(), and IVSwitchControl::OnInit().
void IControl::SetBlend (const IBlend & blend) inline
Set the Blend for this control.
This can be used differently by different controls, or not at all. By default it is used to change the opacity of controls when they are disabled
Definition at line 289 of file IControl.h.
void IControl::SetDirty (bool triggerAction = true, int valIdx = kNoValIdx) virtual
Mark the control as dirty, i.e.
it should be redrawn on the next display refresh
Parameters
triggerAction If this is true and the control is linked to a parameter notify the class implementing the IEditorDelegate interface that the parameter changed. If this control has an ActionFunction, that can also be triggered. NOTE: it is easy to forget that this method always sets the control dirty, the argument refers to whether a consecutive action should be performed
Reimplemented in ITextToggleControl, IVSliderControl, IVKnobControl, IVSlideSwitchControl, and IVSwitchControl.
Definition at line 196 of file IControl.cpp.
References Clip(), ForValIdx(), GetAnimationFunction(), GetDelegate(), GetParamIdx(), GetUI(), GetValue(), NVals(), IEditorDelegate::SendParameterValueFromUI(), SetValue(), and IGraphics::UpdatePeers().
Referenced by IVPlotControl::AddPlotFunc(), IPopupMenuControl::CalculateMenuPanels(), IVKeyboardControl::Draw(), ISVGKnobControl::Draw(), IPanelControl::Draw(), ILambdaControl::Draw(), Hide(), IBubbleControl::IBubbleControl(), IsHit(), TestDropShadowControl::OnDrop(), TestImageControl::OnDrop(), TestSVGControl::OnDrop(), TestGesturesControl::OnInit(), ITextControl::OnInit(), TestKeyboardControl::OnKeyDown(), IVKeyboardControl::OnMidi(), TestTextControl::OnMouseDblClick(), ILambdaControl::OnMouseDblClick(), TestCursorControl::OnMouseDown(), TestTextControl::OnMouseDown(), TestGradientControl::OnMouseDown(), TestSVGControl::OnMouseDown(), TestFontControl::OnMouseDown(), TestLayerControl::OnMouseDown(), TestAnimationControl::OnMouseDown(), TestDirBrowseControl::OnMouseDown(), IVKeyboardControl::OnMouseDown(), IVTabSwitchControl::OnMouseDown(), TestKeyboardControl::OnMouseDown(), TestMultiPathControl::OnMouseDown(), IVKnobControl::OnMouseDown(), IBSwitchControl::OnMouseDown(), IButtonControlBase::OnMouseDown(), ISwitchControlBase::OnMouseDown(), ITextToggleControl::OnMouseDown(), IPopupMenuControl::OnMouseDrag(), TestBezierControl::OnMouseDrag(), TestMTControl::OnMouseDrag(), IVKeyboardControl::OnMouseDrag(), IVXYPadControl::OnMouseDrag(), IKnobControlBase::OnMouseDrag(), ISliderControlBase::OnMouseDrag(), ILambdaControl::OnMouseDrag(), IVSwitchControl::OnMouseOut(), IVKeyboardControl::OnMouseOut(), OnMouseOut(), IVTabSwitchControl::OnMouseOut(), IVKnobControl::OnMouseOut(), IVSliderControl::OnMouseOut(), IVColorSwatchControl::OnMouseOut(), IPopupMenuControl::OnMouseOver(), TestBezierControl::OnMouseOver(), OnMouseOver(), IVTabSwitchControl::OnMouseOver(), IVKeyboardControl::OnMouseOver(), IVKnobControl::OnMouseOver(), IVSliderControl::OnMouseOver(), IVRangeSliderControl::OnMouseOver(), IVColorSwatchControl::OnMouseOver(), TestTextSizeControl::OnMouseUp(), TestTextOrientationControl::OnMouseUp(), TestMTControl::OnMouseUp(), IVKeyboardControl::OnMouseUp(), IVKnobControl::OnMouseUp(), IVSliderControl::OnMouseUp(), IVXYPadControl::OnMouseUp(), ISwitchControlBase::OnMouseUp(), ILambdaControl::OnMouseUp(), IKnobControlBase::OnMouseWheel(), ISliderControlBase::OnMouseWheel(), IRTTextControl< MAXNC, T >::OnMsgFromDelegate(), IVMeterControl< MAXNC >::OnMsgFromDelegate(), IVScopeControl< MAXNC, MAXBUF >::OnMsgFromDelegate(), IVDisplayControl::OnMsgFromDelegate(), ILEDControl< MAXNC, QUEUE_SIZE >::OnMsgFromDelegate(), TestDirBrowseControl::OnPopupMenuSelection(), IVDisplayControl::OnResize(), IVButtonControl::OnResize(), IVSwitchControl::OnResize(), IVScopeControl< MAXNC, MAXBUF >::OnResize(), IVTabSwitchControl::OnResize(), IVKeyboardControl::OnResize(), IVKnobControl::OnResize(), IVSliderControl::OnResize(), IVXYPadControl::OnResize(), IVPlotControl::OnResize(), IVGroupControl::OnResize(), IVColorSwatchControl::OnResize(), ISVGSliderControl::OnResize(), IBSliderControl::OnResize(), IVTrackControlBase::OnResize(), PromptUserInput(), IGraphics::SetAllControlsDirty(), IVSwitchControl::SetDirty(), IVKnobControl::SetDirty(), IVSliderControl::SetDirty(), ITextToggleControl::SetDirty(), SetDisabled(), IBubbleControl::SetMaxBounds(), SetPTParameterHighlight(), SetValueFromDelegate(), IVNumberBoxControl::SetValueFromUserInput(), SetValueFromUserInput(), SetValueToDefault(), IVMultiSliderControl< MAXNC >::SnapToMouse(), SnapToMouse(), and SplashAnimationFunc().
void IControl::SetDisabled (bool disable) virtual
Sets disabled mode for the control, the default implementation modifies the mBlend member.
Parameters
disable true for disabled
Definition at line 243 of file IControl.cpp.
References SetDirty().
Referenced by IGraphics::DisableControl(), and IsHidden().
void IControl::SetGroup (const char * groupName) inline
Assign the control to a control group.
See also
Control Groups
Parameters
groupName A CString indicating the control group that this control should belong to
Definition at line 273 of file IControl.h.
References mGroup.
Referenced by IGraphics::AttachControl().
void IControl::SetMouseEventsWhenDisabled (bool allow) inline
Specify whether the control should respond to other mouse events when disabled.
Parameters
allow true if it should respond to other mouse events when disabled (false by default)
Definition at line 363 of file IControl.h.
void IControl::SetMouseOverWhenDisabled (bool allow) inline
Specify whether the control should respond to mouse overs when disabled.
Parameters
allow true if it should respond to mouse overs when disabled (false by default)
Definition at line 359 of file IControl.h.
void IControl::SetParamIdx (int paramIdx, int valIdx = 0)
Set the index of a parameter that the control is linked to.
Parameters
paramIdx Parameter index, or kNoParameter if there is no parameter linked with this control at valIdx
valIdx An index to choose which of the controls vals to set
Definition at line 114 of file IControl.cpp.
References NVals().
Referenced by GetTooltip(), ICaptionControl::ICaptionControl(), and IURLControl::OnMouseDown().
void IControl::SetPosition (float x, float y) virtual
Set the position of the control, preserving the width and height.
This may need to be overriden if you maintain custom positioning data in your control
Parameters
x the new x coordinate of the top left corner of the control
y the new y coordinate of the top left corner of the control
Definition at line 296 of file IControl.cpp.
References IRECT::H(), SetRECT(), SetTargetRECT(), and IRECT::W().
Referenced by IGraphicsLiveEdit::OnMouseDrag(), and SetTargetAndDrawRECTs().
void IControl::SetPTParameterHighlight (bool isHighlighted, int color)
Used internally by the AAX wrapper view interface to set the control parmeter highlight.
Parameters
isHighlighted /c true if the control should be highlighted
color An integer representing one of three colors that ProTools assigns automated controls
Definition at line 370 of file IControl.cpp.
References SetDirty().
Referenced by IGraphics::SetPTParameterHighlight(), and SetTargetAndDrawRECTs().
void IControl::SetRECT (const IRECT & bounds) inline
Set the rectangular draw area for this control, within the graphics context.
Parameters
bounds The control's bounds
Definition at line 308 of file IControl.h.
References mMouseIsOver, and OnResize().
Referenced by IPopupMenuControl::CalculateMenuPanels(), IGraphicsLiveEdit::OnMouseUp(), IBubbleControl::SetMaxBounds(), and SetPosition().
void IControl::SetSize (float w, float h) virtual
Set the size of the control, preserving the current position.
This may need to be overriden if you maintain custom positioning data in your control, or if your TargetRECT is not the same as the main RECT.
Parameters
w the new width of the control
h the new height of the control
Definition at line 308 of file IControl.cpp.
References SetTargetAndDrawRECTs().
Referenced by IGraphicsLiveEdit::OnMouseDrag(), and SetTargetAndDrawRECTs().
void IControl::SetTag (int tag) inline
Set the control's tag.
Controls can be given tags, in order to direct messages to them.
See also
Control Tags
Parameters
tag A unique integer to identify this control
Definition at line 405 of file IControl.h.
Referenced by IGraphics::AttachControl().
void IControl::SetTargetAndDrawRECTs (const IRECT & bounds) inline
Set BOTH the draw rect and the target area, within the graphics context for this control.
Parameters
bounds The control's new draw and target bounds within the graphics context
Definition at line 320 of file IControl.h.
References mMouseIsOver, OnResize(), SetPosition(), SetPTParameterHighlight(), and SetSize().
Referenced by ITextControl::Draw(), ICornerResizerControl::OnRescale(), IVNumberBoxControl::OnResize(), IBubbleControl::ResetBounds(), and SetSize().
void IControl::SetTargetRECT (const IRECT & bounds) inline
Set the rectangular mouse tracking target area, within the graphics context for this control.
Parameters
bounds The control's new target bounds within the graphics context
Definition at line 316 of file IControl.h.
References mMouseIsOver.
Referenced by IPopupMenuControl::CalculateMenuPanels(), IGraphicsLiveEdit::OnMouseUp(), IVDisplayControl::OnResize(), IVNumberBoxControl::OnResize(), IVButtonControl::OnResize(), IVSwitchControl::OnResize(), IVScopeControl< MAXNC, MAXBUF >::OnResize(), IVTabSwitchControl::OnResize(), IGraphicsLiveEdit::OnResize(), IVKnobControl::OnResize(), IVSliderControl::OnResize(), IVXYPadControl::OnResize(), IVPlotControl::OnResize(), IVGroupControl::OnResize(), IVPanelControl::OnResize(), IVColorSwatchControl::OnResize(), IVTrackControlBase::OnResize(), and SetPosition().
void IControl::SetText (const IText & txt) inline
Set the Text object typically used to determine font/layout/size etc of the main text in a control.
Parameters
txt An IText struct with the desired formatting
Definition at line 285 of file IControl.h.
void IControl::SetTextEntryLength (int len) inline
Set the max number of characters that are allowed in text entry.
Parameters
len The max number of characters allowed in text entry
Definition at line 300 of file IControl.h.
void IControl::SetTooltip (const char * str) inline
Set a tooltip for the control.
Parameters
str CString tooltip to be displayed
Definition at line 210 of file IControl.h.
void IControl::SetValue (double value, int valIdx = 0) virtual
Set one of the control's values.
Parameters
value The normalized 0-1 value
valIdx The index of the value to set, which should be between 0 and NVals()
Definition at line 145 of file IControl.cpp.
References NVals().
Referenced by GetValIdxForPos(), IVSwitchControl::OnInit(), IVTabSwitchControl::OnMouseDown(), IBSwitchControl::OnMouseDown(), IButtonControlBase::OnMouseDown(), ISwitchControlBase::OnMouseDown(), ITextToggleControl::OnMouseDown(), IVXYPadControl::OnMouseDrag(), IKnobControlBase::OnMouseDrag(), ISliderControlBase::OnMouseDrag(), IKnobControlBase::OnMouseWheel(), ISliderControlBase::OnMouseWheel(), IVMeterControl< MAXNC >::OnMsgFromDelegate(), ILEDControl< MAXNC, QUEUE_SIZE >::OnMsgFromDelegate(), SetDirty(), SetValueFromDelegate(), IVNumberBoxControl::SetValueFromUserInput(), SetValueFromUserInput(), SetValueToDefault(), IVMultiSliderControl< MAXNC >::SnapToMouse(), and SnapToMouse().
void IControl::SetValueFromDelegate (double value, int valIdx = 0) virtual
Set the control's value from the delegate This method is called from the class implementing the IEditorDelegate interface in order to update a control's value members and set it to be marked dirty for redraw.
Parameters
value Normalised incoming value
valIdx The index of the value to set, which should be between 0 and NVals()
Reimplemented in IVNumberBoxControl.
Definition at line 157 of file IControl.cpp.
References GetUI(), GetValue(), SetDirty(), and SetValue().
Referenced by GetValIdxForPos(), IGEditorDelegate::SendControlValueFromDelegate(), IGEditorDelegate::SendParameterValueFromDelegate(), and IVNumberBoxControl::SetValueFromDelegate().
void IControl::SetValueFromUserInput (double value, int valIdx = 0) virtual
Set the control's value after user input.
This method is called after a text entry or popup menu prompt triggered by PromptUserInput(), calling SetDirty(true), which will mean that the new value gets sent back to the delegate
Parameters
value the normalised value after user input via text entry or pop-up menu
valIdx An index to choose which of the controls linked parameters to retrieve. NOTE: since controls usually have only 1 parameter you can omit this argument and use the default index of 0
Reimplemented in IVNumberBoxControl.
Definition at line 172 of file IControl.cpp.
References GetValue(), SetDirty(), and SetValue().
Referenced by GetValIdxForPos(), OnPopupMenuSelection(), and IVNumberBoxControl::SetValueFromUserInput().
void IControl::SetValueToDefault (int valIdx = kNoValIdx) virtual
Set one or all of the control's values to the default value of the associated parameter.
Parameters
valIdx either an integer > -1 (kNoValIdx) in order to set an individual value to the default value of the associated parameter, or kNoValIdx to default all values This method will call through to SetDirty(true, valIdx), which will mean that the new value gets sent back to the delegate
Definition at line 181 of file IControl.cpp.
References ForValIdx(), IParam::GetDefault(), GetParam(), NVals(), SetDirty(), and SetValue().
Referenced by GetValIdxForPos(), OnMouseDblClick(), and OnMouseDown().
void IControl::SetWantsMidi (bool enable = true) inline
Specify whether this control wants to know about MIDI messages sent to the UI.
See OnMIDIMsg()
Definition at line 411 of file IControl.h.
void IControl::SnapToMouse (float x, float y, EDirection direction, const IRECT & bounds, int valIdx = -1, double minClip = 0., double maxClip = 1.) virtual
Set control value based on x, y position within a rectangle.
Commonly used for slider/fader controls.
Parameters
x The X coordinate for snapping
y The Y coordinate for snapping
direction The direction of the control's travel- horizontal or vertical fader
bounds The area in which the track of e.g. a slider should be snapped
valIdx /todo
Reimplemented in IVMultiSliderControl< MAXNC >.
Definition at line 402 of file IControl.cpp.
References Clip(), IRECT::Constrain(), ForValIdx(), IRECT::H(), SetDirty(), SetValue(), and IRECT::W().
Referenced by GetUI(), ISliderControlBase::OnMouseDown(), IVRangeSliderControl::OnMouseDrag(), and ISliderControlBase::OnMouseDrag().
void IControl::StartAnimation (int duration)
Parameters
duration Duration in milliseconds for the animation
Definition at line 430 of file IControl.cpp.
Referenced by ILambdaControl::Draw(), GetUI(), TestKeyboardControl::OnKeyDown(), and SetAnimation().
Member Data Documentation
bool IControl::mMouseIsOver = false protected
if mGraphics::mHandleMouseOver = true, this will be true when the mouse is over control.
If you need finer grained control of mouseovers, you can override OnMouseOver() and OnMouseOut()
Definition at line 538 of file IControl.h.
Referenced by TestCursorControl::Draw(), TestImageControl::Draw(), TestSVGControl::Draw(), TestDirBrowseControl::Draw(), TestAnimationControl::Draw(), IVNumberBoxControl::Draw(), IVButtonControl::Draw(), IVSwitchControl::Draw(), IVSlideSwitchControl::Draw(), IVSliderControl::Draw(), IVXYPadControl::Draw(), IVPanelControl::Draw(), IURLControl::Draw(), IVKnobControl::GetKnobDragBounds(), GetUI(), IVSwitchControl::OnInit(), OnMouseOut(), OnMouseOver(), SetRECT(), SetTargetAndDrawRECTs(), and SetTargetRECT().
The documentation for this class was generated from the following files:
IControl.h
IControl.cpp